Return-Path: <mariyka@geocaching.voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 005A91420455
	for <gbr@voidland.voidland.org>; Sat,  5 Dec 2015 23:58:33 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id C5D403FD43
	for <gbr@voidland.voidland.org>; Sat,  5 Dec 2015 23:58:33 +0200 (EET)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 9247134E0072
	for <gbr@voidland.voidland.org>; Sat,  5 Dec 2015 23:58:33 +0200 (EET)
From: Mariyka <mariyka@geocaching.voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <56635E09.5070700@geocaching.voidland.org>
Date: Sat, 5 Dec 2015 23:58:33 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="KfDK2pQ1dSm8eLJ5NDSOFuK0UTdB9hiwa"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--KfDK2pQ1dSm8eLJ5NDSOFuK0UTdB9hiwa
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--KfDK2pQ1dSm8eLJ5NDSOFuK0UTdB9hiwa
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/TWkfaLfSkuVnm6NkjILSdFwMcnQO0xeHr0cErtsedGRm
pSVyupf4SErUP5Q/hjUXO5vanslSjCJMqvJxmoxU8MYvpujAHH/Aq1NbuGWDUiFn
QiAFMEzryztZD6KWexJK3KBrRkeJaU5FzJv36OXyti7au/ynf2zAmkje+YvYexDs
S2SbMkDQm1hD+N2/dFiYy99CAvb2i/MBtPxxEdEiL5wkhS0pMzj2hMPoAGM8+QSj
aGPtOmwkKmPmZKfrNg97QTDxqbUg2Tp21tV+XNV6nU3fkmkT2dp07LQEPK1ECyT8
snsWtzZE/t3pzraxG1TEzbFBLnssYc9rrX1Bvp4LHryoLZXu0vLetibmjfDQxEHa
LLwc9nlySagp1uP0ZlqpGJZziOmW4vV+n/fNq5S8Fx4M/bYC1djy3F+riquBekdN
FLGOK85Mr9XRHwAx+/mr7FgA0vccGfjn/Me6s7CaZqKfWgIciUYozWgPxsCV+jC4
Uyz1kbAQwOi3pNbaADgEC/402fFkvL9K+8K4pu0DX76zFwPjDghl3kAzeO17pBAa
PGm3DeecJsT7PLPkW2PDabhAA/5qHktM8X2C/K3m6kJ56DbettaPx3rXF5rug+Dm
B+4iI3dVdVCgQenBcexn3DteTyWqcRzvKea0OdbbdoE3xTwiC1vjZop9A8mToYl0
r4xCMNzmxvhJJi7J4kwiH0Rxn7Gdn1KYqTPtsf2VDyZmLKNoJKQ31YPRPbtKeIHJ
5sl2ALG9I4fzwrrheYs2Qa1/NHevHn1n1omjxGBbz5Q2HUXoRiJiZkQQHMq3Abmg
PEmStycDCnxCYualfF0Q6i4Aop324ewqK5rDmTLKRb4GIKsKtMiYmab+v9cITPpw
2uRJ+wwS/316OMmz7VkcyBg1rwxm0djXRY3ktgPwohRh+E5ailK/Fs2U9tQiTVuz
VXkpSdTC63MxvVL0RXE2MIBDGodH1nD8C6bDyRgmkHbgXImlKvPP3MwyRFnj9KVy
fGuYG9ElDLuWNMEiZvWGmrKFAgwDv2ykB/A39a4BD/4rKzg3vrbOh16OfOIwOp9y
On6C7hXfEIKHDut8Yt+oU1B0uHuLbgnH2D9O9M8+SVPxAdn3/pC9JjrfBovGNTfc
KLvS7Eri+cvEvggzZ0qjRH8hWez5QSFGU2YrqqiCbsWbL9S7eD5Giatf+6qGX0F9
xlp2MP7lxQ9kMyyN0WoFMpar2A43HHfUboT4Dcb7cHcfOpE9m3PrfdbU6e8YfkCk
6uXt55PsW4sTj0kz8sOxvkayBfOoneV/UskDBdM7F7yY7kOMKIbL9lQii6q3DrNW
TFUGHQ/zgPSVee2H0zUigkL5tWNBGMV8bwzxI51WJUJHWwjsto1cv7IltKUfVcdN
FjEeemSeRMrPiMLb1NVuT+qjfbNNC+4xdqnDjJYlAQkwW9nFRVOIGr/xzMGr2+es
1y7vvinTOsZrwWe5qtBwjvhs6rtP8Yvh2kkysMaTK7ZwibFTtw9tl4IJpQQ3hAUE
deQhqCRMxfNMEHKeD6EKsdSJZtmyfYAaRLlo8ebxkHtTMZD/YhsLycFrFjRNevXy
GjeEur2p7N5LL05A/6ZdzM7YkE62eSOsnPtADmQxSManTy5KAPCNkVIsUtrS6YFD
zLAOnByz4uWO1gyEU8DkrXbCq9AK7I7zafQu3z4V8a2R/jmAlbvlbD9wQlbZWVmu
0hW2pbNkCmw+mcpKMkSW6dLqAYavew/MDsgQ32aca9f3fJLEQL2v9tMJvNkcxCR3
zutRXuZsnOlHJtQ0NfveXEgGHc0TkkkvoJHY/HC1L2FImDhtn7Uwdw4D8OqaBjrk
L0TGH9wvlVCyD6JK2gSaOnBgku0/vSCzb7wL2vxvvYrxpY72ME4qgTTGB1PaJPLg
w/vgTlQwSw87qdHw4e+nfhTIn9zbiU/qTmH2LU144ZBtijsvjCPKLEWBYwIh/+iO
halVP9iMyYNXCHnbSel0OlxOx1r6xZskkWV2rmY2F1irJsmHA55EONKa/nwpzmPc
HSUB25RpNB49ZgvxSeV1azHmDtVRykPrA2Ruy+4WYYMVzDaAJtyCAXqejPI3370J
lcd2ByiQ0ZmdaoGGFz5pmJ/uzkiBwxapetVv0b4VEggOqeZ1X759mYUsxxpKtttK
89vr4G85LK+HsYcIA/GG585rH8SJAvnrbSrdzUooyjgb7yQ10T8ksEgbEHjY1vjI
regLnu49En8y6gN14EL9sGeCArfiuCJ0zlKt8/8X314vxQ5F42EYazKHikZUPkeQ
7P8KGU8LDhUWJeHg5bi1ni9olcDcJGtjHvjDtM0yjV8OSiqKHxSzvgK756wJ2FZp
vJSMm0IdH/hs9pHna2cDHj3H8JTVOpXTcZzsf/lbdPN2AaQJ4CzNAPc42rz/RrXX
HUtsGusfpZVKgHAB+lQFa632G6qiCMa7rtGIWUcvK1wDD4mRznCpYVA4yIcn+5Gm
uLf+xr8rP2WYro3DD4qGXcwWxSd+EyagxxDrQn+nSXzzSQAQcxDM1wfTJkGL3alJ
0p3PKXzxlrbTuawhSNuiHRD6a/6WGXQYyZiOm4UV4ijw0zsK781qTpC1lAqRFZKv
ehwhYGuh7ZSoZiZjYUtxqHFcjz6c2CgnMOiLVT6uQk3ioxlXJqcwtf6xuuNvG3KQ
Yya5pbneT+FDPeqXkfGYnZBro44rHJ4MpZeD8fnfxzomfHWehsuM5oySvZ8JwAEJ
2HnevFocVvfuzHl4npWznFpa1rvq45zdXMZPhFLkh2T8vgYASYP1DPj6cQo2GKRg
i0XTuVU1QceUvwoDvvkk8M3nveKcICz5bnEFGghE5uwz2hIGrReX71oAiaUSY18d
LG6CBq07a+fheQir+a+mS5bYz+VSNv9/vRYaOyyu8eNpWk1vfKNzOE6QIPZ3jRR7
w6BgCy1iinS6SAiiLUQsldCsvnl3Zmm4vrcOteJshLcAMaLdOCcUf6fga46dmoSJ
ZOXIOmLtBYkDXTTCk7c0FXKtvsPgrPmI+kcwW4IPLtNqI7WVNhTBWBuMHiO/vPcT
lRcu1EwEuhyFEC1J88m1vcPhe6lvssbHNRkXArg+egKlUxGRaHL/csamn1Imx4Eg
w6iouw==
=l/RX
-----END PGP MESSAGE-----

--KfDK2pQ1dSm8eLJ5NDSOFuK0UTdB9hiwa--
