Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 459D3142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:43:46 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 27932409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:43:46 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 2E65A34E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:43:46 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C111.5090205@voidland.org>
Date: Sun, 18 Oct 2015 00:43:45 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="fSVa5LtfLIfNFXbkWRFf8CXi7dkjctRQG"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--fSVa5LtfLIfNFXbkWRFf8CXi7dkjctRQG
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--fSVa5LtfLIfNFXbkWRFf8CXi7dkjctRQG
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv9EBsM0MF+qIQ3VIfDjlXVrenVV5xaIIy/0ZaP/RbQddVd
NFgptUysrvbb74rzbaipfjQv1YRhMuOs+Jm09oeRqJWwgTnZBz3vk9eIjEJJXfMp
8Ud0svXrpyHsUKzzlHEIUCSmm3geWZRYvnQw+fwLq/6O/kZ+WambtJlC5nrn2kO3
Zmh+jiaYMlwldqcYME77vnpJQBQyLNl9rcAGllhH64sUy/99C2ITDA8TUIAryA9E
1Q8YIalVoJgAVqiFAnFgtUyss2JJK18+H65B6uoHv3QNqY+FHJcWlZlS7M0/7ckI
gYQPNnj6Plke2ZuukQyWxb59UptlNRbNDQAxHMaUjirRVtTGLdhYQggptb7N8cLb
/BNhid0LchYc4wN5/TCRodqW66veALv17SQJ+nKyFgWpHI+NADNIzJiUFEfBS7Fz
BuHPKZzQk/aVv0DGRxYi92rPGreiGufMFzby4ZXHSE3kMMbbYQWNaGo0HuaFNRE1
yOBtIlPv2G/1NVi4YVd5C/9rEiwwozgLd3rUymIluKSGF4zRhpeVQjwhXEiSpBoa
UuIB7bv97lHU7PK1zd0VXb0jF5V0Y1A2qXl6NfcjG6/EkJWYR8DQeRMY8IYxhjd6
KILWo568rpf3bGKYqnaFiWzRIv4jJzlHWI2PWbQLpB34fubH7tnf4xp++Z0L5RHP
V1GsjI33XhFvGuhewk4ZTJUVs2Bw2ugihyxjoLh8vPmJTOh8q6k3yjcqpW9fEoiE
XtlIqxmttsi9mjEy5L2LlLgW+WixVmzildSX5bt7/DSjy6dXYFQlZkqHq3lRKufH
cclgSegjE4hIaUhkulUo11uG23P+6tuK51UMJM7EIiLl5l5jFqvlyKhJHvAuoZXE
Vjqm5PxqaSJsHNc8lWQjLhHva1HjDj7aLzSDxK3jDhfwEEO6cz+rNLWLJQaGIoPc
lZvvsG1UynfTh7boMRkI6rE7yaa5oKcRgB7OV0YiSs+UHL67CpgOWOrp5Am0vDqO
DrOLfvG0kuQqsYv5DiKKKO6FAgwDKA/jsTGjsHwBEADBHLEJvHyxZ7/FJUO0dnDN
g6x7fzY8+uZBb2dKO94yprJ5SvothIA4mTI7ArpsZvGjufGuGUpVxa/MiuPtUf9I
UsxJQDlS2M9/R/ZE9yTVgmoWqx9c7hDuTDzYQinxPCNriCLDHa772866F7rV8QoD
KEnHpV80hmw0k5fawbPmeKJUd6wCWfqo6hYD9fAYLTzvceg2dJ3L4LKJuJ2PCoCw
RrE4qeJjNzRzEmPhVqo5ZItBJpR56Jk+c1iGzYfqx93BcPXc+oadKg7FNg+PEwRR
KB2y6bTDBh386GDLvBy262xY7hyBrz+gjZ9v7P7UD3dHG+CEzsKEBoS7VZBYY3Y+
nW9c/anrz9WFoA5BsJ0knoch/7k62FANub3QJ6BaKXdehhA3Fm1bd5WE2wJC2Fi/
0w94oYbOkg0cOVF/NLZdXKVG0flznHNCPupiheIXDq/NHabDZOTFbKDDtPm/nw14
pQsEQBL9EUAZhC6xxbPaLACj/y1e7K1qVFg5MpsVao3I0o/yk6Yb6/YmwjyJseLy
WbFSDh3Mgf9/SqoOMWljoeieqJeOhMvFRWPvZ7cDhogWwVt/CN67A0bseEO883A9
qgHoI5ao3ULFiUuqIpq++Rk1+o4wjhwxb6ByKRAfGcK/d2lzPQltiP3wDxyEjP1G
9MouFjfBac1rj/dd1XwmTNLpATBxRvzW/4bFCiWdn4SszErk7A/sYAs1eJp5seAT
Gxw6uy/FgwyRz6E7bqhFGsHK7yYblBtS9EHI35IjhKfmpM555QFYZGIz4mbyEbi6
LpXRUF1AC6afBN29ZeRR7ADv4kf/ujSj3U4eTTFYgQVLXl00k8jlVr/43xmoPhGa
5guEvg3Ln5LvDNJ/AmJVUsnqvVYCa79+1caiJ0ccLxdMV7rpJxbUPe4RPOo1tVfU
9XdOy1YzdDK+7JbFwjkQnXyqPLa5iWdZUqqZBM8ig/NhnHGcvtKHEFaAKMV5JL+f
GpEMyuwWKs/5zTgLcz6J+VjigTsy7Pdi/a3EZQ+RDfNzVpEMD2OtyWC6anIBWmsQ
TcCKeX2FUHY9ABVp5x3YDi4jdCU13hxwI+EAmgiGzwcmRgpElKGS8IvLP+nQBtzE
svSWGa8/kcMaKN6o/nKlmsIptBMnjTbWUi5s5KLXID9hscYXweWDBg2p+GSzuH03
jjH/HrREPfjTnsgboDUoiMEO+FcKad9zaDfsyQj7adBK3ZOSDm5GM1VRE02RjcYW
3RI3vQsEcnwb+ND0zUlsGl4n3ZeiBLf+OcZkeiTwohrthRD5ad53MMdfGNp9LRwu
vcYEnL+6FXO8W/wepzLE055dQmzXyu1PyYyyF73z8W+sLPu5gdbArpSTaI5irC8I
HFLBNAGXUhFV+DsGuzrIfJQw7r+zCPkU42hILKcpABDN1K9pyQXlvkZIPRmHyuk2
e3NOH2HGKD/flsG63dsXFoUz5YLvyhCixGlN2dylrYBdTZJPUQO4KYvhdS48AjIK
lQRZoLv+n40VeemIztC3UAgO3boiO3BKb6JozfLX/dWW5p2dB+i2OuKhSuvjbudi
p+ug+1L1xxShdi98YomLSgq/E5TmJj9SMTzJIRQ1Xav/KAjQGh48B8EMGoZdXz4J
SDx6794f3AG3GwV4Dq1Sd+nD+YgEt+wcUZK9wcOFbMm8s9EIeSzG+ICnkYZVjcYM
KRfjUGmqADld+VCqtVSWkxRffz1LQ+k8F5TjS++9USdlVACtsPGxolD0s2gWxz6O
34SqX5E74komR1b8vZ8fv6OcTuSzV0fEtNjxFJoBLedJvKeyBZKa9gNO6VsoADL/
3+QG+cA9Z3PV7wS/m4RFK/tgSPOawEmhD2O1p6cP26wNbn4qrM6gxK6aYmXaiwwt
nlpRsUJ1EU/kw4L+Q5b4qkFm1+VYA7iwnqmZ9rNpsxByvRrlNwJobl3LcM6HQdjM
OLj//xe+QqDRlEKBM4MBfOYpTyb/MJn/NlcPXgQB6pJTW+ywk0yRr7k3oh1ACJ1q
hkjJ/byopE0zNncPc0H3sXdpsjMhoIHc
=lobc
-----END PGP MESSAGE-----

--fSVa5LtfLIfNFXbkWRFf8CXi7dkjctRQG--
