Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 414E3142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:14:39 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 24F45409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:14:39 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 5700334E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:14:39 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C84E.9050402@voidland.org>
Date: Sun, 18 Oct 2015 01:14:38 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="B0fwSuoNNaECu0OO7n2f4M5NFGGnLU3Nl"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--B0fwSuoNNaECu0OO7n2f4M5NFGGnLU3Nl
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--B0fwSuoNNaECu0OO7n2f4M5NFGGnLU3Nl
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/QlxBv2b55QU4r3XXu2nxrvcv/ND0u8IzVBwaAfP8oFoR
nBkiLy6biTS+HSapU03Gf5RPbzCstnr/jzYxePB1So5U/DTBTQy5+awRQ+cZqdm1
lguPWT08/joPHQtS2tD7GzGKE57vPfmhEC6uzD+6cICY3BX2dvBymwz1fgYNk4PW
xDIopiThgQKW8q4cKwVgVqun2qT8MdDmcKwtDeZS7p2AzJyjBxdZOi4O3jV90rEw
iwfgKTv6FQXy7kg7pWhbCotPynTQU9+XFhmBP583XZCkYU+8uw05Yj5eP1/Wj9MF
PZ55ToEQgnEgQrehDvA5o5QSblHkY2zrpoX3kqq8Ma//fahYTLqB0QrVRblEbnNl
unDrbB80OzvIoo07g3X/TBRY2M8HWbDq+spQqyPSuaVtjXRP6t22Kj5Q9oZDYrJr
Oqhj/igi8emMcq0Ke8QvjJvClIkoBfZo5Bzsf9/CYiBj8EP0Rj35/JzEATWKNt5f
vrboi8qSTsODkyyg65uaDACNizs+HhPtQKNIPs4knyId6kAOOYGDanP1tIe0lZvh
6TO85vd9PLMGU2WKZah04EYcJpQsP7luObrDY8hs34TRBzH4F4n9WZFiyckYwasJ
2Lzr+sUigDQCQ+qmFq0PKnrGf2qYqKdD6NzAm4BCxi99sqPNMBqOhXNO72CaXKYq
T2hyWX6tbZHy2xcLtHPLbGKz2JQczlRJA93U0PAUAmuaXKZimDeKikyiuVv3cPWA
P7PUkCgbMxw3glpbq/kS/02w/GDb4fKa4f4tyORzZEPlWyAmlU/BcaZTyNS7pqcp
4Hm0AYGccIl3UDP0KLdL+sQo6zNi6UTYzgnU/Dr2MNC+c7AYw1p0sgFErmRZcpQT
tq+m/clksc50NvSsyUGWIuKMwR/+is0qg7UDkP6U7+kppbcftHPJOMC3zXAWtVLa
Hsv/DYljg1KIb3yTcRknyZxkiOS+FRnJAtayFjDznjpuzRPZckUbtuEC8kpAYknV
0sZPjzamka8PXuuYZHNABGGFAgwDKA/jsTGjsHwBEACYc/X9WHAZkn/rRHv7XCqM
+fqb9g5nHPyF0n187SmZ+yPTGmOFeBdce1S1888VYIQo6QepDQl/witQUj2NuxCJ
3F/12StpKoNTfzRYPS/e9oJrDsO7+lFCmw5mni8OfTSC8nbJFnUA+UTZXCPKnOIM
+vlVSq4RRixIM++zFRq74VaWq07PLW+gcMM0MU508aZCVRglZ01FtVo0d6QppsDn
XfcX3208VwpgfolVvWkU3aCIr0CD2jiE0A2TSJFg6bHDNrROszfV8d0bZBg7ex+H
28FlD/ppcGuBCwPbiFNeUJ0pNUfHM4I8uXw+xdoGqTGt6XLvLAdGv5V+KJXkDA1Y
HWxwQFMdbkqz7OPL8kqna/yC1cPxmARtjVyzHmcFTSKwpY1EmQ/8ycV+hvo57CmU
JdAYaDl9PlKNLOLrOI6Mr5GVOORl9Y2Ki9j6zLXKLpJxRduDyTBsBKpq40rY5Bqk
W6NnmXTveSPlXEO9Js6ukY2E15suE4SLue9eurvb2/J65oZGOePknZQ9UQ+fbqAu
aNO5HXuASo8KTtbcpuVNdOYkyQmD4aFs/XeJs7++nttggBrrVMqVVwiXqE2nsU4e
oBONtu0JhykeViXAaHi6p54+WYFXpk/Iwuj9M/LOd9r3NjTEwotXNxTS6TmBBxer
nRlm398uz35l6+zeN3XEaNLpAa1O83TA2olPRs1i1s3TtKKJGvar9Kpqcxf/cwaD
z1Bh4UCJ0zJeTkkuqiNUvEjd2MZJQDxsijv9Shrd/DphwZulOBpENZEdO1JvfMFp
YcQgdlRHsdvPPmSVLa36l4LLOEO0vr8eiaUWbys87U49ZGOjTkT/crA5OUCYK5Hl
UKZVc78Pirx/wWTHDaWCigKJZ2VRC+Klmzdu02mo7EKjteTIVRe/NG/erRuH5SpC
BzjA9JYbmTTgjQBPU/5KK6Tt5dmSXQ73PkJT2y3fLck3j6uSzEtb7SS+znNJ97w0
dDF8n8vVAQ3GRYNLCacHRALi6axwUNgDIOQ0K/0Huca1aqmnVEJ5hyfDRRxkl4lS
BWsWpoWOKgVMHDP7fslkolAK60yjawIiUyKAtXGNLzCjI+pqbgLncnp5XlXYjtGc
2nnd6bDVnkg9K+gdaM0g+E4GkgxNyGSomUbOuvxxTzsGxOOrSugNnIrHjY48n2zm
AOuRmnRHNjdTK7c+S8diw9gO3aBrsiDtrEp9lRnEs73IRh1aNfoer862sA4w6FoB
JgkVJOaScz4A4v53TeJV9cjC+atpZVEfmMmwfu0gd7attFAdgy/QeZa5gwk8+Am9
v2RhEG1tVIVX4lHfwLRioyUEtxIpXtSTy5NLumi/45rnRKRdGPQbOgy+YV1KLgGY
vwXA+x+OtcaNnr4RC6X6z+QwAmj1YFYV7eKNtKkixpalegcuXBvKota6Td8/xx+9
xxkZKxXTdcBsOiz2am3Z4WRBld0L9/A471YAYRiOQf1zfrDMT2od23pk+gkJJbq9
lL88Q0+Dg3VztrjGjJurVzwyNJV6fCzscRN4veBF8U7Gj5kTm3b4NcyHojgnwnYh
C2dSBkdhzSqXe4AiVpXPwtHfTsG9a7metf+2I41XkV9BPYW1v+CG9C2Piwk3X3q/
wInsS/22EecjNsuuDhbTvp31K3gbHIFSYVMTU7I3uxFsCQVS/RqUQWKEM5dp5e7v
021hmBw9gpiw6/wv5NmQMqhbZzjjGLkZ+0/WWLygs1RDikS2mUtc0zK3jo8rEGAB
eaQ0Yw6kFQBCgzMvnybqZs//kQ57i6B0sETNJrdd1CSSH6DnIx8YG6+coCORz/PU
y9twIw50GUBKunnuNNimA9GlZw5DxJC2x3S2+Sd4AlYCkZFuTvoocU/VdcWwVaKK
NxuHzt21J+be56Qr/KPdIebejvPLWuxRzWj30FLxbn763MySCNmqz9QktAaUjBkF
vJB49ErjBK7EK0Nzd7et
=lf/5
-----END PGP MESSAGE-----

--B0fwSuoNNaECu0OO7n2f4M5NFGGnLU3Nl--
