Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 8F32D142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:12:02 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 70021409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:12:02 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 9F2D434E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:12:02 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C7B2.5030501@voidland.org>
Date: Sun, 18 Oct 2015 01:12:02 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="miOgip1PtJlKCuN0cXN8jEWfEk2lr7fot"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--miOgip1PtJlKCuN0cXN8jEWfEk2lr7fot
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--miOgip1PtJlKCuN0cXN8jEWfEk2lr7fot
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv+IGNu/exu2WAz0Et569oO8SxNYlq5QJnjg29urHZQtrge
+YZLzRjNsVCWV/Hay9te1ImHM5C8QizKHu5xOFYl1qPnb3mRnGydKSScpgMQmczY
e/f3JErI6Zuh2IsEIzRdpyIqKucB0v5e33dB6v1IiQHsVwvrMTa53SOa6w2PtYb5
4Bga7r1rTeT9AXUvm4cZybaBmxkck19W6B6zmLkqGNqhT1ihA5ml9TyqpHCTmJs5
RIYgCkDuMKhykwj2xclYCGgUaYe9iwwo6tczEwIdWHVYk1o8wImBFFBbutmWBHCk
S1WjywbR+cAdzxZcSUMGFF0TBcZIQ6DPw3csnkAp5ArV7oC0mZACPHban60RLuan
IRIqo9O2rwgb45/3TR+t3YvwYaFrZ9VMsHpDuHLTyB234XlMCOrduhJpwNCLGTt0
wFI28SEoL4QWDZNLhh42LhcQ5inVd4YQ13vcle/ghClKZ/CMpLj3AUIEZ9qqWyl4
FMeXJlx4S83tPG8CDPs2C/9KcVG6kyZM7ZADmvW+uhmJmZbbo14Nyb9oJqC2n83V
v3HRzMzUoe0BMVR7f6mMMHa5DscBd94yOW7wU1dxtSHXXWCi1wv/xi7+IvxqP0tp
ZwOlzJdvYeBYJwb9NBrTCGXrTAXGlKd3P186MRVKjlmGrl9/2ckbFEnWAicMEweW
AC554i+Nbjz41g89V3lHU6GSi8NnyZlaWVfwwGhG7z+Oxih9OrP1gaqqvLh3K5zc
LkkjNzOx//y088rvsw5uvFls+L+LV3FTmEkyU7SgjXkLM+7hESEmeNUgZzZk4Lqy
J6FVc9BrAtNsV7utTB0pujiIiMIWd8VOVuxM/dBB/3x/qXrvuPoSnbblZzZd/1Ip
jDyY2SNr2PP8z3P0tKHug4/Y8XGfZirj6p1yAvdxafzUb9EW2zHvfCUYDgSz5xgN
WybIToRKwF+jonsbr/8TW/N9+ecJI3XOtYyxLbb5b6EGTCCY/bJIlFJsJiiozR9Y
YSugkdk2ls7bcGLkhJaWvgaFAgwDhSqg2e39KKABD/9ck1YwWONqQq7Tiy9VYCW/
CVKpWgYDDgGkuZ6o5PvVl+Uso2+yGPwMqRTZnckooDUyma89RQgEn2EsrRwXcS77
IgVPxyo5QL/tctTp39DwYx8fYtfLHYyb6V6GqozSaQnp2NOPwJkg8FV85LLc0zjE
DhmkRtakXarGX/lhAFY03KmaZdmKBZ7CfzZzgLby0UpPzLdwZlqYeeKiSMrwiqOl
Z8NEk7qvXMVseryHXL5W8DHwVJ39F0v6GKXs7AGG87MtVPO+PyVktjUXxy2tEGPx
/WfZGiroAVp+jyrgum88rHv6uqoN2KjP2/dQK5dIpQ1d+nHa4nEpTmxrD6Q3WtFi
kEaPD7MdE2+FBYQCBuQazzfHVuWw/a1KDqIBchOM1jQZmsoM7A668zD0HvRHHG2+
TGZXvQVodhWCg3ebdONbFh++/NlGzyXVoeildIySOmnZtuvS4kNI3Xu3FbrTJWhH
VeMZCqBQvoqFUl3imXsS/CVOB2SfK6E0QLZ39q+0jCXXLeuq+aj+0p42jO7XA24l
5BQVIiEhgvzBUAfy5XKAfIa77E/hVxO4oXh2YQHbpl+JVaNZFqwkd4jSHQA/d9jX
phEdIVJV3dKT6bcABImTowPjnRjDDMKmXRPJvq7bbig1R+xL1w0VRabazz0p0e7D
z+tVAvMmBSCfVHeWPTfsk9LpAartPQ1sxVlUSmZZ34QSBlVa/Xd7TrSvMqcbmT4y
Wvket+ENqh2f5C6xCvu7mOZT39JeuAHaZr/7ZuksZcQNsTrgcYNp3a5EuhpeX3lg
OEOdKa6vQgqnCIBLhG45Gp1q4Psa/oEgQDoUvOhkUJTj6Qkv2SiVDT6lfjd2DNOM
EqwMGAD04Jd16i50XLfj1sT+NflKp43Mrr90Vni9q0m2iaQoa3MA6DugnFG2pc5t
MXijHReiqwNai2ZZ8tfHlWOVxcl+XWvNwDGSWo6NS7foKC2y3R5YEJdR0ux/fVlW
wEYj596zw56PuH/Z+TcKPMBm+XqRdMn+MMakgl+YZ+v8Pj1cSLLV2Bl1Pd2kjJxs
SGdfBU9uvprHbetI5lTVMtMuXgSwV/ibeDsxhzUQt/Fhgcv9w2evtUFJiRnyZFou
GfKGMtrkanJFLnu6i+rfIVxE/8CpqvmAk4Phl8DJeBQ0AeHoIr55UcocDUHDq6mm
oysWI3XpvRQ5YrFqifpGah5/A//Yos404KQY6awPFTUXVxmPDDuQb99VAibEq21W
uw/nrUj3zCsdS8GV+JUJer/uh0jjveZNFeLqNzgaZ6JGsgfFQk0nIkO/9kHpi3Bs
bTQbuWJus0ucwokSdXlWfjgXlvrXMKkD+SDr+J5uupmi0f7psPcaX2sBDs+Sk62P
ul/A9wpQzxUy6QsJ9CKNw1EBkt/QBujgU8PUFPiHn/EopC+41jDdqQf/UMaQail7
T+BjZhWzG4JuPAQ6UkTbSpmomf0/bCUgrg8iGBO+VntWMJ2uyv9g8DXgK69yfUzf
x5Uk/JyI80bQeEvXnw34N07X5T9KuZhoID1jaryspIVqkR+vySV4qJljwE1ERF2e
Ci/OfsZwVmVpYQMZhMKiZ1f3rgxUWpgT8TE+xCQIJ1yH+7hOJ9/Y3+nVG+elsGCj
JB7BRyJ9QMeC30Gxxf1nnUy3Bx0iS2BbOEZMV+iaJhukZ1KR6c2cKXypQ3PT3i8M
R3CNGU78UbEet6V8VNU++nJkjeGpWjjtZw/ORlnafoeaJ+nLgiRAAjg9ePoz3JIv
mfBKXvlxEG+qDye/mA57oa47STJ9q8x3gab0NQvAv2N3hxAhPv1Eo3jHGQKf00kl
scBZhz2o//G9hkFssHnltlbCfqU63dWaBH4t5kLw/EzS+UcyvMRRZm48jASr1U55
InsijGzZ3EL0t3p0O10zWFCp68hA+7+zLHlnEO+MupNB2Rs2X/N2VK1TOC/1i3Kn
O6lRDXFyy2S0DJw=
=q5Bd
-----END PGP MESSAGE-----

--miOgip1PtJlKCuN0cXN8jEWfEk2lr7fot--
