Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id E6D0D1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:11:08 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id BFCAA40A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:11:08 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090668; bh=yZYrKUaTuYQty7w2s9iS0Yed1KoKRvCYVIO3gHO8Ibc=;
	h=From:Subject:To:Date;
	b=Y04pqbC3MPbv5Zb33Od17UK8P5iViC/Fp4sJjKTT+ZcJAydz5IwoSbatK7DDRf3gc
	 EB/mXJdkPAiW0l4SAGpBtPpGo1vcVfCA+WKfgz+CIcIl2QBddDzOPdpERmMpPf8Au/
	 9Oz7oAi6bpbQnJxv0I4RNIXtf0IwyQioRYPAL7KE=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id B5A3F34E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:11:08 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090668; bh=yZYrKUaTuYQty7w2s9iS0Yed1KoKRvCYVIO3gHO8Ibc=;
	h=From:Subject:To:Date;
	b=Y04pqbC3MPbv5Zb33Od17UK8P5iViC/Fp4sJjKTT+ZcJAydz5IwoSbatK7DDRf3gc
	 EB/mXJdkPAiW0l4SAGpBtPpGo1vcVfCA+WKfgz+CIcIl2QBddDzOPdpERmMpPf8Au/
	 9Oz7oAi6bpbQnJxv0I4RNIXtf0IwyQioRYPAL7KE=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F5E6C.4000006@voidland.org>
Date: Wed, 2 Dec 2015 23:11:08 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="MRBpEownqCmrsliD2sHsMwKTwjmDnDEPW"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--MRBpEownqCmrsliD2sHsMwKTwjmDnDEPW
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--MRBpEownqCmrsliD2sHsMwKTwjmDnDEPW
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/fNHQdpzV9HrUXahxt9j7EsdbON9ZytBT6/lXvl2MXQFH
+YbhxJfcz/xFtW7L4vUdwqZQA/llYihyYZIOcH5QSwrS8UbQrUTxoy4RJICSXwUV
RDv5TQRzOFucFfROe+kYBnSYdHU4E/5uLsDmWV3QR2pNSJ9uLfl3fqCrKoC953vC
XZ8ntj4EVqQtqIUKDDYHZySb/2UN4R2FpLqzNIfMA42jwcCyLisexSbZxEgZCvJG
b5kZTcDeKWX6EO6GbloCouEpfjqFCpBdkeLjlguuyn3Q51+N7xGUmq7q63Ar1Owl
f8TurDwMBLxtTqUObqScgNAghf1huTsPMQyv8vuStXQG+eDFS4MInMCJUOtzQ3N3
RY5g7Aq6hBcQAq1aD+fBbjxx6hRPhI6EYJr32r+j4wisYuNhI9+Rg5CVMU2/N9Iy
uqfg6w5+s0drVGi12SHx/Ad0IbuHhS9kCMH849XNCbTVMF4DlHRsCZWcyTgV0nby
Fy/s5nsdiqLLEFWVvVnvC/4nk+UxKaokxh0uncLG+vSzyJsV+GYaer2ZoiQNunF6
QWhAcc2SNrMCh8cBNm10TAEsLYlUklgXOX+VktHNlXwWRV10x1rfFCV8sWfrj3Zx
ppWHT5h730uqz/cwBHrL1sg5P4XtzaaJFMv99IOockum67cd6xipdOx+j+AUXRVk
dLqyho2nH0zcL3rruSHI1ldLt0js/VCI7cxYHP5OFTzCMJW8NeLPlBvLjee2Plou
Q0wJtgVHWUmIPzd8S+MaY2DqXfNcNsM2o524zN1YvMjgiF2agwTLK1Yu2A0xL31G
k9wwO7AEyxyoRQIoEFfoEq13ofyyVOw1rRKnMKZehW718Ulw0GI0opVoMr5/lDiL
AroGE71xU4JPXqakfmP3EvSrEwzNqQCDRjMf0TTSY9J81i9dI9SDVVXQn0w4AA//
rxepRqPAAJ+O2K8VYXsb27HO/GxRqxzgH61t2o6aroNPpHFRdo8UoMmGJRjsoDTJ
+zyzCxrkiioAV5/UM+Ffi4KFAgwDKA/jsTGjsHwBEACGu/7Uu8efzu5Xt0WxKgru
HYnKWCyWwKJoLVtGnlbp7CMfXf1QveLWVDUqq2XTI/aGlkH8cKkoGVwKlCCIO+LI
uJ4M68jh3YX3K5y0D583M3nWTWOMuFXfW8vtvj1t7vQjzZcaoySYUDLF17XFFrUS
xa3OVD6dgRJz19ejHZV/1Vh6qbqADV9bL32gLjgFwM76cmEI4y+1SxoIAdG0bDrI
R6Ikm9PTWcNovSPNFyp919EpdZRXEOVDE9fZoXWC3LPNqQT9oqyIGV+d2bBrqfLh
48ulY+GD24fIsL+YfFbrnT0mp13J2dlSWL8zKL2LDg2rjQ3k6LRJOROwkIZjjSC0
OvmQsn/cSOf2BIE/Djte1GHIxxtPyaz2TsaBvEYhpag/keaBMlZtv+as21hAe3nG
Gtzzk1vdQwy2Ja1cXUXvuNyWF9VafDcVSsvBfDDsumj/U12hqNSMS9UC0yFI3xn6
aiVC/4wUB5UxiG4Q2u9VTkwaw1LRody9nl4N+NWgTVHE9gE21uzgrspl+NYSFPsj
VXU6M9TX4te/hzVedRMIyCljQJCb0QBCeiiYzhsxWNVheqO6smH43IPl9v4cWEsa
js1dvZhmtsQgE6H95ThSEmuSr8hS15rlOS/gTd/FVpzI5kMp08fL6DRA63iKXoWs
lDZrrqEImy9wCCOQ2Pwh4NLA3gEVGvNMrUV7d2F1ehndTw071XqL8mJxMhuv//lc
JHfEbOmNxWhaZSPQtLz80Da8LtKTgO7x1jHXmNO7Ykc840ljkmDzxggt2EQdmKGA
vy4kUh29WpabkIGqTHo9OHv2adgkMCXlz6pQXWu3jFbUMAQ4EwBkpCTiSQskQIu6
EhSMY9yYB2XxNa0WxFG04c2O389+ND42ezcUP0YSgw/0kpTuO+KjKPO6G7UalFtu
L8hSBXWTUwZHJsoXrow4NW0uX65wcV3h7r4LSJSJNeKJ3zK9HUrh8uQLzLVIUC/p
Jer6S3uA6v2L+2QK0Ver6LDS/CnRjA/ND5wHGTdB4qZBwHPTobYUsUSfbJTAsBYK
rwqixFvLH6OLfcG/FSzZEyGx3FQieLrOhMlmakQKguDMeh2k8Uy8/cXW8MDWaSlX
2Pz1owxUbFMKBZ8tMxhf9m4Rev+v5/+tLRbeXl27vmvHWiwOtJUh/iEP4GWw3s7Q
YTYPZ0ifkM8nvkEZWrDIsn6Mt7ykLGyRLWTPzshEQ4R3/do+0uklOz8vIBAsW4oj
MA==
=v2T+
-----END PGP MESSAGE-----

--MRBpEownqCmrsliD2sHsMwKTwjmDnDEPW--
