Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 9FE8014204D3
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:56:14 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 7F7F6409F8
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:56:14 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 6FF0C34E00CF
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:56:14 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622B5EE.3070705@voidland.org>
Date: Sat, 17 Oct 2015 23:56:14 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="rNAgJQuHpHjlI25gU92x4tarMF5g2Dh0J"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--rNAgJQuHpHjlI25gU92x4tarMF5g2Dh0J
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--rNAgJQuHpHjlI25gU92x4tarMF5g2Dh0J
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQEOA6uQXY50FwtKEAP/aqDtn1o8VLaOL21pcLYnLTPsfjJ7RTTBkzEtGehrtrOt
zCbRK18SmPxidyl+jGpTGeBcVhb6xy2QoQZsZk7CMNJKID2JDouDM4CohgxV+JZr
yGCYOrGlh9xTrpPevlvwJdLvR/2seVR+udze6+RNLjZ+x1UEs3wZe+zVvOPmLOkE
AJcbHFJ2jKLrhuY1956YarzeGZRX9JxJvgZIinNkCf73PcF8ZC4vScHFTHQU6qAa
DhC6AwL21qxFI9NUBN48BAWLQd7VTEDw1qfB9gkdX3gJQo5/StYH2qw+g3dGqQfd
+18cXc3PzU0sAUt3OJ/mRwR1RCLgQCHi1eqtVagYcbuAhQIMA4UqoNnt/SigAQ//
V1QqvjWt/bWq2wZyNJxtwvoIIlzZn1rL0+ZDBmpjXC182HLg3nweKmgJyOn4MfgU
+RcK1deMj4AMfZRndnD7iG+y8N5iI/ZVzP1rEFwJdVq/8kPuPUMVZ/VpDlYaYf5v
YoWHgVrRbnSYt9fbSEhiLft8SgM5yH6gBJp2CLp5izwBVXYEQ75gf5Q1QDSzSzWU
AsBDhJiURDssOo+KVnIP4anoDNBqDC/vfhLuf7KuTbXNSpsnHMrXbtVbmlzGUABf
m8qkoHROk4sZAHCapaYGN/rDNPden6rlNljwy/fadxLdx3nrJJFtFT8bMds09dvJ
Fr1MzqnvBOihWJ99oz2V8Gh3QOhL+W99R33NkAfLOw3EV0gHolpdt4dndqHP8poF
n0Il+KFLqhfevEFDsEP/YXrczgeiPylqprrSpAMXIW6cy9uSL7N3Ypd406zHcP5i
vFMAQXK+JFnqQTuJYwOnj48Rx/gpjSpIouq/LQ3adg8V74iKAsuiSihHRQoUpJGN
WlwuZpJZv/02qD74rXd4kB53lCzCISJqRdMIDGuGi6uOmleu3g8f1SEvqPOrS9gv
o0Bt8NJPVNX7NCVTz5ErdVjbaf9XN8rhVdUIRJbd4MIJ2xIdW+scuJh1IgeUpcuM
SUg/EfRHZGBftX2MBdp5+JCn8CP9rIGEyap9dBjtKLTSwDoB8bEaCAxJi6JcSlUM
rSBgVc0GvMiq+8OowtdJSrm7Wi19qhY75CSz75eYzWAnh47TZqGy20Wjp5kGvMy+
iQS87scoIe+11pLPqwtnWFTmi3i5Dqe6L+NDR5RJ02MAXQynh+E4C+Himky6Lb4t
kAxOrQkN0dxlPDePrGkJa+U8khvioPD7ysyzzOBIlvNgY+ST1CWME8YHut7iyAws
CLycdE1L1UjHF1ARTY2FaWmOYGazU3YgMbxZ1xMo8cLGSIpyb2o4bSEjeiBBD15Q
7cXDWEVM+n96BchAfr+3k+imbgqgBUV9ILdX4zm6U9deXvYDtmJCSmvLRSsj
=U3y+
-----END PGP MESSAGE-----

--rNAgJQuHpHjlI25gU92x4tarMF5g2Dh0J--
