Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id BCB051420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:49:27 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 97EFC40A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:49:27 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092967; bh=IaAjSyDK+eN8K5/iLkBqcS4+AemE/20sUDKMWIGWzEA=;
	h=From:Subject:To:Date;
	b=PA469aVmtwrrnz/pB2NtsgmUyA/RE3rPiEirsDOJ9ypBRhM+RCRuGXZoGXBh28SfL
	 i9quHQCTWNdptQhlyGtbjYBamd6mU3BtVHcOHzpxhhaUhrex4LrG/cF36srwuXlBw+
	 9AWyL/bLBkNA/AwunU3n0+pm2yxsRrcNMiBL7JPM=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 8245934E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:49:27 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092967; bh=IaAjSyDK+eN8K5/iLkBqcS4+AemE/20sUDKMWIGWzEA=;
	h=From:Subject:To:Date;
	b=PA469aVmtwrrnz/pB2NtsgmUyA/RE3rPiEirsDOJ9ypBRhM+RCRuGXZoGXBh28SfL
	 i9quHQCTWNdptQhlyGtbjYBamd6mU3BtVHcOHzpxhhaUhrex4LrG/cF36srwuXlBw+
	 9AWyL/bLBkNA/AwunU3n0+pm2yxsRrcNMiBL7JPM=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F6766.9040500@voidland.org>
Date: Wed, 2 Dec 2015 23:49:26 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="Qg1E7iq41mmuFiFSBeQ9I64Ex8PbPUChM"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--Qg1E7iq41mmuFiFSBeQ9I64Ex8PbPUChM
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--Qg1E7iq41mmuFiFSBeQ9I64Ex8PbPUChM
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv+I1PE+k2sTT+kcH1ycuBveWQatEcfh0A8Qzgfgyuown29
OQyQbPau8sYYOyGPLk3L8VSHjPHFNhcsLuRY8lkCA8GQTzFU5gqDuViYw6oCvCgn
qGKtke3jhQ35cPhDikpjBJ16GSKwbzwjIB36cUXXjbmMDDfg3tr/5gduzVXfQNW2
dOTIp8WyLzbeaQQveeOG3qWwbRjO7L3MrCnDEDOJyKAYW+iTGzpkBpYzzEzK7Zc1
WeEaUVkwBg7r8NBXTMcX6vELwTCDduS+oz4BRdVgSYlUJDeQyMMz9MMjEMsZ8beR
FuxysJGv6YGfy8HFdJVDmn7CxxAgYYN+LRLZ2O+zCVCTkyfX3LsSPBFEHInqE5bW
FTJhulOFDBrzNdH9cesdWYJWId8qKSVM4j6QlNYhqAx3G0vNgJ6SfnEUqXO7TZ4q
F3qQw73Uf07UkxC9XGPRH6qFBhL9WQMATAC8YsTFychAQkExaxw++6KiygPfe9jC
HAmCPMZSHHExqb6IvK6bC/94bAvnma+95BSeF/WySj2TFO8CDmT1A5J1Y37laWmY
3UXErNrb9zP/YTJZG/NZ8IAwFdtQULBWxw9JM0YaTcoAqgT/C9noO2TSQs0jot1h
sSo/l2tS1wGCA0L/nqhyANknjTM/qYGiBMuI9QhBVeAXZUVWQlasdVlWv3EyIVhC
1acGsrJ2xnNyoWLGZDUpRaCEUfRz0IU9gYaSmkUiSDNvtgBRW+B1GQjV8Wa+aqWg
dOmvilWgoY8YOVqcFEM387j8ON81LCt+VJFGrLcSz2K37P+0AfWTxx3K+ysJNIQl
8HEja+YO7RACEVLR1yVIHkEbqurTve2P1fBckUjbH2ow2voxmesdFcZOaN/ZBtNK
tIUDmCCRsFZwONnyOeOcrjTvPg1mHiGmZq4dJpHxcjSQyEQ17ReDs/pC5YQAonCf
VvonVeDvdNlSyIF+k+Tbow9PdhyNaU8sSJOjNVi/iHF7H5+7/vFC++o5TosR1peM
PYfaILMIkQsnV93gtYrvwhKFAgwDKA/jsTGjsHwBD/9/CRZM/zDdJIvk8UQ82psy
zEWpVzGaCsHXNPcyD9/TKQ90GGgu6TMIC5Al0SMNKmm1vV/a6RvMn7BzdV2AtjWj
Ha6Zjuny/tolRcPEY4eMUpkBipRmznphEVxW+t5/wP2X9bWUmtbetqBmSXyVigVq
V/qIbLd9KfrqXRXkIk40osZ+iEL+NxwXF06V/OywIwh5ByuyB08cEDfTJmuAHgqf
guVP0h70vOmcrdqOdnyYYvKGedSZV8vR5pVlIVC5s/e9sBAVu4U8Yv3sRc5HpJJ+
oPWHmSxTm1NsY/cJNZdPYQykaCM0U7vnwCtUWYM5iQ67HZnBviw0JqL+nVs5bTUN
nzI/qEpSKsFppYc62/No+3bmXTe9llZVx4KbaqThN3AmQ+GufsU0QE3D2zlciEGv
vzcXSAOWf4umjcZWWyaUorTWKxuW1I4bGoeXbbl5NCM6V9Eab40a1o3amagpi8B7
AHFPDxhX9bGx2iP5gwB2CS9QguBK2PwP34kkTftkfBxNV4IaMb/PCkCjDV3FclU6
+/MlT4DUmzz/6T+uMfinx3j5dOS9LXjESfbKMZyFJ8cCHhwthnzSn1LJA+qMmpaU
4wA+8adkaSyVtmvlkB4+iEdit88EHozq+rEijIiQVib9dldFpZxU8NXABq6M0BBM
y/hWnjnFr9QASlfEiDzQodLpAf4gzLWc0pmFcLJ5cdAbBjLuFNUrJLx7Bq0vvAzj
G3ETOdkYSQp11OU4MahFntLX3hKf44B/viJXf8w4vZdhBv5LS4j0wV8Oy3/xWm7L
r+OHTZYHBlcuz1nZmAJ8NSWSrTuzX+dTdUGN3m0jYMnYmUTd92ayur1sx6ZchmfX
ttwPiq/yzGZL7BkrObzHuMOo3LWxMAJWjTqYd4WxC3Mkb+0xF60UVo+2Spz65dw+
x5UXGky+r+KVjfovTyLf0mpgZ3Z9N+GVpFMIVs+MjrBZN7mOOhEXJUwxA3m8GpmD
WhVgPTdpcMp8f8+jV+zEijpiv0Ksx4NsTaHk07e5ZffOxI/ZveinnJu4Bwm1SOM5
rubEzOFLKugazjoBj5QYO6vsN4IUyrIqYV8dwyf9yByjGW3m2bdCPCqU/YcGdSTY
M/oXPTiIC1Y8CTolA9IQV7GuHtWo9RIVY+gl/C0cAvST72jZJiQtLG33H/CnRnc8
xag8m5YUdJKIVmNGvLM+op1ExS+ilN4R6OQxKglCVLRVCmBqjbiEOVSwc8FXifV3
2ljkGk0lpKepOZq77gqmPkhKh0OXm8zTRJr6rhONCGCfJJYnpacrcPBoLsO8EPxS
DMJWC30TImfBIjR3ej3K/Nt/wLjPsWc1hBVj8Z/1XKY+L1mw/YJ0tMu5ji9HNYER
/PXA7JFFukeACfvU8/TcUVAhgx/Kwq6d96RfFINt0C58LxScRX+QBDGrjveFAl0+
i0EMcUjcMejwMDvZl/CVMLPTuR/v0ElayoyI65E50mdCnlNLYajllacNUqEX5p6z
AK1nEeN254WZg4lJO9XEHg4J3pHOasoqD5nnKC5+FEf2gULdwJjmjbWii/w7vAdZ
3sYeHnWTXxHv3utmPQYXD7H4frvOAFHiQ4P59RwQ2Ea+4Cv34kReVbUx35SflQ3a
JMnIaxdkt+3Ro3hZWgFITD148goAc360BF/uDEkPwuiS1T78b5umVJM/RoZZLFv2
CK5PJtPus84rzbuyIv2nBuZP3TF11ZhWgo33LfFk2AJJ83gZ37iFwdZmrvx7Y21f
afhdFW00RCsJdkHkRA2SdILYTgJnJg8UBQX9xtxWWHkuRvnz8v2+vA0uSnhZh4dl
9JycfAEdPlu+VP8EWWCdqCPYa9sPyhCoJySPIJtFI1mESfrLbcxmTQ7uriQakqjW
KeaUbwzRsCCDiJXV0zxRqCrisSocpP25zpqKFQygfLV3uLdpUJBXJBAHX65DtbLJ
=v9Sr
-----END PGP MESSAGE-----

--Qg1E7iq41mmuFiFSBeQ9I64Ex8PbPUChM--
