Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id EA11F14204D3
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:41:01 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id C9C8B409F8
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:41:01 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id C8DEE34E00CF
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:41:01 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622B25D.4030203@voidland.org>
Date: Sat, 17 Oct 2015 23:41:01 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="b2QCCRtrSG0QxdGhCcjVcLeqe3JJ3kmhJ"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--b2QCCRtrSG0QxdGhCcjVcLeqe3JJ3kmhJ
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--b2QCCRtrSG0QxdGhCcjVcLeqe3JJ3kmhJ
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAwAiGZdSyX4V8OEgd4lB79P9uKT7Laq+dJaT5J8NgR9Zgci
HYE1JWCLljWvpSiBGbVgXOC0BLxG8UEgQj4t0fB3fTfeS+7vA6ekKbNZI8ekNGo1
C9xgPj4FaYGSsEnXKl7xqWaVgYek7qrM1Z1r0V7oXR66CTTtNZPQXAfiWEDYXHki
jX8LjA3w2G1RUYoW5mvRWHM7coJKifjZGc27ypHzHu/2F6gOrvYbHHuHy8MH1sP1
EnL6pI3AnFJn8TWOiU+qnmnyUhPlQ82yD3G32WIvBPHiscPSpLwVoZQBr0qI62Ke
lBDSoDkaGYnsCW9BX70M7gxZZSyZebna7I6lIIzpMNDyDXrdbZtwhds0AgcvIZCJ
74D4btaMMqNDwb9RSXggw/J5uEI9mehh6Qfn2shjkbjMBH2NTxdFwMTR9VlhMRPj
WU0FQ8lo4gEwM3MXu14Q/1VLvhTmLxm2MOakZDzNNlCJntVhCBElNVYSzQ0TKHPd
WbB98rNhLciYLeLCW4c/DACKOdpXupHfrl57DZ5+CSfnTpizfOIF2+RNBOl5YZT3
fVjTLg12EfDvPXQVGQ0tV1a24Sc5NjqEuxTnilEaSdZ8dp1zKlTnDIWnOGBZl9ex
hWTctRrJsleVv15gqdwgpRDruB5nRtESGruWTF6IvdVOpvifes5NOzrb8R90WHN+
lkJV206lPTBafe3CKBIVVlzWftiICEhWBZxFJHQ9NwWWbP2f6oqAs0YK1n41D5jM
nuBYJHoF1KV4qXV6qAA2fAaErGSfPkEJiZIrq6uIcUzNGM7YxWLsaHhAf9Ir4/A3
pDeWW4eYA1t0izkp5cC4h5pHlxHigcv58KmRJMXLIcw1ahFHZk0XNDmbFZZNgjNU
WVFEfz56Rdb9z5Xq1TgtIczYdDrf3oyTmiZeeEsnkm5uzycNAWEXNG2GaUkpsTqC
w0byvWunPOPLuGiaSJrrSlDWpOqZk/CFd3vORL/J2Z+Byg3JcimtgYLuldlPJ9LT
2J8JqawKp9mFTYBbMyEjAsCFAgwDhSqg2e39KKABD/48S+9qbE4Jc+aLd3FL8412
Zey2/bE6MD3XqWdRnGNVpCMygxJOMQ3xHAKhcsEByW3fDTNNEP1XmWBKLv4nKNV6
CHJEat7C6LL846nK31QKIeuCtYBOSIiogt203e/jotpAL9to2z5f8nb4QqjNX0tC
FhGbwe/AufCpfLDBc+Wpa5CVc13cr1azlU3Nugg1OH981+qiyVSDtoZmIM9Javj8
PdJpLA7LZAujiyWO4FOsBxNrJNxgb1OeoxL82XebAV8e1zyraIadax1o1u4lwPQi
rwWU2yQm/pep5wWqzU3Pshb5nUIuCzBIFy6bWfB6MOWUNTXDGcMGfNeVe274Ekld
d18lb+SfvL9miOeOdVFFELdF+6HAyzLzrc3H/vh2BkGqTYd7MN/aw2XNyNwn61KU
roLLH4qf34GMGWgKQd+IzRQjNgASYn8uO20XMfwn/Ol1hXlc+zAJjyC39dvZoSBb
on/lCEJV+x+QW5mBu+lkKRm0m4sJe0kS6wZJXujsEdwRHLF5zGzfAw0euWjB9oNc
C58M31a6sAWvLBmDmO4j59a8BSuwk4gj1nBcgK0boZ8Gxn2QZLhb0yQMCYS9oHtK
2Wfn6H3BvgyKhfHulc3CpB0PdMOlv36gvSfp3yOzAQ2hLwEJUX+f2l47J6TaViPV
sDRzH9mwbjgx23H7L2BWMNLpAdTVbyrGEmyC5brMBiG8Dl1YL6eTHqN8CTTtZ97D
VRVKc+hIWpTj8iGsg0fKwMSu53og+AqbrK5+QzuIpbscjZoDr5aLrZzi7LyLdAxN
mUQUqlu/GIf26+iC0A/y/HyT1EhzcYpgy7Pk3CGYPcu7tblfRMQ6KkUGWelTUMCY
Ct5M0kphcV/VIIoaT78yBD9V1/0ivoGb+yljls7QddiKr7sy+KdOlLLnxFV0w2o+
MGiEUuYjE5YyHN+H0GDUmZgS2jr6eaH6L4gXf2lC43Cksi/8DMMXSV9pTzvh/EEn
13dhK/TvjEXskdPLFsjKgwo/FfR47o5CoaZVrJTEo7HBsHdITIbXqMqInvWm/3qE
+7qDDEAUEQ8TYKkugbzmraLaQ/+mbi3ze23NQYdBrdDDCRi0QGl3wNK1CFSY2XES
rUHeo2O7/gjHh42PNjhYSIEj3B+y+UIA/d85bdY+XN+z67nn2pEuiHhzCirEAZZ0
0opNJjfoS+I2zAYVOiDRFvQSd38xC5zOX6zRv2cuGoVbJAxVsvQxeOsIHvGs2KPk
2yUZ+U7t9rnS3vbURjP8R4GUPzDAoJSYyfvuv0BcYPo+WEN+CCZwaaWX1NY8+pmX
WMBoPAmCIVP7B94gL2Lj7iCszKaUWXVnLV54Q4RlTT3rTcoQx+OpZKhykTK8hCkh
7N/AiHIijQM+h7eJbnH7ngYJjJQb1xclQNAAbx8IYbMqv4e9bOxx3vwPjce0NGtQ
L9bV4Y7IEc4M6wtqBn0a7PPWWcdGl2vvFqKcvuzMyjM2lmy3AVjwN7qNEgMUMJJA
0wcRf8GMcFRTdJnkWi1O029Crah68BvfyP9zobfcaCVAAFaeHroJqKOs9GSPt+Bn
FDlJyOlf2P+m7ynU1A6NKN4xJ0rxgJjXD0USpUc4Gox4sMNBZ6e4dUJ/56iBGQBG
ZoybsQjet0wTIlFaxHYrZV9DcTQJ2OdriaCDNKm3neMMK8P5D73WtXqLiAvAHbqt
n7vkyTDFIy+q5Li19gjmKzEsn8j29Irs1rPVBK4fF7OEk3UEKbBIgxV9VFhbNJZV
LyHEjJJDWEbVEjXNC+mfioj0gvIiycBHhK93JdXHFroTEDeL5Z/U1cdqJ9w=
=y3qc
-----END PGP MESSAGE-----

--b2QCCRtrSG0QxdGhCcjVcLeqe3JJ3kmhJ--
