Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 84EBF1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:10:46 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 6597F40A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:10:46 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090646; bh=WaB5uwZFcFIUa81h4k2xv4Y9yMs5pVD6YHgqENDpWVA=;
	h=From:Subject:To:Date;
	b=rehXD8ZmDoxANWrjJRt8KwCxgVaalkORcLbywTIoPG+GqubaM2FDPmZwTnzah6fOd
	 272HMpm4h+Hlmf/bK7Po1uLdfxERQ1H248+tFrRKThNLllMxosXj+Q9n6gfB8N8b6p
	 7lNZbB1peNdZl2UaJUMtXKre8TMrADGZvcwFntEg=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 5BDCD34E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:10:46 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090646; bh=WaB5uwZFcFIUa81h4k2xv4Y9yMs5pVD6YHgqENDpWVA=;
	h=From:Subject:To:Date;
	b=rehXD8ZmDoxANWrjJRt8KwCxgVaalkORcLbywTIoPG+GqubaM2FDPmZwTnzah6fOd
	 272HMpm4h+Hlmf/bK7Po1uLdfxERQ1H248+tFrRKThNLllMxosXj+Q9n6gfB8N8b6p
	 7lNZbB1peNdZl2UaJUMtXKre8TMrADGZvcwFntEg=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F5E56.5010903@voidland.org>
Date: Wed, 2 Dec 2015 23:10:46 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="oXIM6ecv3lrTiukgPEU6NblQUkbfBfjuG"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--oXIM6ecv3lrTiukgPEU6NblQUkbfBfjuG
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--oXIM6ecv3lrTiukgPEU6NblQUkbfBfjuG
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/RuRfTi52Kkf8NRbKPtTRjne9qaexdoKJ7AG6w43aVthT
FYiJ0AfNGv5SfaBc2lw3d2LxdjVuNbH1JMvdHVNzw+icFloKt2mKRqG/gmQ84fOP
UMSBcx7TYttg0BT708Ww0UlMsd58JDaxCz8yL6iVGoy7DQu9uAnSo8pyv0Z2KuAK
Xkfj+OsOGIc2hrTkvkqIm7X+Y+QyVZxtGKct81KSFt7F4hradNERUOIyw9kW5j6H
cfvz2Hg/duLfXIv9n4SngXkQVIi1SpW/yyd1ISxzII3k63vwIDPt9ya2yIK8C7tz
pFNpob/ygaMFigzEZ3mxRDAvL47Fg12zX8yE8I8K2MJuwpEzy4l+Ub/+Zxru6Eiw
DMp1Wx2WprwmIIeuxKi/Sn7YL5FKl72xJv6JVhcDhYzB3KDqQp6k4ZtuvOy2mh/O
e1BBhW/JaSXDUOxexIvPNtLDZR3asUpCQHTqv/DWu41u4zAfkS/T/urD11aI6Cy4
ejlDb70i675cLbSOpnwiDACKr9kgS7ChKtEWYhqBC+gZCDqNy4AOSpBfkoYu5d7z
pM5NrUXz5c3kuKMcWtQvI1WnMOx0QVReU5GIP0wsk19xQ56Vx/Yk+iEydc+/T6no
/2XH/Pc7+8EZKp59Mih3N2bI7iWl5sgrg6OtTT8WgfNczN/w/5RaRDaMuJ7eevfU
EEMiE9XAYkzupHi8vUmmASHkIOOCmCv2htUopBGA+r1KtK9cPO1n/1HEkKMPvdI8
CYPNbkK0uZ/kVrijrnl6Xh/RbJ+Sh4FxX2vIBbZi20BFLSTiNjSsg59QorL7kMkf
VQhIWojEyQq2P+8HxjzS1EbWBf+dzuXCnOHG3c9/LEBEXlCVK6Y2faOZn8PaQG96
CKzB52havl0Hpp0M4lEC+haqGtjFV7E5KD4qfy+PZNpHMVWdnImG76VmJt26X/6d
ppp5j1pZNVw+16XKcoPAnB05XyBPQP9lPPzfGOueZ3YbO0bgIaNtIvgZbmhuryTo
/UiqAtnbj8AHHi1zbr0aJfiFAgwDKA/jsTGjsHwBEACRKj8IKOkEMj1Je3BBonKP
dgZOohn8y15BnYYnyo6KCNTIuVh4/So4S6H6ZhWkxFjz8pgn9776fVuv2MZG0iMD
fPYLeQa3PJo813fY5kuaenmZLXfK2VVZN/hx+kiQXqVSkT7qHkpSCiItVmmtoCCj
ImE+lsm3qCv9cDTzPRyLNmhXegaBxA3asMp+iBkspGzjSYpRD5LwNetUP8KoxOGP
ntXMoXBrQ5FBAOiBCljXDkWWv84kpWWRlNDg52r0hrSFn12ZRG2ksfcuMGbFtCIi
RKRX7XxJyxGGQ5JKDsQ05CDm59sEZQ0DAEA8yZsOm3EnT/+IfEk1KyXIQ+ZuC5AI
ddVEyn+3psypP7VCFvlZYradnXtwT2yOqceerLDYHKWMm6HejPocuUt8SMcUzstX
1w121N6V/IvLT8v9Co4L4ZauQsaZAwEd1wv45/UZc84synCHN0FHCNAY1H+VODOs
rYu7C3YH9Zggf/ThHLtlGBqdM6lDyf2XUirSnXK4X0Fgl0XYx9EqMUDlcslZ7KAC
nB5kgljco3idrlSSWnkAmE/b2Ax7xMcwHXIwlVVXXfgJzkkoxVVCYENrE2e2lyJM
HNvXH6vXlsnTlQZxdZLsKx9iqddr/ojQXLUcAVslyVXmP78EJRFLM8gri8qOwMzr
8m8bCfedTvQ//dPWFYRrgNLAMQFUOsLvbz+213e8qNVLmfxPCfblyaBU6wtG+BDV
vMjpH/rzY032i9OYyBWpdOJSsPNlfzGR8uWB6FjceQFZ1MQtTXZQEQtl3cYG7h3Q
QNGEXC4T5IUls+j9xszfF+xem7lk95pODsoh6bO4aaoQAMOB8/W9mPTrj9r2qcYa
OM0lBf+sfk245CuFKzi38cAHtj9M0Fjq+Ig7coqzlpuc8RNmQ7gaq1B5erKS7O5P
l2W4J1eR4IUp0nzg5kSOOJK08f3us+5msWUDrISpKqIKGgJ899d+k4byzb8snk3D
pWq4Yh2U9/xTT1sF7zna/9B1FiE=
=WEiq
-----END PGP MESSAGE-----

--oXIM6ecv3lrTiukgPEU6NblQUkbfBfjuG--
