Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 6626514201E5
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:45:11 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 427F840A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:45:11 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092711; bh=boQA5ZWZkrlXaIvTbKkOAo5Ru4zY5SmqhuN9SetjvKk=;
	h=From:Subject:To:Date;
	b=acAVjK11R9uO/7+U68yj/nK+0oXRNKEFoiHV3NxB2g6JlavQtGGVfEmp7rwnCbEEs
	 l7tcMpb7wF12C7AfRl6iVjIbZV1kwyQ4epfH1jTUp/grjke8b9x2nYxpQTdSNF+Z4I
	 tR9gw/E4X/YE/QWdB32Tg7V4PJ97uOlEkQ/lseyM=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 27C0334E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:45:11 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092711; bh=boQA5ZWZkrlXaIvTbKkOAo5Ru4zY5SmqhuN9SetjvKk=;
	h=From:Subject:To:Date;
	b=acAVjK11R9uO/7+U68yj/nK+0oXRNKEFoiHV3NxB2g6JlavQtGGVfEmp7rwnCbEEs
	 l7tcMpb7wF12C7AfRl6iVjIbZV1kwyQ4epfH1jTUp/grjke8b9x2nYxpQTdSNF+Z4I
	 tR9gw/E4X/YE/QWdB32Tg7V4PJ97uOlEkQ/lseyM=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F6666.9000503@voidland.org>
Date: Wed, 2 Dec 2015 23:45:10 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="8Gwkq7e4p7bM8rrxV0VkgDQ03PLRJVt04"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--8Gwkq7e4p7bM8rrxV0VkgDQ03PLRJVt04
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--8Gwkq7e4p7bM8rrxV0VkgDQ03PLRJVt04
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/QvWmp2ykWC98OgsfyBFp6U8wUSY1i/368SVLkjPnTq7f
Xrq9YO8OzLldA55xQld4BRc294tEQvah3FDVepYMCVYqgkPVCI4IZbYNQ+ZNxL8F
zX7v+rfArmNe+FKwBWj0SHQDyOQAq2rLlH1Xer4LerOerQr203y5dU2vN+6KsSni
GlHTmAB838YTv7IKLucN9AzStOjSs8TMC0nSHdMjLOsL/hCQdM+j2E0o855yYbwJ
Tem+Za+2QpQXPxYR2zUek3JfwNHHTg4NmXmXnYEO6IcNNn+rlMQJEO6mwoerbCcg
WE1vQpC9N7QJegG3DY7j9Rj9x31GDz5fwMyJVYc+bh+Q0lGFklr7lbYwf3eLwWuI
Uz7WMWI14khc9pNt8SdopSVt4WuN8lzgl7LkB7H0z7VMAS9Hcu4BgQdcN4aCoEPC
GxiOTEmyQ2kJmM1M+J1KEMuqzvGqp4Hf0dTxKXYa4vbz4RasnTdLLRNY4kVvpxaN
hPW7NrnmRX83GI8YNqIHC/49kphZzX8xmRVag4pKpGjB1a4jTq6Ie5ZPpi0bi5V4
a3B7dxOtaMOX7PNBSf2AymPkqDDnX+5Swcj0A8p2gJgWrSKJmeeGSRB48MACkRNx
95gblBSXXPgOdxYdbnsPe6WV74+Cag+qtCmvIgeEO+W2y3MerxRmRESuNQ82SZF4
h37f7XE0iEJImsU6FBFVetyVB4MFpopwYV9H7EVlPtxEDoNUt/OApODgSh+fZ6D/
1ROmV9TWlaBleLSttHXKb1fzAYsZrG2dNJ7BB0iz52Z4s4jrxULrPqyFFEkuKkMb
Tz4Xwi033Gz9RbaZ9IUcKydhNiOP1KwgGiwcqXinfA8CLHnGmCaHJbYxSgW2/h5E
xZyHcv9ssXh+pogGNTrsp3ZyUbr3oMtejXLeRLJsjtJBcuyS8vrWq+Jy/Qdq9gDB
5XKozlRl1/htPzjroe3sLQHzNaZJM3AJwIhnAmneijgkUrMI4sRGDgRiih42/jYE
S+IsOtWyyBr4imOJTxjpiqGFAgwDhSqg2e39KKABD/9xchImCJimBGHsnGem2BzG
YKj42HTKF6v/gOgKn5YqLf7OckEboLk0ugAoRq/s0QgRsLBQPRPaXdMlcbsBHEgw
gvz3JByj+/jwSgEeY3Oem+yOnUJGC9Co6vmgK2hOvArHlDK/qmNPl6vL0UoYavwC
EpTBg2cWvr38zMULwZUqs8J7PpZdV1zE5Fq4jIEARl35Xq2DC8DHyYeGX2iEXp2n
n0TbfibUfPl4/ia+YgnEeqwZ2OBW0LfVH53s0nmgN889AQnIn44i+OPkNrnaUcC0
x8JRL6i3dZlkFpSru6x4npLPqjBgq+iNDQ71GglxPGdPoEqgKHsNyt6CBtEGySVF
FyM59JqswCXuGg1wIVvxM6g4vAo+7BLuUoBh4S4R1IFKL0+BSV0KgBf/Qca2xQ6u
9pCS5k6JGicAfVozJrBJ0YPXXUxbND1PkXct58KVKoflAioc1g3f32Yo60aa2OlK
aae0NhJI40Bwr/WMeanLVIywW2CMLpqNiP7iGxw+ZpxRnTVmUOGFjxJYGwuN/wcr
WiXMblrayxcRmHbza36OuZ9Q5dsmMFGJ2WQJ7nDVc4AJIh+QBVbUgIpb6Dq/KuPI
qQOO59RKcAJvK6aUG216amT47yLtstQl6ZT2gMCg4ohsKPCA1r1TxbmPu+GJeigU
6hT1ig2Z6ePN33nP0WukrtLpAel+kemKXU/PKyffwGjwgDwDnRjoAU92A/2V6EZe
qtlEDxx3berijVUu3+CA+jn67Ss8dATrpoZAn/g+GaJeNrnSBAS+22K4RlvyzuXD
IC+P33p5ISIIbS2Yo5ECJ1V5ik5rwQIzt/XJlD+5gNY0Bohi9LuHN/KBMgW95bgN
wvvWeA2S4WXzXo3WIXKC2ZkvROX7F8EO5JalEPva0qg0Fs+vqJs+zO9439YLoodA
fk1QRn43BhYDAUjKmEzqZ3LXgXfLweYAssieWeTutTDhgRSx2gQFjLNWZvQI9qOo
TvdoxzNgxFmiOKAr8s44ZzzC/rRs3IQA1vEC0XBDBlyEvjjPKgCJjJOA6N+cU28e
0158+c2OaDJJLpaGS7+BpSi09WXSfTQu5eFjoqQuHou1mW+RtJbitT5TstDX7dj4
e9IB2X/o+cHI+t60YodRmUQPNjlTYeMPeL30YirCOjNcHMgOh3wfgz+0bU3zD/Ft
CEor+rstYW5PezZunvnbe1Rqpsh1Vvqq+gH4WuA0Yj5PCVb9xgkd/HqPSPoVPCv/
au2taC8P9WoxLL8Y1K9ERJr3Fw7lhD54fSuVaU+xAOB0wTPHaJzt5ICE5vcyi8vc
b1jADUMGatDmEwr+I8AnBWFPpoxEuYjdF4rBfgz8NUyhZNhYMRpzxK5dbBIbHy5M
ZvjAeD9Eu3JmVdX22PomKRQTyxYxCLp4FtFkgNUAiYvX4ncK1XWOYaIrOOmh+I58
HGWxF07teYZdIY6aVb7o1BRYNjZ68lNZ25rftD4onoe5uOJ+o8ziX2PI37nmKWG/
3JIdONekcfQhh/icdwL6eH/LI1zOFWaKdkmtKr1zzyC35oYxuoWEfP2ED+QHYPfn
N5VoNg5LdLkhPH6UWI/JehQOtZTvO5WLTmmBDWs0Tgat3tZ634LSSyMuAUO3akHV
1cdPeuqpzOiAPnFl2BBKI4Oew2FpgT5gEJEi8/NFaOQnNvTUzwGZD6zv5oFsZKe1
nCbmXIH3ZBF01mAamR1TGN1rNQCSYZSWELLuWl2NV23YQ/5i0cjwDRll7eccnCQc
L3eccI7wbXuUMmw7S4Mm2pSLTnXBYNXSt1lHgg==
=OlhI
-----END PGP MESSAGE-----

--8Gwkq7e4p7bM8rrxV0VkgDQ03PLRJVt04--
