Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id F2E9A1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:46:59 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id D044E40A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:46:59 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092819; bh=xwnynw56/vzuSgFpfUiGHYbFoKWT3EkWlfC81Ayepv4=;
	h=From:Subject:To:Date;
	b=XRl4uIqBBBQ86+x3kmLxuPhpVM+rZ7763dMCUB/bzPEP2DLuffmL5C9lure/ZGSV9
	 vpQQ6aSsgNawkk79G4Qn8CSydiVIOxM4d3BgFJA5Ydwwl6idTVX/GoLD2kTyL67QFS
	 GEdz/VH3ihfwlDhoBkpOdOIGjPPOROOP3XvUFqnQ=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id B9E5B34E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:46:59 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092819; bh=xwnynw56/vzuSgFpfUiGHYbFoKWT3EkWlfC81Ayepv4=;
	h=From:Subject:To:Date;
	b=XRl4uIqBBBQ86+x3kmLxuPhpVM+rZ7763dMCUB/bzPEP2DLuffmL5C9lure/ZGSV9
	 vpQQ6aSsgNawkk79G4Qn8CSydiVIOxM4d3BgFJA5Ydwwl6idTVX/GoLD2kTyL67QFS
	 GEdz/VH3ihfwlDhoBkpOdOIGjPPOROOP3XvUFqnQ=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F66D3.4020901@voidland.org>
Date: Wed, 2 Dec 2015 23:46:59 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="LN8LhvjOmodQTotAEVXAerjuHKJMfOSNN"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--LN8LhvjOmodQTotAEVXAerjuHKJMfOSNN
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--LN8LhvjOmodQTotAEVXAerjuHKJMfOSNN
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAwAg4kt0/KSDoNgH4dNF96Y1i4jfNnjr2KPfSxkXS2dQAXd
eMxZnHi2MSYnb9b4DZpGQr1Er5fr4xPfJp3bzdFk1E7IBOPVvxLfAk5F1JzRgee4
6qbsogof1vqYg7jux5ZBcwHGx6f6EmaRfX6C9cIHRRkVbfC+U7ryDUGdjPTvm9yc
aapdk4NPs2ziKTQXsduOPxmGP7kdE/zkje9Hd4cVhlALTDdRpGIKToe+TkTLGlXs
wN6IgZpqnJeHR2gxjp4VfIDWf/qM6Ohv5dHQsyfSt+fX63B3F3Vv006UCYBugD24
hjJ4tldl/gZnVHRtkvh5NNFthKccDQuD3/eq24J4JLIobtTAjOyztarwrroJqupg
Pps9zMCqMDMjzkuDe7HDpPBtbP5eR+E/O5QXERmHW/UDUEskAV2iGqb1gdfnPtp5
+rgNZPLLvtfC3Ynly3ApxiBkRsW4rxycNVnzG+nYt0bcYd/kWJM7vo1g5ohkUNl/
jmFilSBWmsVhb7F5XpDZC/9o0DdIcNk6pcyphC3QOIxGZrIHIVQIy4KuU5O+zZm0
qfdi035S4EHecRF+nqBnkRfxw3fGwGK7UrAw6W86HsbxEORTrJPQDsH4ChD1B13Z
WCy5JKeCMUT0+5fO8IJMr5yZkY6X2YKkeBKG3a1lccz4w8CTwSDsTRRwD94rePYE
ZcafbIqTdHsLstsOAJm59e13Xk1+BDo8ffiraufSwPvNakA0tJnpA48RGhZYUnYf
VdZLnQVXjx2ZLKlSaqD6j3U1QJ4ZUMAv+FhcmHqlRW0EvM8ri7a4Hld4h7cRBf/3
f1x/TSQusWW3E/Pp/Bnvb5CbobdNfX+3yXnY0f2A/OsHpW0v+UbnzuVokhQ+qeSX
2kdVZqburdFliJ6QGs9bJgTGAk5gLJ+jb1gkKfmLoDEW/Fg+ubdkhOCXrz4xSgQ2
4Dc3oO55oWsXwEYezeiX9z7xWCCwSkRrnhxJC0si+C3B5TIXKF+UfETtddq3aYnY
HTiXXH9aJMfSpLnP5NkNp0eFAgwDhSqg2e39KKABEACrKQXOP9AUGu8uvir3ImZ/
1gfacCDQmpzdyyk88u8TKqk56UUmonBlnx/hrG1vAm7UlnjvgejoQDCeMAuRkfMx
JbR4MDmDiwhBALkK0WAwxtNy03yT8eNr+vhigeGLa2xtJKd4pqeswtlmHSMuC7Q4
28Kko9l0uqccVIQO5WD/f1AWSt7BwU7PgZtEfrwzLhW6VLWgpZsFNpFqR1vUPnDq
oMySzvFeQA10FvsK9vVJ43qvRUE5nNSurjS4idTY5hCI93k+ZXZdeIEh36RcUf4i
3Glq+boIILydNgvaNqHNzOEBC6DzwZF+43+ITdvWqHvz0EC67GZYpaMCAH3WAQjg
MVD6ao0KhhqgAPftO0ZKcjIoA/+G7koHxLCXzQDYykOccQqGLNeNWVWvAhA7gmGQ
Z3RTdh+dFnKvEvmLC+/Q+NmOHmIhUSdxNlxR84ezT420aSGpBH5iVJEfnx+bemAS
p4Irx8C6dsUiTmc43iv8fwOQEpoFRd01kfpUkkgDzHKnpSPTPAW7Cs43ruhoaG9e
mpakX+5uckpHzIJBFVll4Hg0nOOg2Bco+9/ZTQXL6XzheQcEZIT3et2l0gcJfpJp
LK6+Ef1tAE2ae/jfKpIslX6vOJEJya6YrMqQq5TREdjIyIuDqSxyv5WxFX72EQgP
Wvcv2a9rxSGm5ngCScAphNLpATUXLe+qX9kR+MUO+gKJjFaYecWb2Lh5/davPfby
aFEPjR70KVKjCBeSUu/VemBTJ4ZfRD/w/+zhwSE3OBqhprZ4dbEBCNVMbjO8ZpBi
8fB64WyYM77d1gNiMRyaI2Txl5BLcmPp7Wonor6/sJL64GfmX++TEgFnZ3P0TqIY
IE8jzWVaqbkhIVm3qEZO0tsfpCsDk7A+0BZAaf0YvYQkQm63bFNhwv8N0crRm32U
2fZfE6WHwrZRW7d9SXXGFb4sqk+vztJICIQDiI4W7vN5o/qtPqR3VZpmEn04HHpF
5b35x2M0Sj0v4eWQr8eZCdoqO5W32CNJ6DDGa8t0Px0P6ci7FAVkDQkhWFhUMXKQ
YzZRebOo8a7uXeXa5nw3ZW9oERv5Pjl5l0UXMAYRKErwqkfxGj8CEyFobxhPnyg3
Sr63J0D3lvuLfFLoUDUKOYr7B8UKKlbbWmjk6dxANPeh8wFINEAFocQHRHYY9yDM
GUMYkV1yuZjINdbFZo+9EKk9M4ehl5isev/4m1lnm2D1lsph2jO/kvUWdtMNfa/T
xTDQ3K30bzbsHcjdxz4QQsufpvg8Iw0zMvKS4DjbOK6IXUr00wjNxR1HW9408n6c
ofMiUiQOtO3b7Ui0uCA1gYa9tV0D1AFDRSaPL90xWAi9VIg1Tn9HjLeyaRqfUoK1
A77A6T4vUJAXDDYZl3NHecsKT+WdqK3waI1/9YJlxISgQUf8wDnbyjgbAOL/G2qq
QR+AsDtzxaFEZ8zg8fvFb136JOm9XdgEghPJh2sSANGuji3+cMRn+2T12PBZal2+
d2GeRZJ8MtViwxGG3xWpV4dgr52yLBfdAOGojUizgy6Iheu9OxH6l8kiX5KW/5Ns
lUhYOcln+rADCQ02gIViqirxrXCPgX0JAFa4dTetbwcC8ZAM0xWVV9y1ZcQmNm0K
wgAVJZ85cuy4X/dutiv0EdLeWWXFsdGOyCKuR6RZZr8N1/llSl8RRH13IaeMyZn8
tMSLQCCOVNchB+iwov+bjyfGfi//vZeqUWUDdw+aAyHKeKv8uxK1SJLKP4J7zc1f
eCkqrG/TTwks8dTQfia1yLP7oDi51rURdytUjaCIVGaOJWQXFPn2VUCQTbNBkkau
b0Pz7JFJlPMSVIiviLuodFYLlkVY6cR5FOGSm5Bf8NRaXK8Fa7qvvImazbhulAtT
8acgfR04960Z8aUlsypuEyOUHIevNkX3nqL3jkI663Pc6n9sKAXJxqDD2yHq
=7y/E
-----END PGP MESSAGE-----

--LN8LhvjOmodQTotAEVXAerjuHKJMfOSNN--
