Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id D664E142017E
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:22:29 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id BC636409F8
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:22:29 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id C760E34E00A5
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:22:29 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622AE05.6080705@voidland.org>
Date: Sat, 17 Oct 2015 23:22:29 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="DGPemggkViRXec023v0ovRv8083rK6xM4"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--DGPemggkViRXec023v0ovRv8083rK6xM4
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--DGPemggkViRXec023v0ovRv8083rK6xM4
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAwAg5174fsyFuwoWFPbbqv6mvlFiL2mXurQFrHxC4XPxFZo
6aNXNFVXeRlc99W1DA7sg5jcDZhXC3UOC/czXkVs0pYuaAMccFultLOrBAbx/FWG
fSMJgSRvzWcX+cpB8bXIkfC1amfC527DCPKZvxMCgnOkAKfRGC9MJX5Ziyv67/AR
QEf2m5rcEjqGvTI+sQ2hGiu4y/LxmWI9cbOYFWwf5TABi6l6ZZmfu/lzdQ65SmFi
RQodZCFPL0L/617T6TfEnnAryRaM1zebDVtcNYOkqaHlQpqi5bOuvLog2arSXQzw
Wts7N/rDF00rloGvTQN8gnAvErpVPRVqxeYeysiA/paIiFbTKWAHMSb8tMoFP2IY
N8eWVXH0LdoLajLBbxnJvTa9F+9PBbmNoKfPlsUhuRdO6RM9zpCHaFiQXSuviXkN
zX2s6TPrTmRKA3KkAtmQAUZq+zTQxygINyee8Ez77MkGWE5m/b+fWgc7ybq7G7BW
eUIUeL3D9Ib10vccULW5C/9DxMzC8/ZK6jg6dCxvbcyo28Or94C5jwJGoftXG0ZF
CrGH3j9WZsBkM8HQ/Uv1wR3mncGemiiiuFsu7XfXu7GF1JrUN9xGcOoYIqFXdeJW
P9FrawFj6YIUmk7qx/QLIRFafT63FZIFrcFh+2EF9HEO1jDbcZVxN24DW99eNbYi
axco5yXCXdmU918D/Wwx/7O+dyZ/SSZ6PbrrUIm7KRHoT0ZiNARb0J4/AHf76h6C
mzH05P5BAhJ6hE8oZLK+bG78bKbIdoCymIh9vFcRLC9H7sEDtcH4/U9QOcWfK+Zz
HDgQhlQ9/bhTmWmlPiZrYm2jP0lBjsTEHhylJT7XrqE14LtzEj/ZUWOwA8B0kKFi
KMum1zIrYzWmUPqOOya1owTUeTC05PHcmdzHg6ZUt5SsD1YO61D//mdWeGPiRTkx
8ZckaxgKnZbHOwSxFHwO6p+7mD0BAJL1bJE0e3Oe+0P53zHhZbauVpS3gsPNWFIV
5QG6mEuyEvfGsQ4cqBg+8VOFAgwDKA/jsTGjsHwBD/9kSb1sKE96vM8nqTMf4uAI
jXeHIrvcPGeWRVHicw1kZrzQ/Nnw26tqdab1k4gPDyOvGeQhx1bcUaUinGK2daBs
0j7ljFmkyY/4SCJn/o69Nsg5YRZ4OUQrphkCJrjdUqn6ycmTHTJHutF3soDP7tYi
BmRNYRwg+ipFQolNRW1CbB5j+tm323JLvmVjjd5iVjGMgxN8Ve0YE9iGcETTNeAb
SMr1bEQQIzAVb9gPaNWhawevWXaYrQAJt9T0n5GCdC2d+gtZpLzm8EfWrnbbKN6r
WRLAzVvRdOUnUWx1n97HhjKNluoXLxKBh92GnwV1FF0aeKItzLc1Cd0o6DcNYNsT
V0KrZo4RvfDR03XcjMDSS4lKDwf3S1N3O4nyRoDwxZr65qkWsORreKpHAJmZlKD/
ULPLdocrLzrjuFZbAA0djP/iiFoN5Fs0agQ9b4jC2z1AHyO5uDuZwCerphqB3XgE
oGGXFH0kgDT4NpRlhlDBnJZHdEt5dglz/EhxdQPK9BHmT/0uzBg6hmUvGRdrNCsk
PvogZSQUBv+yAmKnxvXGKuf/9sxZExlbDp5h1bz+9+bfmcxoK7YHyoegMXkRl08e
8BUrwIzsPmJxxDmiTpem4M4rsLhVtgNuvQQ/eXadiRmI8+fO8oboeSRpakyG56/F
TjIxIWNjDoz/T/fFOh1X8NLpAf7aRHT2/lzL0LAKIXCANmk05sb+JvaM9hN0SLGU
U1ZU6bmeWWdf+WJDkb8uURQuyilUUioMeLQCuoe2qcEZEKVA6AVFsrAKWMJiuPOO
1IxlWlCZ+CbaiAr23VXA66Gau3XvfMRxqN92HgswGxY8Mdzzafen8xrTK+nnHzU8
Llg19cQKl4SxBiTEIP6b1YAQ0ma6HfhJpiA7ypNFIC7vToedHPacllc8shzXufyl
ksJBkXV62ooR3ND/DIxJHcAGZKntTue1HKYd4HCxWbtwtWlCqXSznOncM6Gmwg9b
YrecmoSxOhsfyyNSUATzJSaH0rGgsutJG75tb4kV37oEL8JR6em6CzTvPNaXfxUk
C0MioE3sRC+SChTiBzITyXdpuUOix9giG4NUecwp+Dw+YdLOTe7sHt4mjooI3gy0
44EL/pbjBfuFeRpU5azmjkeqphDrucFf1A0OnW6Lgj40kNRanm8YjdLJvuLiMLOL
eRxc8VLO6zAKzzmPjPV9fEJWrp8rwtDQdISlNxzyxihT+vJe61YeO615UKAYvMZD
NUUY6ZLNERWA8arYsHVpDl8ipdM77l6WcWiXI2e1aKM0fJ1ZvUMeCZBPYwcK1yqf
DL0k7nvVtd+0iOcoz/GwjL/pLEDyZg5SAtPTkRijw1RpFKfq5o/VbtuXYzm+qWQ0
beDAiLRZqry3YZM+fikBCtysmBOoGukOw7aVmHagY+JlcRZWmYsQkBag4poYJwlg
fvsTMc3e+Tvf6vwPGI5cHO2nFRpmRWL16WA1jKodzcXxl3PJIGsArZPFBbpf8e6W
m8wbXNc9vmLwh6AzWA85kDP+Fb1GVpg828EaR57i8u4rYeVAlENFJ/ElJ8wGoedo
ixwf0P3RWtiZO64ddWdoETb7n+h2T/QA37unN6Bhwx47WMTXxeN1Je5HDeX15sLY
L7hPCqco1c0u2i2hllHxDZdtBieRBIX2f1gOzm3RfsiDbVFQv96S8MZyhy3eIyvO
0KAxpsdMACP3hqUIizdKixj0g1D0AqD1vLTq5fsvad5ehz0PdagExqd45KvFSWTn
Eg3QsUjThEU9e/srvyJlsLVEx6y7r+yO5E2Gc8ZytejzrLL18x0k/l42HNo=
=AL4P
-----END PGP MESSAGE-----

--DGPemggkViRXec023v0ovRv8083rK6xM4--
