Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id DFEB31420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:12:51 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 9AA7740A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:12:51 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090771; bh=TGgh6lDbyjre9pmNGEf+Mbq/KCh8e+bVK63dRRHKbDw=;
	h=From:Subject:To:Date;
	b=BzFZdB01nKUPbY4Wk2c+Wc0bjR5sdUt6vyZ8svuZVINSZ74J3nEc4LyEiJd387bVZ
	 tVwdIvh3cuH/G+pD51n3rUC+IVG/IJhDJ0Y2B9JDZY5tBqU/hwygRq+nL/IKslg3Y5
	 RcMTJw0JLtpti1NjDNzrNvtbAASnypFobNp9ynP0=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 90BAD34E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:12:51 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090771; bh=TGgh6lDbyjre9pmNGEf+Mbq/KCh8e+bVK63dRRHKbDw=;
	h=From:Subject:To:Date;
	b=BzFZdB01nKUPbY4Wk2c+Wc0bjR5sdUt6vyZ8svuZVINSZ74J3nEc4LyEiJd387bVZ
	 tVwdIvh3cuH/G+pD51n3rUC+IVG/IJhDJ0Y2B9JDZY5tBqU/hwygRq+nL/IKslg3Y5
	 RcMTJw0JLtpti1NjDNzrNvtbAASnypFobNp9ynP0=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F5ED3.8060709@voidland.org>
Date: Wed, 2 Dec 2015 23:12:51 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="w2vad4eLqQNPaTikglJGTiCVffEoW5FdG"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--w2vad4eLqQNPaTikglJGTiCVffEoW5FdG
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--w2vad4eLqQNPaTikglJGTiCVffEoW5FdG
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv+Kt5oAhkPbw9BouQYgx+2uvi1ElpQYXXmAvby98anP/Oy
KpggD0K4Vq6pWE+qTJowOxrT8Pl6D+f7XN31/p7vWm5OOaY5v+CS4i6jKKScIFLl
RFkj8XqAkAglNH+kJLptqjIhthwClzlHi/0GRp+9xtOs99eOUcJu7rlXlvTrQ+2A
SVhgjNZRkbuBkXsAs/xjGQ1KVENbjVjc+y4apBxOdPClv0aC5QlMuWGSYgSHhDdK
AqCdM3dTraoN5jLlOq+UR1uPBzIV1iMKMD2iNLyVNyUSwQShdJ4QDH/miHTbB3k1
hvXRey356XkcGVMs+jsy9ijOzCto1/41h7ar2+m5YZ3Jir+lXmfMPZAkKDgn3yuj
vr/5C+x/bbU3wbhEH1jlkACPSUNWInLKJG4xSqZthJ1/zNpgQKLvdiQ6kipZWib6
JeVD18DgXv35l9xGB9Gi6k16N+2ReNoT7zpQ/MhEizr//AqbphjRSCL1f0nYehRe
93zrZlIc+aI3h3q7CLKAC/48xiIsOJj0fDygBcwFToBdTXTsmETOlON5EfjUWQ3K
ALKt4IeJ2o7i6u0VZzC9uj4oO0MF+3uNJJUpiEU82IlF605gW2LaA8VIvKiAExQn
A1Xox5DZwo3YrOFCz6UvOHtu1MdxFSuR9KOuXU6uGd1ToWZ1ntUM1wzqmy7mNqnt
2kOEa+HFfZQ+CJq6z8B6nW2t4wQrX0WZep7DhJIzDWBfVgsJm4OZxG2El7a/k3zX
lLc0Oem8ot61rPp6CsnZV3z6qLwSSfNdMQ4GcGEvwTvZw0BgLPIWFnXRQmyG84N5
BpHmvjtF5tnRLEQln52tmxbf73NlihLFCeX3LSo2Pdnphpp+VqvaATpNd7aGhGAI
bCtgeSpeodkl1coiTRNUgzf4sfUPxgNGEa1mPH2F3iN2Vr5Q8d+ZScf1iQXLC4dW
cqbPZTEr8Ht5JvkSb7K2yMN8krn0nHjpTSl6Ye5EW5aNVV6/MBzU3tN+y0Rm+cVE
PX8gXpk4DU6OXPU4t3Ylz+qFAgwDKA/jsTGjsHwBD/9fPV5j+m6Iuyqpd5KMniSZ
yXc5p3/JtOBHRog5LzxQ1kmQZgunX/7WEBN05+RLQ4LmbIzc0vnufndrqa3qt07Y
nX5Ky6Oo48g6kSMb9620uyyAcTbr73AKCdYtXzPQy3af5ficMKg2T0DxacMj8LtS
KODzEr3P1PTVkPh+bZCD7zK+15YU5rNfcIw5qA0KW4QhrCRCexSufSzVoSMX7pos
fD2WhrTPoqq6pwBM761YhOBcZcPnZtmdldqP4CQO/OTU9ygKcN2WehGikOGazRe5
YwsRQEqu3yRJetbrEgSk7dYpoKKx7yd7VicIMR1oGHYrtFPvQdZ6lRWv7bOCc3/M
8UZioI+IgHmxWF28s9d/KFhi75q7KFPCpbjCrbcOwabP2Jnb3z10F6h/1Zkg1o9e
zh5Zik9df4T9UvYBfzvzzvvwyXFKoOq85lRvFNC6IDP+Ge1BXInbHpRK3pTEOb72
TvNXFFXH9QuPss8zd4+kQw3zGtWeXtKaESrgsdwFW/OkeJjGBhogyUInAGtK/Xb5
6fRgBL8cvv201KkoxuukOzDx84wMs35nnTfXoh9QqjCd2FOGXwWZTzc5OAGuizEt
VGlEisutnjm+CIQ0uWsfAq5Pd+y0LHcT0M+MYQMiBkPYwRUqdPz4wpskYgEOjzkH
l4ZGiAZ1oQAQFnNDmXdp/dLqASvkx9EFsWJTq/nGwITo/2Txcz9q8b1RpepLkfAM
oPhzD6HxjH5n5hJ6oZYsiYNTzNWYjNi7upH+J0QKr8pwVN6JVgl8PGULLtndZQ1i
ZLAXtrm+e/uALXCtpePkKcvxQ8HrGLac0ISYEvgy0P3G3lOFtUwo+z5vhDq55o10
4a+8G+B10y/SNBVmEPRf+77Ay5IUTwxsnTwlgC4e7MlehFMV7tdS5ekV4NBwNT+d
o8Rb54NXuekCp/pe26ai1d5DPneDWDzH5nlzZsGA7nXuqw5Bp0LAbo4sT+nP5ww3
QnWl8UFHjO7ovCqJLqL1OiRy/XwGwKH4XkoCKMW9mjKd9tmGgOc14tTLHhFFTep1
rvstXylPQYizgNOgfEiY5dJLEtK3cBmE5viKFUAiOHvsCwXdacN8OI2bVgZ/ZJ3J
hSjO1CIFldQo7vACbSCz7Fum9iRcI2jN71FsoAaly9jqCbiBQw0+kPdmstQqqYjE
z1hXNzvhaeGs1v2nmgwjkl6Fhqm7sOHcESbp+xAj+8xHbJ/sWdAdVn6PXxxKaCAY
T65UiNdkCuQ/xBLMSVlcfE/iWT2OkUSySzdndsO6uWBWi4skwbhJBhKxdxP/zyj2
9pkzllADMPCVxJ4R7zRiBE7v8Cq8ioxm9egfZf9vFqNs9PGbytnGjwWh++Zs3+yk
QX16OZGxGyQCTsbfBdHFhWckgg58RYVg94VWxklIxdQngLO0wsihwqt/pASlkxfw
bGun3Fwepdv5dXrtDDLr8CdcyRIBWdQ3ppAO/RR+GvlpYNcGxOrb79PgmQSMGkgN
7W+Ak1ABzKHaYQ+JrHaRbKGLyC3fUCxNYqCwHdEEpFSLO3/dI0QT5NNE1xR02Eo5
WB7yegSx5/U7YtEuxiYcX7gUNW9sWZrtSnV9F2+9oL3+DCtwYxAAFG0UJNn9FhEr
o0WH3GPKn3hEWujocCFlyzPUZahpcfeNjcWb11In4hF4/EWdcPnFAsWWbXLASaH6
UobzAfxWZA3FmaeGkltOd1P3XiIIf1rrrHKUr+BVKWGDwnNjXtxODwdMLhiwClKt
+/l/HE39cnVY3JJu5HeYAZIvEbNcY0YPBkkHx1HpEV+na0twyN7qLSqAA6okqUQB
tZLELMDLxaoyBb22mMln6wgvc6gfj/KemJilL7oQJaPAJqqP8OeCXPk/nb2XYpMh
4f8hyb4uraFcMvvXFtWQYDN8Bl/w2JsKCHe7X19E3fFnEbfMMQfk20+qR0Vlu2Wk
RAxbZaNFe3jTauR3OOq+LX+4v+7VE6HztMFWiVmC1iZHBtYiWsInjlMazCe0AxUF
zok3EunVksdO8N9P94bD7iroQuyP6i86mnhCxqf0kFMZVQMO5zM=
=ruLY
-----END PGP MESSAGE-----

--w2vad4eLqQNPaTikglJGTiCVffEoW5FdG--
