Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id BD1AE142017E
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:22:01 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id A0C66409F8
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:22:01 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id AEF7934E00A5
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:22:01 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622ADE9.8000505@voidland.org>
Date: Sat, 17 Oct 2015 23:22:01 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="4PRVRJMwvPVXsQXGqjNCq9K0Ea0fL3Lrx"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--4PRVRJMwvPVXsQXGqjNCq9K0Ea0fL3Lrx
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--4PRVRJMwvPVXsQXGqjNCq9K0Ea0fL3Lrx
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/YWJ6Kc8TIMBxVSGZlPVu+rBFv8jz1d0HRkn2SEqk3wcS
WXa24M3yIBYulkJvTcbH1rmLVqmqftvdqlMKl5SGRh/DOU/6XzHUOutuB6UzFVJN
+YbPtffPxijwdBM71VqueDE0INW6haF52JkwN6EZjmcBJgaBs72fWN7x+xpe3JsU
WCZMmOu5SE1MI1kby4oRs6Kc2uPaRTXKyXY9BidLMMjvvy74xyzS2k0onX2jF8yc
fjfIA4hPDqVPtq0pxyHfKKkJPdX+Qx9vsu6fgixV+WdNQPB+QkCYFYvSMi1duUYs
7g2WOoIOBzIilyOdlocx5M/HbiltJ+HXZ8KNq84XTgBoeR4L6+u39VRjvI2W2vUZ
TwS+q67iwf9E874Jncq0V19aap44hF3MuirwXW3xoEuRB09YkPzmDo/n5nk7dZmB
HINY5deSLZk1fI5TomAZkj8MpdoXVxmU6QKiuLc4lS2CPy9qPySBVL/tXh5K7eX8
ElE4spCznkU9bQD7BNphDACFh3KoVtE6JHMF7GcgC0aHwpKHMjHN/3vCABZmquxb
1lG4ubA0K6LzbsC7QkLbJHHvAJWRJdo6h+XCEveF0MShXn80YsfxoGQWZwS6gTiA
7WLr7VW/iQNrE5U4ezG3mTwUOkbBR+e682tduVXhlm69RLluSH/L0U2JofVnzxlr
aglSW+cqcV3xKv0Ub5jpvO9bl6bI8hmQO0aw893JOaQotjEUAWDJvq8G/5GXankP
1FeWjNDPOGw6+zxbUti14yRJPlKgKrnHCLOmfcziL8cz7zc3LXCfqKziLea1ZY/b
0Z15bh3LidNIQgEJ4jJU3pLYEbdVkYnIu7hsEAsOGkdc1kYtZSKOt2DUDZelwnIO
yloNYVKmUnZ4814w/n3u8LD+RMX7cKj0WYb1sKYpxdc+v+bdZcTxMccE2gPv4isS
lRYkhjIXeoZtkf0Fe93SW6QNEffhtsJEEiXDtFtrpOitlD1So4XmTCHG42Ts6V1E
NZxZO1740+bxz+uFWAxLDk2FAgwDKA/jsTGjsHwBD/wJPeHUs3f+/brX6wcuNpRm
1OEid1M9QsoX3gWi63sfFxN1+l6rex9miO5G+XCTfWe6pRndmmk+fQG/sVkoMTwu
xEHNozOaIFgOq4Ml7KPeUZhaWGpYfQhw7gdtAmGAskbRSQXpjrDoaj85h6x+/7mp
MceaJCyBGz5ZhOC/4hp2J3z3dX/U1xG1+x+PXXWSukDcms1ssDsEe06Z7+IU4WyY
dfGZcC/hSWgJaidu9TBCqN29fJI2dRYmXRkxXqtroeBMqVgPWcRDFWSylXQHDJO6
A3PP3JrXeOgRcrbhLrlymhDOH2D/PErdzv2rMYE/Fri68gqeeqOJv1bFu+C9KWww
tkeYVibVTaP1B0oVoFnf8q6UjaMvQ6Az1tlQCx7xynEB5qO0MPFx4MWP498X/q5H
Tttb8IT6Fkv4B5sgML+LGvsWSNRNpePFO1VgYSJbSmZDPWoj4RFU+mdJ4MxHt2mk
6NU2zD+J+94Ik7/bCVpE/4NRP2ko9UyQytNJP72ZOr16oe6T/NX4uUqJssO9peAy
1l/Cdyuder3u7stgSMXALbPqv8TnShKKWOCSD7GreOaQBFfQ/HDTv46V9HMm/lZL
jWYllWhzoXHo0RtX48wmJHi0e1BejCkLrYXcwJk/yC1ZvZhcDH/EENZ63mnVAHRw
lOURA13mBaIibp72T6UnWtLAOwGywGSVCm6u+34BMuITQrotIcaMedwYaBc6Wn95
d2I7Io66gO8DAYiB5i03nauc+5/vjXhZVR2a8nOl3rDhmC1MdGULUv1iYP/IdlJI
gN/Bb00W5xFMYPL1EUlTMnpyN/YEgx1Ia1IHLaF4cVN19df2LXm+S7ui0SP+Do5g
K2I1S86h0FR33cj75tLkm8/ZnHHDbt4wPAp6Yvn3RYtrWufjE3q1LxDGcWyX7KNU
3sENssiXLBtYKlfACTxtL9sO3cRX1iJ4Qzk+5MgLJ+DUf9sDkrlFeiPKMrWYqqsi
ysC2YghChI43AmCgSX4HkGrfDzVwWW4MDNRY+6Sk
=Zu33
-----END PGP MESSAGE-----

--4PRVRJMwvPVXsQXGqjNCq9K0Ea0fL3Lrx--
