Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id E833E142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:53:59 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id C8D9A409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:53:59 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id BCFF434E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:53:59 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C377.8070108@voidland.org>
Date: Sun, 18 Oct 2015 00:53:59 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="HgjATOd0vJ7JTUlQmQvjbVx6VL4kl0Fba"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--HgjATOd0vJ7JTUlQmQvjbVx6VL4kl0Fba
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--HgjATOd0vJ7JTUlQmQvjbVx6VL4kl0Fba
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/STt3SDJtqyfnpWXGC7w6o7uY8digrRo81Tpfa3iNc7jz
a1rbNiADZCExKaecAtHzKXr4NWqK3YZqMV5dv1o8Y+/36QbUTQI5RzRXYU3LqdPS
gieqfCLGiclmJhn2VVtSkwPLs1dmIAlOcYnIcvHTgKqLZyglHInB8lxK3bzGpqMa
9B/sidZgDEgybN6FJiR9Ey+p91D2GZKTQ4GOWWz+cLgeT8DeVQeqVkKvNURVvDFR
5FWGq9lQB84VuXbt8ZfwFxx7agfLuQeB8BvLPSIO5Tx/hguHrF6uoR9VZJWjBTg6
abrWtFrnoQWyEQaN0ssfVL9o4zxT2XVRrNnxmMhzxFlYeYq30KCXm/mpZAaKO/VJ
1XVgDen5IWU/WKS521mfw3JQfuPuXa6JloMDpn6uKdzz6ZJwpcSJ0bXyxzq3otSB
pcX8m9zBV582lDvp8OLu5QR6b884SM3VoQszXXztp4ZdwqeVwzdli1uXyWX4pVlM
qqSQ4OozhePVo6fuzrYqC/9yCBVj3sD66d1uYqOqC58m6cxp4Dl+WfQ6r+R80n6w
UmgEkp2Ofrem33nOukC8wdf6izvgPULm2mvme5AVSy+5Bcu0yDfrg7BD0g5BwGiN
IRlQngv9xmoDorqlNdhWnXK1lIyVLNNV6JyHfZqM6Hyx4QpQEaK1M2E/TMqpI65M
2G/sfKflGZ1vMKxx0oDojzokdneC8gVoAdYuefL8GubUEz+WZS7/xU8hFm8vnrPI
lQhFhZVfhAQZMuomU+ljc0M3t2nIH5QpvxIJaYFKfTPJKdjCBiKKLwc7+zgAwwmJ
4OIdNwuAxTJMYnzBYlEdtRPQIdlRz+sovL2BDMkErSF1wbsi/4HV5b6VTE8xfFNC
/4ENqbOithMAHtaFxTxXLRmxwTZR1FuElQ+B+WCmb1LzvbNNJIukekYuXrCDyTP1
irAapVGLA+tlWPbxb6cTe9YERAHvgLB7GDKacneC+e1eCHMxQOqY1xH/zc2Vjre7
wqnQb1goC7fvAnmtyHm6IHuFAgwDhSqg2e39KKABD/9QQGU0UTV/NKwMXiWgDGfq
AFC5NQPom7c1zxfUoPPNLY2yEK727+TsvK9AxjbB9rWtpUqJrT5tldkM4To5yZtr
XUDRI7auC474R0Zz3muKxU0u9gtsfw9HxSva65ml5K1k3tPsd5vSKK1l6FOlOMAu
inXR2KtupV5NgJThfLBG8ZBmzX/nVRp742srhABE0fgsWW59R2IBVFONurDGfrIO
6SG5ggcislwUzUPJCLsxKBUeD03SsAsWQUhUVri9qGbHI9hYPHu0eplREDCSUJJS
Cda+rW6bkA5ABx8AKiTMpLT8V/lgBLt4aqIGWIaIXP3VkaaD6z+FPfUGt0gX3+zM
+WlbvGxkd0++bWeDnYrKJWSA5K72FG79yfauYmy61kktd5APPNH6D2fZcOI47hn8
VAkVUT3aVfUhXrdoyg6WD0pzGMpjod26HfjjaMranNARRfosN25l/6YfmTD/3GEI
xK9d3PBUFq9yqr9KHUBzyq7gYUeVfcPjgsjM81qXJ5xjy/YRPTIQMQ1iwgczM1p9
6cdtapV1bCWePiCRmxbuOfbHeKsIcZXOCyiAF0Bq5hk6pxTuAsCi4hOReHWTJg/j
HbGVigZrlYldE+0T0gnAyv3uRc0KilEo3dfhVoqMCFqPJ205hei6tykqBztoGKWV
CWafHIVmIAht3dIO//tXENLpAV9oSpyPYuMiaXidvlXh82HZudF7+yDQP94Mfh2e
3yjxZOHFJ2JvPLdBwipZAqCqc0G9AC8KrpT8oyZ3iJPcT1KsPlqv6r4yxZ1vStvp
79A3xEg3D/902t0UGQoLqeLjzm7jzltni13+p7xaJM/ElqM6Su8j4cOub7NX5FU4
hO7o7T0Ib6IF5xSftYIGONPwj9qIdppFFwludyqrKMQ48oT9Q3VYiY4lW5woO1o1
c4vGu7eWJbD9npxUfwgHjLa3V2jAeh317xWjhLbK3A71K6kxrEmFjgAuSUqvuezw
utLnhjybxZDn8fR8XJRk6uKpXGmVpt4JldoeByL3XmiDKY2V2nUw1JwoC23CXvWL
RLkOrWEYLkK7fsHDxqE7+6ogBqn6y9h294TidyIoYy9ZkYthQblMYGtlm6RBYJLd
GoUebX8qjIFZcWsfDqhqwwxkdCPuLRcj9n0y9WokkfSrWB2CEyMGVAJ8scwWjZgO
zU+xeL9uCeSlUBmW+UPovuZH6zNiejWHaSJJmRTwFB2O5U5YWjUP/6preG4yPUMD
5Fh/3ercUz+jziLsmRmeu+TU6kYm0FC26o0t43FcMpOyTY7Rm71TMXE0UsJ5pO/u
9eTvixXtzp6WKFH9mhtC7ZM2ZISEehn3WsMk6234bO2WX/ZSrOzpfJ9cTxh/AD4E
PJjBMndppzl3nrAJJsfIqdRznRNRsKf+wZ9ZFY9IEZhuaCbzHwMoBEEfXT1kTMg3
Urm6wRDPkqg+ion9z+N2W1U+LH70iWONWWNM1CqGSo3AMzbBVgxbpvmEE2OLE53l
IP802mdrQztmPaoTmU8japAIncLVIlFIbBbcoriNG5jhsImB/VQdm0aISKNV+aRT
IGnsATpx0ZOtvLv2D/wvg0scRED7UuqXpePaG1dxzowmeE6KEkU35ap708soQG/M
UeFvbm5f1njGr6NR9llNqibY5qycYeOb5otMR5CdUllV176JXOwZHjYxl0gKpE33
axMaGq3XfKmabglwg4d5pxdMo2CSTjRX33H3fXn9/zfC2f6sjeHcUkCiNhn54l2k
xFsz3GpphfOm4j1P0urkVD8wqlsoqLIsPjQAEnzV5iR97t6ebtg/wgSf5V6rUakr
oj1i9PiSf0wkB9dMGYmSobNNKLrdFYZOucLcfWlMFS2hgJahUm5ZrS/V2mracyNV
CeiWOUYnU47DkSiKcKe6HCpjCJFRUOur6l2Oz/SqVqvcSA5j8lp5dBao/PMparSG
35/NKjjmqoQ7a5rIaWhNMdske29RHjH7Ayqf8Y5yXvttkfa3riltfWzpvmkql4Zs
/j6LbME+tgVlASf25O0dw2nnuZZ5lg==
=rXCc
-----END PGP MESSAGE-----

--HgjATOd0vJ7JTUlQmQvjbVx6VL4kl0Fba--
