Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 501D91420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:52:08 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 1FE7640A2A;
	Wed,  2 Dec 2015 23:52:08 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449093128; bh=tYsXNET4YIJUP4EPWwlpydRWBTiFjZ0v2P63U10uKBk=;
	h=From:Subject:To:Date;
	b=A8Tmz9PdugmhufyqXmpEEeL09V8hozP7kOmqgxlVkr/c2nTPXaJnNbOcorwS013Xv
	 GfLqpF1zT5UaqiJm01uP+37XYDo1MuVGL5VV7pnIMm5nRNg/doSPyA7sWeTACm5hDP
	 KqaEFAwH0ExGts/CShG2+QRzLu2jUkLrh9VDbA5s=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 07C4434E012C;
	Wed,  2 Dec 2015 23:52:08 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449093128; bh=tYsXNET4YIJUP4EPWwlpydRWBTiFjZ0v2P63U10uKBk=;
	h=From:Subject:To:Date;
	b=A8Tmz9PdugmhufyqXmpEEeL09V8hozP7kOmqgxlVkr/c2nTPXaJnNbOcorwS013Xv
	 GfLqpF1zT5UaqiJm01uP+37XYDo1MuVGL5VV7pnIMm5nRNg/doSPyA7sWeTACm5hDP
	 KqaEFAwH0ExGts/CShG2+QRzLu2jUkLrh9VDbA5s=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org, mariyka@geocaching.voidland.org
Message-ID: <565F6807.9080903@voidland.org>
Date: Wed, 2 Dec 2015 23:52:07 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="KLMRucev9tPAkjIm6CuNcrnRExSJ86fRd"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--KLMRucev9tPAkjIm6CuNcrnRExSJ86fRd
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--KLMRucev9tPAkjIm6CuNcrnRExSJ86fRd
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv6A+YJUmBr1HEDagoJxOCGuJjb1ud7uwF1FFWiAym1OtN4
ueFUbHzGhWVAfre+ZlZWfEZRCyCsX2vzjQH8T4Am2z9fI5VZBWQ3w4dc5jKvJUBR
8yfG90VQYo4nWFVg/2JTXFxkFiEpjVTiHY1n7WBRi4MjJQ5fGoX4I5rzLLRGXIYK
7l4hb+gS4uMJ1hNEtnAl0qImLIJQOHC7K16wT74+FZhyVJXC/l3Pvbn84kW7cHfk
KAze8pT655onLf80iUscytv0lJTzIgB3EDlXOzQXH70Zch+y14GZH4zXvHH0GEtw
BE456siafzNXqV8bcwVkkTBxgq0qHx94F9GRdBmU3zP+KKB3R3r6nIIlVyBabS60
0Q9FCRo9VYXWi7SaUVTW3JXiH6hPlYHojLgV0mwzOagGCbc//Uhz8fb8DKfuvP7E
E9af2OG0UGsCyyMWClEFM69ADn0D08WoNvwIgwMHdOly+DC+3CZT39IaPrzVyR39
fugn9S/rymb1pF30zL4SC/9ygCcR2aBHj0kJh14evKcHmyBnRmWjndIMMPB3Yacv
uWVLkpMgdfdn8VQCu2qgcYiTPlDGYbZrKJu0gXBDgIqQoUGZ6Uv1obwL8XXou17d
H+6uUStOad5bcHrN3fg8A4Sb9pY7B+/PxHdHW8hgaa6Wwdl5eYLC9qXGxnYbFxP9
orvUsU/e4qlA4nSGsLINftX9iUOIZKI56I3d5JvKccYIk6GYu4K+LMHzZznOhNWa
x8S6YCgxbuahtJPbql2d66x5Hb3/0CrzZ+V0bbDPodFedR9C5uSNky8TWYiD3dKF
VAWwt+3M+8U3H9nppz0jGCbT/fHv3vEtEVYP+mnnQ0sQIqhJNBqBxhBEvGhBUXDd
Awp7RRiag3s2KLl0A4igdOe37kWiATQ0yoYAaxndZmDqcbyFbqRZYbmglDMbJQgn
evZmFR9Apb+0ii45SD69oPLSH2TAwg0jA6UymPX68/kipMSxHJlDcYt1s7+gAREy
GQPuMrR1x9OYW/4mM1GE2zmFAgwDv2ykB/A39a4BD/99qZf27K91EOXzlYQ0x9be
MGZj9b9AmbBGwQJUvpb392cwNYEHEIGk3O3e4TdoFRj4EcYHXK5Hv66vhPLlU9Yq
VBGnS1JKwCJpVZhpdxgG37iOtzf2+QIUEGDNT99wYVOiSR9STq/pqzsoRevBSOr/
+mvLnseJAhTgile/vbigNJHJEJ6oy/EmnGk4b4oALzBne9ThlBAetu8+6dTdyVIU
9sR2yIo5DqafeJ3TTD0MAVYi33G5W1RpXbHgFxVRUXU+3T56+t25evxt8iEMkVdg
230X7ZJXrVildMxthSIPKeEwVspGGH3MjGYRIvddZu/jfiv4w/kvEL8DU2j5uJxu
bBxjgmcZ6lX2HXPWBg7wmOTIH6uphPlNeZQjKQbOGFFrG2vHYO0wAeUXKyXu6xKK
IDdu0fK0+Ue5rpVaoDP0fhi1ei74PLswmRnP3TUbWvwuNE9XnA5WTQcibk3Mwz9Z
G6kqFgIYnxxWeOOJ7fvr1ManWx0eYLO3A6ZJCOAcrWmgrEp5UoYmz9req3vC6sQ/
L4wtCnLUx5m/h592Cl8zC50jA8BeJRcv6vGqHwsb/AQewsRz7/TuLTOCETvrgpHj
zwx53g3vjY/Q6Mhqk0Dog2nWiZe8Jl9hLKAHyIA3Fxu2IcTsyZYlwrREdqLqRxvt
wypcCllTFyKc/NvIU8BL1IUCDAMoD+OxMaOwfAEP/0O9Tq4lIVi7AoQqES9qfJcw
4deMcX3foSlL2Ey1gtlzjJy0aV2tmKag2hP+ntCipadId7w4gKUDCNGRX2tct9We
KKBg+0gZ7RKrxkg6whuiFHaOOWH2N1LKsaQKc+gc2LxxMoFCYRrzhftS7wH1uUA6
GYQVFBMDNdTXwcfzsQ0Ep+pOzxC5dRP/oY3eftjj9NbXzxrroI3aBZOTWpqX54tn
HMG6qxboffLi1At27P9sfxz9eiyQb0MpSWJGWK+bd94DEY9soC3WV8dKTVe0gmHY
MXtHEspFm7KwfCcJBwHmizuXPCXbFauI2bGP/bwbAUTH3+EuliyDkGeG7LS43YZs
2pF40Av4CVgoHEAq0f+NiTZVgkb1UraULstRxue+Lo+i4l9DijvIBYD8prrvu+Sd
Qe65Wrsq7fumkllNMz2qhr3LJLYoXGYgm1YewJnC3+UYyzTKbIHWV+fbSVcuvoeV
NVuitZwqcaMHbGBNRJyYtsIttdG5ugh9duS2SGVwaYXGRbo8dZfw2vLMEL1vLg2y
zPtXBK5we+Te4wPEhQlVlqHwbpigbws+8MuZbKUcRler7i8uvfZG/a/BFPKfJKSB
RF1OUxBVfDLtgo1ec8fxe+NK6qXGdHc8ze4ORm4EAsRIm/DNH6z+P/hp++yZDIuo
gOWXRPETUyffqM8QVIXi0sCTATr5ROMC7/mHejYnvLvKCXa0Pdd52ihMmZa15jQY
hAD32C1zfs/A5wfoszosW3bUeTSNYYTZOHMNe9BmclnlBmRwDkeE8NZPgKsq89qL
sIbSccdHWpBERq3QBMtNlNtOD6tjZfI3Qumu1U1F6qeiDTh6t6+l9SlExOFdl7K6
9XSODLV72jB1PXYYAIRLYvGkIB1Zv1+hhtSvPb02TT6LbHj8drtuUBaIE+Yqg2SY
6/hHlx0A6zRI+2cTG/FHgZRGftL8YFfoApkzp6gYbduOG1dmZlw6BZEVWMfmvIHN
mkP0IlMG8oPuj0Wl3QO38dw74984bHU76CYs/Jd5Ptmqrl2nVtMzf/cqNcca6rqk
hkZ/xJhpYiSmNg6ubp+6/i+lhEk2Mkq9rUCet4MTuGBl6LM1Hf/Qgzy/ZqrfqfRK
lFlzYWYkEWo75m0O2bwUUTjqzqSP
=Z3Sg
-----END PGP MESSAGE-----

--KLMRucev9tPAkjIm6CuNcrnRExSJ86fRd--
