Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id D5FB0142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:13:42 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id C30B3409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:13:42 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id F2E5A34E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:13:42 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C816.1030807@voidland.org>
Date: Sun, 18 Oct 2015 01:13:42 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="3RkAFiWGaALHH4gVjHeuekaUT7EjXWSWT"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--3RkAFiWGaALHH4gVjHeuekaUT7EjXWSWT
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--3RkAFiWGaALHH4gVjHeuekaUT7EjXWSWT
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv9Ha+TCjWqDmmn/YHA9JnBVdLDcVLDPSbwbUZ1Z+h3f6pm
+Jlh3+xoCgl7Z5bBRlioRHQYb7UzqHY3aauRzO9XTSXSG7THeXYhelDEGoogdfLX
mnuV3FVgKx8BSl2eWXqtQAKkDBPhEy0u7BjUTC6Ia0xdyW3qOqCawHuONo/kRU+r
W0Rlcep11D66hj85efpZVUc7bm+8hmjofmBgCJS++mRbs3H2CH4z/KxBzdPuUpSr
Djnifo1FfkLUZFHL3+3mpOzw0SY2FRphkEyOgfF6RehLp/DkvPKMqF7bUnBLVVtC
csFkX46qvGw/Q/JYz1qKA92yAMAbLKtoYiK4TmWtznlfWIAvH7lEQnpH1lA1bf34
5Qp5EHPQd+UNc6SsdtglBmlGv9GdWdKmw/KXjQ7hkfM0YM01+uY+HKM+uKZILpVX
RcP9D4KsjvZ9q+2aIUyOjTEwfqYNETbx+ivgFDb2nyKRV7UH3tIVg+ftN7QQ3Jlu
pTi+mFa3e2Vznqzeg6R0C/0bb8Zrze7Svb2cgqS+TMJv2xs9n6m1L/8mVAdonp2F
x0U14etlIeQqtrh8HqWqJ90oZRfmoLh+dy+aBv9COQar4Ahl43zaA7i1WiNRP2BQ
vPcvGKlLV995ANl0CYJ+v8AJbyBgXFidUnMRe1N51gNZ0WLZ1t+0JsYFkY4/iIKx
OC1RNiOPK3CCbwEwlgCRbW3Eix6t8WCMpP0qh3JzOMo5ayAH5tSEHUXCdpQZiCwl
7xu7pcMSi/cEV8c2rfd+mH+ueKjxzAJUnHjDzu7yxXOBn3TkxI/VJA7rYvzSYAAQ
Leqfi71peyuiuX+XjCN+v/nbjPtQL9ry3crlu15/rc8wdZzG37f9+kNnGZdretXc
N7K8eGEElL5AsYwzQUSQfwIjmK5pmoS7+99syxaE9PstiIycVSe02/FFQ1nLNF2F
tnVGM+oM8+W+CFjsTJ+83U3Ajp6p4S+1Fk7ub6kfXKnpdZg2SOKC1aEGNEFxO1ru
pansmIaE5IOdNUR9S/IF/Q2FAgwDKA/jsTGjsHwBEACh3dmb/JYUVUtyccA1RTP1
E4zyqT2Wo42AiQeY947/fkt5vn56CtL0p0D2KVtfyqi2kIsO3ptHSuqkmY5PwXH+
eFNlqX018/9ekMLPuU50+ahMzSiVYtnvxYKxjQzV7CKzRKQ0Q17rnvMAh6d2lZTQ
tEbTSIeq/lB3kjG/FK2lNweDE+XXSdf8BBYQwWug/PYfzoeAQGJehjECGaeqhMLi
rnvUowYruN3iM3Nn8WqSjQ8cSfKmKKPtJJBfucHqDDusw2+xRrn0xHLC+kqTFK/J
w413FiKmxT7XXkinQI8Sw9SybKUgTFQztd5RgIeEJG6HwBUcfco0B4WfHw3tYYia
/bv9y4y0F2m5iL6k7dSeg7o9pblvC3wkDLOPPoXmQJKVU+7UwNnSRiqmrPKEocyx
jbsmkql7ypyVzYochg/+Kt4JpptYQGsjvaSjnWfmmW7G29N1AK5kZ5MULfVDeX5S
KPM3L/wH8Y4qXEFGnCdyRDeTq+GMasMPAsW97t8f4kMeUdrVw+NoOTF0I8ptRWgl
NjSOAd0I8K4V6BGKxPE8zPHtax+5j7EhDv8vGUl0cJ0DScw2xWx7dDULOO2NoJ9C
kcEfKStG2sHUVQOtIPF+eIWz+WUEABUuxcnIgXz1AkvzgUVaReApvQ8nq9lHgc42
LSwMq6EHH49I2QUS4/Y4etLAmgGPH1NVIiGTeIkN+kAhwdkdnLrDeEBNDB/s5VOE
f6kBcN6MehXrSU106LR9qD+/OT5tPn1oj8k1av5JUgKconJZ3AhQN2c8YeZNHVip
elnjR2ykA/iA6xr+XVGtZBrc8e7Uq3EQjhEA3wkk2u9uWiqHbVpCVVd1T3Gm/m/4
JgQ4uK8AdXRBxDc6PuAA9o0fFppcTu3RqyScxl750JrPyE9yJNqxYpAw3WhRV/Yx
F8OIfkEklB4NAPks1UCSKP587Jcg3Y/MUQm7N4PGkKNkP0/3PqjFajunMU4Q5EAA
gAcWBZxAt5KkOxI31UHu06rWRin+h1I7Mp09jivzeTC+TK+zZMH7PSleQvGGs0lu
BuZrp2/zsA+3smNeGgA7P8l0eryDT+oxqi7KBOW5BzUK8bc+xnh/3LnyFh9RWimP
OK8mRbSZGgXaF5YLN+BV61jgj+o6BOXHxxlO5ug=
=Smyc
-----END PGP MESSAGE-----

--3RkAFiWGaALHH4gVjHeuekaUT7EjXWSWT--
