Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id EE4BE1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:50:58 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id B7E9E40A2A;
	Wed,  2 Dec 2015 23:50:58 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449093058; bh=EWXSgfBIJTFjcraiPrP5GtPQ6EhZCqfArC1iZ2IWxkM=;
	h=From:Subject:To:Date;
	b=ymcOyK2330culQ6etR2aF30XvjM5OHR9aBgDsrPMzuchKVuxccKJHpmMAvimTg7xk
	 Yv27RZKmY5gUf9Ekm4glyAQ+Vap7F5W7wVOfXK+zA4bhw6tQzCyqh3MPlMiYcIPBAo
	 iRk7vW2wMvDm4ka9WZ0znUYib+IVChak/LSKUIAc=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 9868734E012C;
	Wed,  2 Dec 2015 23:50:58 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449093058; bh=EWXSgfBIJTFjcraiPrP5GtPQ6EhZCqfArC1iZ2IWxkM=;
	h=From:Subject:To:Date;
	b=ymcOyK2330culQ6etR2aF30XvjM5OHR9aBgDsrPMzuchKVuxccKJHpmMAvimTg7xk
	 Yv27RZKmY5gUf9Ekm4glyAQ+Vap7F5W7wVOfXK+zA4bhw6tQzCyqh3MPlMiYcIPBAo
	 iRk7vW2wMvDm4ka9WZ0znUYib+IVChak/LSKUIAc=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org, mariyka@geocaching.voidland.org
Message-ID: <565F67C2.6050308@voidland.org>
Date: Wed, 2 Dec 2015 23:50:58 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="vcOnkLujkiJtGTRWpXerQBdx2lK2jKiSM"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--vcOnkLujkiJtGTRWpXerQBdx2lK2jKiSM
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--vcOnkLujkiJtGTRWpXerQBdx2lK2jKiSM
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAwAgFQEgUxHrX+pvoMJcDMosxu9LHLssZAY/376eGCfX80O
rhXfNvVdRVtbz3JAyKiVUXtYpAtzZ+HdK0Fz+uu8O4Xd06AUcj5PW1C4VAG9WNNt
wFfYCqnVJFVXYzchlPxBsycWUqRjXVL7kU4ItaRIGW5CU8oyjs5ThksdtoMr0QWf
Zv4sAIyBTdUYe31vWq4vWU4OFgjju3U8mCzcpFzWze85WsyKHc/fJrCfN2G6c1Mp
k7k+fK/VKpQrwXCqEjd0U6gZYm5mzlcK71aZJhOT6LCa6P7DHYUnbyTu1clltMqv
ugoHfA7d3I0KeYvsm6PTpdrepDwVkYwOjwVvmeGI9IfRNXbWskzhUK7uhIFGUkLN
lpT3TfE4t5XcVlY1C+Krp5QMCYhU4tOS6GSnNYkOCDZYKUuzgP6uYkX0sraB7tVU
I+vCZ5tg6y9EvpSVYYdj914XH40+Q8U71CXpkPF3UjmshwMNfDQoCCXniOiuubVh
fqNDKoLKKDxDLXymD3/CDACFAO7obeiTuwlx6IlBErhlUqHE6mmQFcxSe07zYiBq
m5zBkS7U7rlPxa/Fse/FITE+6h7fdr8qGmw/ds243vRIzy6/9t0KdzBPdZuy7vl0
mxCWvy2KJ4GtGu4aCtb9HXhciJ1KbBQvgl0bqjyUPWDn21tAz2piBwazgrFOMu7Y
ihlBZtdrMr/fFf9F3BB/dgHMa+bkveC3NPUbqA+98K2kViVlllEq2nUlQA2CifB/
CIFqNUDlvUnM8qv1aLn31F5FgyRE01QvnaGtk+FLKRr45Zo/uUNumqyR6eDi1ekV
KWjOK3JbcAiIxoi6Qq45vPnKYnC8ko7oLoDkcl/Rx+pnC4P76AM2+F+5wFAoE2ps
3L7PMZCI06f2GDGy1WlvWiQuLBFxUYFr8LvOoBHGVeeZIVmgwLZkDo459o2FVZSD
PSKo1xhA7w8Ax+J37I7Ukgg324e12Rf5ZJVPTvavh3lL4OaNXzRrNdXnWnZdOE71
qxOaEgD/VD5eNAZ6vWalHoqFAgwDv2ykB/A39a4BD/993FgrbsYmROaXHodgXmBb
GLxSnLKMaPIyp73SaxiO69XwLFGjGJLu67KkfxVWHBu8ryxy6HTvkG9AYkZscp70
en0DS+Yjy8dcZiyHBAQcB2kI7gBg4t9CuxFzo28JI1lkYufM/2t2iONiaUoDERgP
wnWdZmwIDzpgc+40Q1CsZMQtzxVx54Dlamo+m08BV67VRgS9wbqSuweCwzuCdHst
jdBL39JLGPBPxNqB14GCdz5540GL8be6ygN3fw4Ybf3ZlTCxK8NbjEFi0XzeHW9A
V8T2ObgNQoP3rbmGTjxM0EW0YGgwJ4MSUT0kP0kll0WjfaYucyqA7TQnpsz3hNQD
8vPsnfba/XAUirEHirbBaHdXr1sM+w3bQphZUe+ML1KgUBV9fO09xiFkL26oqi2d
a2C6TAFTwNltMoVRLqxhNkG1v1z+dMOMDZRxTK1uxPjBkP5jiaKvCSms65REf1c4
D/aM2eW3c4eBjPgYmKKZqNWEK3LFpM7rqaVDzy8qsbV3PSv9oQTSJKX8QC6e3ZwD
ahBfnpwMoBJTF/TXxOeRL63dMY0U2n7FymDidgUdeTh72KtCu8tcQ26Rm8WZQoxo
goKzqJzzvRZnDL0p+RPNf1cQE7PQ/gldEYlEpdl4mARFn33fxVby0Nuu+p7RHtTT
sYUrRfLESB75gdjP8dcrQYUCDAMoD+OxMaOwfAEP/0KFGKsQtpUo6qBeW6wFK1CS
UvgCE4awSD5FOEaaiE0xWnI2cOWJXQua83A6c/IoE2O7kl4HbYYH7CXDunkvqzzO
CQEaPjIJtroqyr7mOtw1RfjFyDnUCSnGrydx1hU8387IRzVcGGsg6oQfNuo6nQiD
bIvNnwyBl8sxPVPpXNcxkivjRd0yI7/DhSPHgCzKP1jToTJBeAtBYjg79I1Br0qy
8yk70RTIsBjIqlelboOmt3HXr9LlyA1Ioyc/SxkNbgxW5DsTR16Eypn2rv5cZxg0
m0UQKBYUuHMTQmmcpa/oTUV6an9jcfKZL5cKs7utzCTtBu0G1lGEVtyP8XEwoX2x
FHTu67dH1vwp+a26v7VxzAkSqSb7S6m2SgOA5+Jdi1LqTfDgefiHq9uFM8oYO7VV
i7q/cdOkBvnUyuTn78Kbzeq/z/esDoX9ue7TugwYI9+xz9xgDjpvIsIO6mWX5xCE
r0vGizNf7qQj+3lxLNyQ2hoA5jxqFwce/9tQL+N4xOqeAyvc6sqC46uoqKoErkrT
X9t4jE4ncoGq6BoV9h1YD1AwtgCXylmrflETEZirqkZAMTHKX3TKuvSs7g4eUryJ
3Eq9YAV5MsTbQLKbvJBAKQNWtVZK/qonMLj0HdZ7iz3H4acAhCA5bHrHE9kV0kBv
1Hkde5mUzlU34V45GXSV0ukBLziO9nDgFq+loVqg/5+Ubsv4j/rjMYZ74b0fHafu
fQfUwtLsLOATOWn3tnCgvz6sg1liQG8slU6YDMierKm6RqKIHmTMmVpAn7UQrhQ9
gsz9VwGVNoN6j2nV3IrOH57ypEXAtbh48m5Oz4IVK0IQd8RjGCBSrHAlLGayjzeI
WpXfVF+QM6d5TE6ooulgmp/MZ+y78INKaofIqwnxJmPN75KcReqOqdhs+k3gzvPw
j92Y2FaGVkRD7X19v2t2DdwX+JO1i/HHJkyCZFy75yX8kZndeVoE1Ahh2nSTp85Q
GBpxhiuTfl1Ji2I2lCu4IXGSO62HJOSJvecPm+dGtIRbrDFSff3Ibf+f3dZq2243
w2G+MDJJtRXpsdJbPwAakgkCEtaDv6QEFnSkV4PxNWn/gDZcDiv0bApf7CRJRomD
uUrEATWpbRijq5Vqu91JFrz4bAh902VfZ4tL9Brp1osj4dcTpbo+8bM47EUkgfWB
c6KeipuiSur0TRF7urkbu8+U5CBhVo3hm5wKbbxNUEUgbTJIb28u+hnYK8+XJEle
A1Y3hUjWV7LzMRrYXfEUWX4w59h6odItu/OHdb4ZYuWdQ1pwKmkl2LWOiOTP4duL
bLbA+my61MjvxoFx8hLrr5PzKd8nf4nzpJlwwjUIWMtnIUh+8aLdxguQJN4x+Y7v
+8B8KgBX6e+yY492cpojMBjGz7zmzNnqB8I/bAyC3X4UfybMPxwn5cJatRTnuiUy
GfWJFuBFF4H3JjYK21v10TYqKAuaBTFDCti964EUwqU3TYH8WZOSnMi2s18GeCnC
Db5br0fEqh1HG6ouCDnTPmU9e5oPvpsystXiN5lTYoRIVxLojuaa+D03Gm2AoC4M
+oqsdybp9hy70bfxSssGFOhSVsK7XO/2XfzcEsU96DXX199pRw0nu2rlJeXmY6Fy
c5e/X8mOytHNKA262/mbaLXX4nCChVxIe8OaoLeNoqvjBOqOae/VZ1psf8pdXvua
TPSI6kNPNqOCuZP2GqnLBABGjeKzf1PubN79zpukOwX93jD3+itGss/cw4szFI3N
fhCdrKysWKWwTjZ4AxOAShgReqt4Hc4eQ82MgExiBw==
=1XyZ
-----END PGP MESSAGE-----

--vcOnkLujkiJtGTRWpXerQBdx2lK2jKiSM--
