Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 34A1A1420017
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:32:15 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 15212409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:32:15 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id DE8AA34E00A5
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:32:14 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622BE5E.6000408@voidland.org>
Date: Sun, 18 Oct 2015 00:32:14 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="Mh9UQdTTIGG4gXnBVtp7oxqDmbDkutAXa"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--Mh9UQdTTIGG4gXnBVtp7oxqDmbDkutAXa
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--Mh9UQdTTIGG4gXnBVtp7oxqDmbDkutAXa
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv8DM1K/ndAHXdMxZg2ZbxdKTi0Op3TcHNyeS8id1+qbUGg
AZqvVZIXwS88vjzvkMN2fzN9N/V0fuxtk5udkLcmCIfUc7KdL2c8eIZYSj9+7bIz
8PPkQVMj7Mj4rtVgVMHMqvuIGwyRnL1FEhmLYLW/8QctX5mCKzPIUqqfMFRfQDGX
yTnq2jf1Oza3Lmq1eS29FHBmFBIgAan4RaIlyvEAL+KKvyEo/roMSAhGG21S/f/e
aXdj8BqEX4ciVtCuEUxbZMbviynvzccLHVp71O//pcxYfOcbPrxKz6K41uqIcB6r
CEgBeNta4Qt87CuLTzQy0sxhmyot/bcc+M+fak3qKZ8AmJOeLGR9XrNGLfeRB5ft
hJT79SHCPbnELHS2RR3/+MI1F2ztufr6YQqAGiO/6PLyDGT1mpzlSFQQARLpbih+
uesZ0Q4Ah35tTqNysR8IeZKFZeQIIMv7UAHRPL9eR8yPTwNuGz3bnujmT1p2drTv
DynQxOw96HCRVaG6VvDUC/9KQKbTLFagNZn45gOxXXpYVnJXxKt+itqwerijvI+d
arjYGjZLatTusyWo//Fua4OBYfequ6UjkKJBhBqcg6IUF374XdDDHc7SUL/163x4
RBavn9/lXyw8dotApJo0rd6/HrHp/Ui37Vg+CczkWqeXfYi64pqEdudYvLbc1F3P
3IiIR05dTqGBF2QP1Qvk3nfpScyUoZ+y4Co3wzctv47TBVjiEOp2kCvqInVvxctj
FsvcLrXS/mgCGT27UU/JuHcyiQUMaqAR6Lk5nhBDsACrzLkP1JNnXtxVb9eCHNHd
AMI33i5wGOzYuWY0ty/Lmw5umGTMuiPvBW+I22+wqcoPBpj+c7SyWeyD2ghZwJM3
EQUkK4iT8tq0qV6q5yVzkKmyCnhwMnUCL4ShNPwFC0iefCJz99UzoYTSFfAues/V
XilLWfvSqhtvEkSVXvUQ5kg7AhW4n7t7CPRQrGwZl7XZzbnA07FcfWxB4ohwfTeJ
h7N06I1GWzh9yEzt7d1T3DOFAgwDhSqg2e39KKABEACESzVUVE0SHmc5wGEUqVR7
NFbkSfazmhVvEkwsc0lHwnyd+kt+cr1ufizqEO/ZKgTn2WQatYEV4CeaC33pBIwY
oipWgCecQr8D46c6h7gdrOFrYXu+VBmICm5LRf5dwUw8xVS4lIezUnGxYLFBvNUg
yEnHpBUUVCjhReB0A/YbZ4opGuU6KdjVG+CHpl4QEqKfAVRPm2kndIBlld2dbwv+
9yh3cWyEHj+Eiexf37Y0BaC+PGPA5GffJ/raofz0WyGc+ZMAobdwtzeKfQ0e/bHi
W8T55S+et6+n5I1cKqlKhqyopDl7FilwNLRnyMnQL50x+iFDisZg/aCvjJBAm4XM
lulPlM0Y+euT89E5aJELz46wanx5UJdropA3/QBR5ddPG54nyoa7QYuhZ8G7ooxp
eJ5YQCNFpz/Is7REG2U3S33MmKdpvbm7Y5vHA1m0gXNMcbDWDCctyB7Gn/T+yFwj
7XDEmnvg/CPVFcPFfn5BGMtX1jQb+trirY/U5JFb4jmDcOqiAm8IGcirp/hl0eus
NjdggUYM3402Lutk6ZDTwPC935E8Jrr/dZrf14457JWRLb8IVNmLL1y4BRs+kE5k
WyuQD+Zh0m7jmBNFQagZNJOEGXvRj58wzk+RU157LdznUpK7b/Mair8YOSzFD0gW
WoOxmJkSvx5XiZuwXpKnytLAzgEm3UFNkikt8LtKgdChcMzPfHKPycmDGi/d+avr
htc1Rd40Kalmf+B4wDTGE6CWy2niT2odHo1PJgbgMB/xD2g5qlTuqznrumT2i1ly
UrlkZJ1pks9I7YFz9N9rlDFLjUjhThorxh/9aEbZasWeO8/baJtmpsSqXfAYCBNz
QwrqFFc/sADXbAXRJ5Du00YYE27cLah3u/KsfaW4xOpB0ZsTHhqa5m38oc2i3Ie4
JmGJG1wDReyo6Jgz86Su/nLje/WWKzj0KMDQYRj8+o7Qfs5DzvBALL4wGrHJ3tDy
rXZZfaCxi3HuqxtljpuqJgHn/sdiYepIfLSATuuLDv3F6jq13dbmrAZ2IpCXfxV/
cUh4QavjXSVVaXEDXcayxA4i5ZIAPtvgEIMk64ClEBzl9NB+y905bo4GFUa6RT2e
i7Q9s5pMhSYHEpWICiCtbCFDLmWp4jrOdIDoBiTWfx7bNADpu7rDDs02UJVwFtdv
mQd3/y33V9Y1V9Y7N1qHm8B5wYwcBSzkD6nGqhYgPenN
=yfYH
-----END PGP MESSAGE-----

--Mh9UQdTTIGG4gXnBVtp7oxqDmbDkutAXa--
