Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 667671420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:46:39 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 42C1040A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:46:39 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092799; bh=zROTKt4kXED9D4RFLFQS3GX9z2wlkAUcwCkPCnRmRpo=;
	h=From:Subject:To:Date;
	b=EzMVGEBgEjGtGQmSBkDbEW4JZiDkLoiAiUkVuXMmO51vGTFcan/zHa3vPpEyg5TM6
	 boaGBlch5nFW1VbjoEAUIVj7WKOQV08duqEoJ9JcoRHFLht6k0fkGTYhGmPtYG2l+a
	 RBZSOGBZykEeN+tmp5eOnZAL+4VcKzRq96yjJmPg=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 210C934E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:46:39 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092799; bh=zROTKt4kXED9D4RFLFQS3GX9z2wlkAUcwCkPCnRmRpo=;
	h=From:Subject:To:Date;
	b=EzMVGEBgEjGtGQmSBkDbEW4JZiDkLoiAiUkVuXMmO51vGTFcan/zHa3vPpEyg5TM6
	 boaGBlch5nFW1VbjoEAUIVj7WKOQV08duqEoJ9JcoRHFLht6k0fkGTYhGmPtYG2l+a
	 RBZSOGBZykEeN+tmp5eOnZAL+4VcKzRq96yjJmPg=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F66BE.3080007@voidland.org>
Date: Wed, 2 Dec 2015 23:46:38 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="Pv4au3mXSG1k2p8HrNlDAl8op1CH74j3h"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--Pv4au3mXSG1k2p8HrNlDAl8op1CH74j3h
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--Pv4au3mXSG1k2p8HrNlDAl8op1CH74j3h
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQMOAxJFBmWPsF+tEAv/USPj7CvqWdoqyQQ1G51HvQlB0LVpIj86ynNozUeraM2d
Y9KoHCjD6Bc9uaxsdk16UDzLI4Mrvr4/XJ+p/RcVqKb+acNr28NqsF3DD/Oilh/a
VHD45DoggnxGp0C4z4+A357LAyHaG56itQ4raFPRx1gp6vetCkI1KSZJ047vBxO5
AWvBPLZKCA7Nrr3+729J38wTQ2f9542ETvuyQDzzv9DKlwuy+LRhw6yoddfu5LgS
Gv+2CfpZWzIKSTuVbDqjdsuOily+2JRqq9Io0Hv1GrIOHrAdulfE7h0T/mSkgJAq
95/SI1lbDTmEFbc+RCKyeE2gGzeei1zBUo7GKixJIGaGjmABTIzPmtGr7W8P4MW7
L4y/Xkme7+c+TsixV/ZpYHEgUXxYCxI1IXZKHO/uxx/e7SRbx5njkR1GHGq2aoYW
3QUWwPoVowEO3FlCFhYbA1O1INuLzy4jlYkjCUu0D66fAsKFXmxg0x1EvTePUxKW
N6XJEDCLZ3hz8FSfUxLCC/9gTqrXStVx+bl3iqPoSFikIUycsWTI7U/bI4ZVpU0Z
HBeJwhFdO5eMwj8gXAJxMn8VepB495FxRPFdjJaAjI4BjBcYO+VuSQ89qc+EWOYb
o6zcUCiaAXb9raXftQSX2uwoQUYQ9B52qhqJG/Mtt59XTH6wbf6ctUVqSZAPSO4p
50U12Zr81UvEC4Dg1SRvCGZDpiTjgWmALJVWrxzTER64KqnmBwujPCnmqzK8yi0c
ufhp1ZgRGuprx6uBYWCjrZ+WwXUmDPhdFg2LSbD9PWg1UUTsvAewoeqHXN0nqpRn
M1n274KzJeGaAeLtp1l079zfCu1ZfZHDMNGhUMwOfiN9uPj1hJY7MU77K+xB23E4
Pt+jvGSoCL4RoqNLMRfRNOXptXlUhQ8SgkYlv/s+1dNrOTwXIBIZVUCv0Ptg/+kr
FLfPxLQoWF/+KZ+v4jjh55sPOWYybcGzYGSJnWsnRPCO7t4gsZI1pZgosB+M9us3
1ybeexjgZmoR9vNrIRs01pWFAgwDhSqg2e39KKABD/0Xxm4ZrvZN7xWmf163sC+5
N5VrU+bOm7jbb0HOw75iyus2sHhzxQINvbcZbox7cuc2jorp+Ijx5u32nVTXlzUd
PpWpx/ABwOQtyUrtMg95Ncp3AL+8zgrfr+2CGtp+/mthcKrQXxdJlIvCo3Dkt9Mv
l92gJEspTCZAUUF1sGnodQCdam18epVHiixcLABrS2JWGI5LAPhjNv3OyIa2wV6p
5omReeK8oa60cnOdvEqqTImd/gRm7mwJoiC5MgLOGf1sbeZXWAOphGFsS/B0UOwc
iUWKxHiIbx9Gh17ZaBOizeyolpGoIS23oVDERBXsFAjWgLU0Sho7xhD8f36QJU4Y
XUp4E6tZKt5sjrqaCPZDgiWpqDcnvTljwXGkDA0DwOXWby9cfQA4+5vdYVcevL2C
8KmKVVhMne/X5Ld0+29kDip3zcQyABxvMS/uAQuqp7BgQQ6Bn1VhxeJBCV/CSllx
fRKOTBZFbYVG09g9lESCHUMYuKpGzAyUPQBixBFJbQgQuXfr2nQkPUMoXj5FpLmp
xL5VL0q/GfxtK0Pl3A7eR7r8Re0zUqcw81bBXhC9huuZ3Qjfe44AUM3xc2fXzbkf
qGtVM7fEpCsZRKIlvRSiscWR+Iqadx71eq8prCEqoGy+xGUhEqEHdyHuPGd/xD2o
RwcshSzU9RFd+/PIMymjndLqATpYlrfDvQc+PNFYLs51vcHjkcd+Lm3gr49K2hTJ
jQ46M6tP7RnNhbJn/Z5jEasb7u+0nq3DaTS1wGB+DiKBKjf8ZmN1CPMV/xQlDyv5
eCJb5HG6xeAjntfY/jRgV6ExSqzVROTTiqJECy0uU137huye9Et6Ohy6tibmAslu
zmn3cTBr0DUrhasqgwFG39tqdgFizItuU9gNlGPyLJRY0dGtmXZISDVo3e/qYN+z
dPpUDZuntNxDbUP+BQX2jHPHcT9bL3iCsRfLzQJ5Oc9F3Scvq/cmR3CcXFGKceFx
cgD+6nreJxaiB7GC1y6oeqIo3+n9ckfAFT+UoHuCMmykk4Msn7RAYil7/cm0lLFP
/ZTOizp+ms8bw4VrdvAdydM2IZLJ/tPCWxYPZyo9z+ziOFZSo5qauGlGJXRtu1NP
e8qupgpD2/b7CIe+FwW9djX1VvC3KUNzsHuJVr2LZ4CIyaUjyopUYiJpVy7NkhOy
yEqTJzJgt5iHOq9aQdpBwkYUFK354jJfMQcurbiHfwk1RboD5SyoYSXJfJbrTun2
EqijgUAo6hzkMJo0D91XHsrD3eGK8m3nrzFX7+V0UWChPIxvvAMynPksGaNVI2rK
tE1vc0kozfZz/PrSjq6VZrMI7eGAO8ZsK2nsvcxaakxMsc6wRa5WW0GbKj9fIToR
lR392H0Z0LXI1fKylHAeK/WjUpR3nw22UjE7M/LiZlObF2LjUg9tLKi9UdXk8gVc
NixLFpL/+7Yy5DKkvuDw9dzsO4+SEY15R8+OYIEJOEQUh0jEriqW83Xzx5gPXUN6
nECI6m6KhgXeYdRHDn1bvTliE4woKlwEr1RSVHYpySWnTAJIaSfZk8Yizz0AXVra
LGITwQDohxy83jf5NaDcTYV4GQmhyG+A1r9OJNbiOq798sO3Y0mgfj4VZGd1er+z
RojOrywUDBOYCAqCdyiP+IJqvolj0/jwym5aYQo6OluF/lvMcYrMQQx8/evDvgNR
84Gj4nLuNlHGHtWMet+YIhNSy+LNSeg7gAFZKFqOKP369PvYQOncGVjuiYDs5REQ
sJWPspLXRQ1kmYbtKfR3gBOTAfpVRv1+T2YY2UWo8n1EuFm/lqhTOLa2hodfmGIq
exg6IKA8H7fakpYLhhYgJHDX0GCbwyzu5akWk4JhKTMEBntGbqkxxfPn3N+KCAr5
O19zPFTfBcl57qUtwO9l+c7gpulf58dW3SwePem9j9Wm8wIRS9LMln2gtYIEFFn/
fh0Vh97ye00GtvVdHIykDGCf1IrLkTQeo1+65K/qiVkJSk4OeNwpChTl5aGgz1Nl
c5zXAzjxTRDhZ3nljYcx2DYL7pxwz+cZSVDpPtGvYfs/hgQ7wCfm
=e0+l
-----END PGP MESSAGE-----

--Pv4au3mXSG1k2p8HrNlDAl8op1CH74j3h--
