Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 02B4D142017E
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:20:30 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id D3581409F8
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:20:30 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id C87FF34E00A5
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:20:30 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622AD8E.3050302@voidland.org>
Date: Sat, 17 Oct 2015 23:20:30 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Alabala
From - Sat Oct 17 22:30:43 2015
