Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 15AA914201E5
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:41:03 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id DB29E40A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:41:02 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092462; bh=tHZbNNUMktcyeZW2vNY1rZ/WHHj49Ckt1739OJej508=;
	h=From:Subject:To:Date;
	b=IkqjPgyb6v3xdKqJizYk4j0YMnMJVOA8AvGRNGj+hnLgRGPq2P2aHAjyepOwtdJt5
	 G63Rffz1nA78NzWUazWyRcMBEtfHCgykkZtvNC81PRyuoXZWQjObptXCj7erdsySOE
	 HxPG82J8xpGyVCz1lv+QR1qUWOCGf2dYcJLZnXpQ=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 9AADE34E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:41:02 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092462; bh=tHZbNNUMktcyeZW2vNY1rZ/WHHj49Ckt1739OJej508=;
	h=From:Subject:To:Date;
	b=IkqjPgyb6v3xdKqJizYk4j0YMnMJVOA8AvGRNGj+hnLgRGPq2P2aHAjyepOwtdJt5
	 G63Rffz1nA78NzWUazWyRcMBEtfHCgykkZtvNC81PRyuoXZWQjObptXCj7erdsySOE
	 HxPG82J8xpGyVCz1lv+QR1qUWOCGf2dYcJLZnXpQ=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F656E.4070106@voidland.org>
Date: Wed, 2 Dec 2015 23:41:02 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="SF9CIL4R3Oa21iK61wpiNXsGSt0GgFBhL"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--SF9CIL4R3Oa21iK61wpiNXsGSt0GgFBhL
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Alabala =D0=90=D0=BB=D0=B0=D0=B1=D0=B0=D0=BB=D0=B0



--SF9CIL4R3Oa21iK61wpiNXsGSt0GgFBhL
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX2VuAAoJEMl6bvU0WTOvl+8QAK7HzXqeXiypwT23MENI3MGH
dG7Wa62/iHIVpBYN6fCw5Tyltjr/dKBGZlmXVWsihDSkH6K4CNWKdz3am6YPnoKZ
NEit39txD8YJZxe2C+ta3qZO17KW5WSmWVtlRnfPoNGOrEgi8Hh0PU3jWcPokDqI
vxBqfM+aNk/hVo1jFt7e6bhk04GlhhHhxkns37AYhAd6HEDk+6V9mW0+ybAbpBna
DWFUVX7F9la/SSRZVjyF/o2+TsgAzibttr4P+LMQ75YczApPXUk6K1K7gcg5d5oV
jor7CbhlQ9iMXRapsy9fuSbGgKXFAfS1b5HVxzSlrSYTRyXfjViZld/JkdfH5Aep
57xjp6vKgSPaM5+z/VbSJa9BvXPZcw8b7mGjrTPoW5EJ4EcIRPdY+7QrF4U499FI
HP6l8nG+Urol+6Bv8hVggpPtMm3pFhyTfrHofxAcG9rzCmvdhysstlFoYcxRO7dP
6++n4Yuf3IPJW5rqHG/Onlmbwu8Sbr8HO3f3h75fmVPt7zvZAVgDHH7vkEWIDRwm
uyZq4sJKuPLWqN88XbmFsN0Uzh0XE+MvGUuDyzxx6kC4RZJ3IOU8QdqqMZbzzp9t
eUQ96Hx1AK/gzb6itDJSYlGWiuqWBq0VJtr8ELj/R/UMiIa0OD/TuxDZ5WOE61yp
j0GrWkkhmC6jA05506YK
=jSeY
-----END PGP SIGNATURE-----

--SF9CIL4R3Oa21iK61wpiNXsGSt0GgFBhL--
