Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 585BD1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 22:54:21 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 3A17640A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 22:54:21 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449089661; bh=5Rtg0qTpTdAnZA/esd8B+dBvaQTAdAXAhjYv7lmK/FU=;
	h=From:Subject:To:Date;
	b=elKBzV4iq4HbatR+mz5jOnnGeT8zUZUWOUvRDK1mW+EvWeNLw6QCd1pkTNmbcsYmZ
	 kxCH4SahknTupF5vKUQFwkplJPLkZJrTbG6TgrCdl47IuFWD90WPkVrfgbiE+orJ1p
	 7ICtEr0blzOaQZdsgdsKgfw2QedVjZFiKokX93tg=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 28B3734E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 22:54:21 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449089661; bh=5Rtg0qTpTdAnZA/esd8B+dBvaQTAdAXAhjYv7lmK/FU=;
	h=From:Subject:To:Date;
	b=elKBzV4iq4HbatR+mz5jOnnGeT8zUZUWOUvRDK1mW+EvWeNLw6QCd1pkTNmbcsYmZ
	 kxCH4SahknTupF5vKUQFwkplJPLkZJrTbG6TgrCdl47IuFWD90WPkVrfgbiE+orJ1p
	 7ICtEr0blzOaQZdsgdsKgfw2QedVjZFiKokX93tg=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F5A7D.1020004@voidland.org>
Date: Wed, 2 Dec 2015 22:54:21 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    <b>Alabala</b> <i>Алабала</i>
  </body>
</html>
