Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 9AC82142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:44:01 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 817B8409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:44:01 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 8A79334E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:44:01 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C121.1000005@voidland.org>
Date: Sun, 18 Oct 2015 00:44:01 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="Hk8X0uOFH29fAXwkWGFFn5fWmg0LWBAb6"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--Hk8X0uOFH29fAXwkWGFFn5fWmg0LWBAb6
Content-Type: multipart/alternative;
 boundary="------------060002010504060302040507"

This is a multi-part message in MIME format.
--------------060002010504060302040507
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

*Alabala*
=46rom - Sat Oct 17 22:30:43 2015

--------------060002010504060302040507
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body text=3D"#000000" bgcolor=3D"#FFFFFF">
    <b>Alabala</b><br>
    From - Sat Oct 17 22:30:43 2015<br>
  </body>
</html>

--------------060002010504060302040507--

--Hk8X0uOFH29fAXwkWGFFn5fWmg0LWBAb6
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWIsEhAAoJEH+wSfeQEeGpa1MQAJKogpvOje46mDNwzxD3v+sX
NHhOdQzC7JoZdE8dQbfQ9UpipVjvzWcMZXutZyrZUiiCdttHSvdl3qDBXvSlWm8k
2TzPDl83vaAFBEjvqu+QxKz+f+VChGQsauBb+ioy37+2lYxI2yeQLlHNYpDpSktw
P2OYPiOiP6gaRjgnps6BFbDxY5p13l9rbUJ15MpkRtWyec0G6icfJ8YL9PjfeGpk
CDXwJIKLSOgHXdHZ1/Xelmap7Bzlq9DwlPz02kIWCXLOfJ70cDnyq7e4slfmt6mD
6YgkKaDhY4mNQFk5EQ4bLUuZZGNRjwCDouBGhmjY/cUwliBU3WUUSSEUcn9uUW9I
SVNNLSqkhdPPGJMAf3IHgPwXmgQUTbYoCFJxeTpVu53Az1KJ5fu6xN/ngXQM6Etw
szdlOASClZPHQHPmNmhIbM+VQdt7ZlTBgj+SaQ2LaAgG+Sl0Nm/w7SGaYPdnMQ+J
UoJftiHZydQPEqgv7TxCvh+keCWkz2elXi+I96yYwnIpduGT6CJXrNsZUkSL1NR9
6UAISEIMb5S14ltyMzqnFn+PhBxFl2nezhR0xVi74d3RczGWEKqdYI0coC9c9/Y7
OWXrI1sY9zIIM1TxZ/OQPUQ095zxavi18nkXOs7YS/dlXMkosxGnRCydKWQe1XVk
tm5WODJrj1RGEOr5JIYV
=ySbJ
-----END PGP SIGNATURE-----

--Hk8X0uOFH29fAXwkWGFFn5fWmg0LWBAb6--
