Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 8331A1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:48:45 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 64D2A40A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:48:45 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092925; bh=3Dl30SWPaVI7Mi9cphoIHFTjpxSrnjVvipaAFxILYpk=;
	h=From:Subject:To:Date;
	b=lI+IvdJFk0T5ul+rMCecuG6O76735ivRV1E8U630zyKoG3EiHhAbrX9YzAzhyNKzl
	 ZNgFYX+w8KS4HTu8ymLQiuDvnQ/QwrnjTn7yFlytq6hYv2Ub9PG63lB9sS1ijTha2L
	 CVJP4qXB+ryiNIHihNGHiHSnRvHIyGmrAwEpEE1Q=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 4A8D534E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:48:45 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092925; bh=3Dl30SWPaVI7Mi9cphoIHFTjpxSrnjVvipaAFxILYpk=;
	h=From:Subject:To:Date;
	b=lI+IvdJFk0T5ul+rMCecuG6O76735ivRV1E8U630zyKoG3EiHhAbrX9YzAzhyNKzl
	 ZNgFYX+w8KS4HTu8ymLQiuDvnQ/QwrnjTn7yFlytq6hYv2Ub9PG63lB9sS1ijTha2L
	 CVJP4qXB+ryiNIHihNGHiHSnRvHIyGmrAwEpEE1Q=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F673D.2060308@voidland.org>
Date: Wed, 2 Dec 2015 23:48:45 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="oXFOtGJSpEiEr0wvPBMj9sCBid5bUTc7C"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--oXFOtGJSpEiEr0wvPBMj9sCBid5bUTc7C
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body bgcolor=3D"#FFFFFF" text=3D"#000000">
    <b>Alabala</b> <i>=D0=90=D0=BB=D0=B0=D0=B1=D0=B0=D0=BB=D0=B0</i>
  </body>
</html>


--oXFOtGJSpEiEr0wvPBMj9sCBid5bUTc7C
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX2c9AAoJEH+wSfeQEeGpXz4P/RUcPPUzDQCTL3GftdJWcIoZ
Yd+4vgk+rBoSNrC6itkPEl28FFZiYLAofZbXeZ0SeoULRMkSmuGstFyolMfX+Jwo
b6Ju0cvEIJwhAMwn7rPZRUxG6cTcs2Q0svy2JXul+LtfuD1453yD1TPQvt7/RMuZ
1RFUMs+gB9XgDc0hiu07LRz3ns7yGugVXLwZ+HnE7fkE11Fspmzmq2fDcXNgmHWW
s6tCw1/6qVnlq+6NhksPgeXfx9SpNt8hR9o234Vioilb9+LeA3BHEE53dWYX5b+D
CbXGBAil9NMo9oZUSiAWR2udBDTdZwgfubvUisv1L5adHhM/8pUUQxd4VgYeIHUc
KCW/9VXtG8CIOJH2qhfSKtu7XECZqndmIJjeaQqFiwv8Y/QXQ+1qJ+Q9t+g5h23Z
lhtgJaG04rkbSfDzqzVzs9rK9MdVpqEH6yT87hyatSu89lOPLH/HIRhe+SZrCkGL
DZ1Gq9ivm1ugDT6ASl5h1hGdTPaUr4mfgS6CJSwbGi55+QLcF+AJ4EWiSD/uxlDo
JrbRKR4pT0JEjWjwaltn99dKrc5f1BldEz6gBzf1CkcJ+BJc447927PnYy25txPU
uSr3TbfhonA8pvla/8Ea5YVW6V5UidcgDXZItVb6O3E79Z5ny8xrFhZZ7bmneL6y
Sm5AUr2sRnQlHM5hbi0x
=P9s8
-----END PGP SIGNATURE-----

--oXFOtGJSpEiEr0wvPBMj9sCBid5bUTc7C--
