Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 981C914201E5
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:25:22 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 6CF9440A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:25:22 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449091522; bh=vhsF7v/jDpQkrGCB4eN6BuRQqJn99iX2+JMo5fPYJtw=;
	h=From:Subject:To:Date;
	b=SL/H8pY58lNQ6uXk3AXHW3waQuyLaoT6iZO5fg44BOMNKnz3neLu/qpmROr8wTq3q
	 yGw9CeJQkMLS9OO9SZV78lqHMIHd144UTtp2szL6lNLNVX/hV9RMG1m9vBs0rMGV4c
	 D9WVDi6bmL3gYDXcbYnp+kp6oy1ykX6u6pXShxrE=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 1E56234E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:25:22 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449091522; bh=vhsF7v/jDpQkrGCB4eN6BuRQqJn99iX2+JMo5fPYJtw=;
	h=From:Subject:To:Date;
	b=SL/H8pY58lNQ6uXk3AXHW3waQuyLaoT6iZO5fg44BOMNKnz3neLu/qpmROr8wTq3q
	 yGw9CeJQkMLS9OO9SZV78lqHMIHd144UTtp2szL6lNLNVX/hV9RMG1m9vBs0rMGV4c
	 D9WVDi6bmL3gYDXcbYnp+kp6oy1ykX6u6pXShxrE=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F61C1.30302@voidland.org>
Date: Wed, 2 Dec 2015 23:25:21 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="cPd7L1emUCelsk4J8wvEHRhGXeURciA9t"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--cPd7L1emUCelsk4J8wvEHRhGXeURciA9t
Content-Type: multipart/mixed;
 boundary="------------020408080101040606010801"

This is a multi-part message in MIME format.
--------------020408080101040606010801
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Alabala



--------------020408080101040606010801
Content-Type: image/jpeg;
 name="BorPetVlad.jpg"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="BorPetVlad.jpg"

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAQCAwMDAgQDAwMEBAQEBQkGBQUFBQsICAYJDQsN
DQ0LDAwOEBQRDg8TDwwMEhgSExUWFxcXDhEZGxkWGhQWFxb/2wBDAQQEBAUFBQoGBgoWDwwP
FhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhb/wAAR
CAA6ADADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA
AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK
FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG
h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl
5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA
AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk
NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE
hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk
5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3J/GXhpbpmiBaOGKIgKcAhs54PORj6VxX
iHxPFda5O4hkktfLJgAMahhzuQkZG7GD39K8c0XUb3UPJQsAZmWMFjt3469e3J/Kpop9dttE
uUvbMpa20JSN0jxgjlGHvjI56/jXNHNqlSM+RfCcMcKtbvUwPFeoXn/CUSw21t9htbtvkRMM
iNzn9D+ntVW0F9batI9xtcrGr2/mFShbPOR/wHH410svh3SZ/DNnfvrMi6zIcvaG3MscKkkA
uV5B24boe1cf4gm1IXUaWcsgu7eQxxzLbkr8p58tiMORnOBnrXiPD1q01N7u3nrdfodEqMkt
iT+0QfEEr3uG3NhYkUFSvcemetdh8O7600VY5NTsIfKkO/yZ4EZdpzwMjI7HAIrlfES67BfW
c3iC5bUZJocwzyhPOU8H59oGRyMbhnqM1n6lcanEJIuWZwNoAG7I757dO1ceLlXwuJfsHquv
9fjfQyrUp7NanpNjZ+H5/EsqwXF1eLFbeZFuIx8wIJJGMbTntycVleJks9L0a5Nzr8llptnb
y3DROoZmlVflVT15YKAOlTR6Np5kDqJQQu3du6r2XjtXJ/HOwtbT4c3YtUH2iR0QbgW4Jy2M
9DxXbgsZQ5lRow0k/wAzvVNQV7GFr3j61t7vwnqWmaWbaKLTFN5bJMgN6GcB1LDJLblPzn5s
kjHFe5t4b1tPCuo/2rd+ZbaXozXUcVjJtnjuEi8xVUEH5VPHfeOuK+JbWG5REkMbAszENjAy
ew9Tn0r63+FPja2na+1SW41CGys9CgF1dPcxjZOdwk8wP2O37uMg/WvqcLQUJLljrf0t+Gv4
DrYypV5m3bS3qXPiP4e1u/8AA+keNNPuv7a0O8tYJJb1Y/mtJHRSVZAThGbOCOAeOOK82inm
lkubfT7Vg6KWaWVflUdMDp+Rr0+JW0fwLqHh+x1Flt9UnS7h0yWRVNhDgEgopO0O53BCARno
K5LVrS/Ofs6zKwGwGLDcfjwelfN53RVTFLlXu2Sdv61IlRqOzbu3v3RoXnjlLAyQwSebcYGX
ldWDbuhAGMemKg1bxLpuqN4f8PeIHhW0unbUdQuFjRmTYH2KVbKlcAEr3zzmua13VtOs7IWW
kWscFtHEHKpbrnkfeZsZJz+VcV4rn1jxDfSXekaXe7Li3MCK0eHjBwOn+76etfRYCvhYKc6k
l0SXrv8Ah+Zx4qVSTjGn6/dt+P5Fb4g+INGvvipqmseFdMENiwPlmYAnfgbnRQAqZAJAUAAk
4qvH4Yu7/R21ifVBDucFEXGzHBG4nqeeKdo3hPxFbeX9p0u4hjZl3yvBIAo7kgKT+ldP4f8A
CGv3cjJFp85ihbMccgCrgd2GTgc55PpWdbGc0HKCtrsjWEWkk3d+ZX0W9v7PSw0N3M00snzS
liNwUjOR3yR0Nei+DviU06rp15GtqdpPyw/K/GOefSudsPCGowXiyXD28SsQrf8AExTEY/3A
pJOfRqsw6XBcapJYosc2xCzuWwpHqSR7nj2ry8diqka0ZRhdNJefUte76mJb2F4jRtFcYmQ8
BCct75GMHBrT0S18QyzIGa5Zny0myUqoGOoz3yPwr0vwPa2ot2YW0IbPURjNaDEi6MQP7v5v
k7flXFhcC1Hm5yo04tpdTh4rDXoxGZXZ/LUhy4w2BycnHJ/Gqc2oXt2XCXCwtcbEaTkqAO+1
Tj/Irs/Ek0vm6tF5r+WtgCE3HAO48gV5hdO8d5IqOyhZBtCnGOe1Riq1Sg705P569vuNJU9d
zoNI0SCXUI7G0uP7VvJk+ZZQVjgGfvcHJxXe+HvB1to9sPOVr+RVLtIwCIp/ujJ6f4VwXg+R
01kujsrMoyQcE813EN1cvBHvuJW+YjlyeMV2ZfetD20nq/wsY3d7s//Z
--------------020408080101040606010801
Content-Type: text/html;
 name="Opa.html"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="Opa.html"

PCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDQuMDEgVHJhbnNpdGlv
bmFsLy9FTiI+CjxodG1sPjxoZWFkPgo8bWV0YSBodHRwLWVxdWl2PSJjb250ZW50LXR5cGUi
IGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD13aW5kb3dzLTEyNTEiPjx0aXRsZT5PcGE8
L3RpdGxlPjwvaGVhZD48Ym9keT7A6+Dh4OvgPC9ib2R5PjwvaHRtbD4=
--------------020408080101040606010801--

--cPd7L1emUCelsk4J8wvEHRhGXeURciA9t
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX2HCAAoJEH+wSfeQEeGpaBsP/1NxA9Y0OAViVTCaM61Q+9kC
co0/G+Krd0g3qjjJM1aUJiYyUBTUwmVGjrkzxfA0oAC9QiEJlzmp40LVajQ8uDTM
C/CrNGY+FoCZg9NZe/qJR2zxe4IGHm66vw792O2UC/wCUc1yW5zAzf5mgweM1ibJ
Q0vhWZcZjkX9I/vP8staMy25AK+p4zynZTP0AsR4bZRaY8IPSqYx69dwbli+02+T
+OTOygf+lfitpcPPFWyRDQMjakI6AOwDWRf8xoYvLfpgsZc7zlYhbp+ku6Z989y9
4jJhkPenei0NZQpuXjLBxtuAm4gpiEKfjfv9G65dKqjmZP+ljQdsdI0L9oVY/64k
7sKJiSI+fqt+VwxyKBmR4h6cLGW0Le2mV3SvzZovtcuBwg5OtwGOaEgO/BZhZG9d
6UiTkDw0OVqePumuXCuamUvo1gkZY7xpPTzMJek1KayU09YxFM2wpyknnRzY1eu6
nM3sThq3N1wugCRiPaMLRq9AWWIP6Emc/ei5+k5iuBl2HvrkqxicscyzWGnlhUWx
4bcP5LlNPjb1js4Fafsl2COwGYPMewS+3rBZwPaE5brDR2slC8sbeTvumtSuCjfr
cYrqVp4aJzidKFqDT2yg35mrsg2ha3df/tyTkhAhaWNeCaRF7IIUf3+gtL4GuUwk
++afspHkeOINezOaJ2Cu
=9YhS
-----END PGP SIGNATURE-----

--cPd7L1emUCelsk4J8wvEHRhGXeURciA9t--
