Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 40B6914201E5
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:41:23 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 224B040A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:41:23 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092483; bh=Ni/RKIiff4vfhiMBTcqblTaAAKlIPTTCTflNuyae8GE=;
	h=From:Subject:To:Date;
	b=Ra78MRUXZq7p6bC+jwM5CyPQegAt4z2srPqtKTEMoA51hce/7FK9QEWjyq6sJ2LR+
	 MzmuiHGKVe3pO4Nx84uopQncyVyDQi0mm95YVK1Z/+a9zCqW5dDGFG0B+dEBSbTH18
	 OhcaUOPhErjGnU09VP+u0lVA5SzOmqdE88ZcX2Q0=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 0951234E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:41:23 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092483; bh=Ni/RKIiff4vfhiMBTcqblTaAAKlIPTTCTflNuyae8GE=;
	h=From:Subject:To:Date;
	b=Ra78MRUXZq7p6bC+jwM5CyPQegAt4z2srPqtKTEMoA51hce/7FK9QEWjyq6sJ2LR+
	 MzmuiHGKVe3pO4Nx84uopQncyVyDQi0mm95YVK1Z/+a9zCqW5dDGFG0B+dEBSbTH18
	 OhcaUOPhErjGnU09VP+u0lVA5SzOmqdE88ZcX2Q0=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F6582.4070006@voidland.org>
Date: Wed, 2 Dec 2015 23:41:22 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="SP1ropgen2arPEXnjMoAMkkgWwtC1NVQ4"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--SP1ropgen2arPEXnjMoAMkkgWwtC1NVQ4
Content-Type: multipart/alternative;
 boundary="------------080206040604000005080503"

This is a multi-part message in MIME format.
--------------080206040604000005080503
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

KkFsYWJhbGEqIC/QkNC70LDQsdCw0LvQsC8K
--------------080206040604000005080503
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body bgcolor=3D"#FFFFFF" text=3D"#000000">
    <b>Alabala</b> <i>=D0=90=D0=BB=D0=B0=D0=B1=D0=B0=D0=BB=D0=B0</i>
  </body>
</html>

--------------080206040604000005080503--

--SP1ropgen2arPEXnjMoAMkkgWwtC1NVQ4
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX2WCAAoJEMl6bvU0WTOvdlIQAITo6xqVeEKRJ0MLBqjCQzZn
aCcagfVhMlSLpF6nOm7UCfD9AcB7dp/hMrfRLam5WoqUGMDb8tFIeG058ezC5eWW
DemM89CEvuMQUq4rwGCzehUs9bhGLjG5R7dz7x5js+YduTIc7Os/tIekI6Z2QoX6
KVWExyq/8+hM9oi4SthPxLRVVbO8Vbun44ZCbSkRy0+FPzQhceByXHQnVQPpHlcX
vFo+n5Q227Y3+63nan0CIl8c96XUwPFqIKLDsJhpMz9IM4yhOnFXb+agOIuOJQHA
HabMTMVtmpLzHyFf3OE4boGNWSXuHKDElXuEZv/Qiwkjy1zZO7AnNUxpUT7W3LGH
7yC/xPcN1BGrnSd8ZtKQg5qvKPdahjTTzuZQwGwEd/iAPqgBjqcuj9y8ihNDvud5
wQKno24+JKRIN8H4Mo6nDUHExJX4d3HTOYqblmHnKxhJII4yaWHh9KK72g2RrIXx
fke+Odc27Y3LbQ0+AsqI4SZEcnvxGBt9PYIqd0Wp2Vb0lIgzK4KeaJTYiqHYoF8H
+FhYU8/fCxwLM6Qf4xqVo2kslMJ3PANtU8Vuuk9PBYf7iUGmvLURNzCJGP47iy9M
cOmDuNBpKIS+CSoUFawAYI/qX6hert/GQ6iKVBapzVTRipY/NkiHmXwz/lhQ2Af2
fvQrwh31aPmrPOUNA22S
=kbub
-----END PGP SIGNATURE-----

--SP1ropgen2arPEXnjMoAMkkgWwtC1NVQ4--
