Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 1A8FB142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:48:58 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id EFA42409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:48:57 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id D9C3934E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:48:57 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C249.2020105@voidland.org>
Date: Sun, 18 Oct 2015 00:48:57 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="b6uBdnUHrhFrDPb877aQ7Gt9ceuACNodu"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--b6uBdnUHrhFrDPb877aQ7Gt9ceuACNodu
Content-Type: multipart/alternative;
 boundary="------------090909010307040004040302"

This is a multi-part message in MIME format.
--------------090909010307040004040302
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

*Alabala*
=46rom - Sat Oct 17 22:30:43 2015

--------------090909010307040004040302
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body text=3D"#000000" bgcolor=3D"#FFFFFF">
    <b>Alabala</b><br>
    From - Sat Oct 17 22:30:43 2015<br>
  </body>
</html>

--------------090909010307040004040302--

--b6uBdnUHrhFrDPb877aQ7Gt9ceuACNodu
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWIsJJAAoJEMl6bvU0WTOvChIQAMLmR4Kw68vGurRLCV6EoZQU
ZvHC2vpVuP1aOuBF4affQ0ze2qZAyEv+7RH6lxvonntbxSE5FppNzsjhPdp7kR5/
ugc5Au0fARuJYhc6Ma7yOVI7BSERVqvavs2rpP6MTAMZZnHRsAaBu3xXxxpY/f75
QZMWcFCWrZOfwyM/tD8Gej6xMFfPAcOCIlzp95Q2M7AHRA9VDnjngtSfianiGqRr
Ov76vlC3gJHXPhHelk/YaRNYtN+5/8Vu9lIwPWpy8l9OEhK6XMqFolpcYTFeEyRw
YYafT774KPYlhGBtyGKPPwM9jTqFheasLqy0clm/tZwN7PyQ/1ovlF/bgWaCNqLq
mk5XfLLaLgxwu9ueZDvxu6DISL9hyk3JM9IWw3Q+TyPnS4bxrW+JRmBVr5Gk0hfp
gM0WsksS3jEWX23JuQQdA06NsckpaUUe3FwEHc+GxOLUs7gUlv0KyYEI/pQdHdkH
FuRaTRjeHq/alFFuV75tvSeSC3Vx++QQEvCmd9B8EyZbAZKbtShWv40HHXeaBdTL
fvXUvI1nEAxyvXptR4lbv9fZOiXi0pQwBIZFKptxCIHYiBW6Iw0MEAcdxbH2Rg0o
cNjJr/Gi5sXh3YcbvTaJTDmWt1+mbbc0BveKwgA0UNoMD0x7FYoSiB7t1Vjl5k2y
NDTRPhyngl5njxd8LFdj
=Brgr
-----END PGP SIGNATURE-----

--b6uBdnUHrhFrDPb877aQ7Gt9ceuACNodu--
