Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id F419514201E5
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:43:04 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id CA2D040A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:43:04 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092584; bh=D2TLDAdpm+fjK70CW/j088nStdidPvC5r6zWbPI0ZXQ=;
	h=From:Subject:To:Date;
	b=EtxS0LPRwDimetTFnD8CjwhNZerPRVIeciQa5OGGUo6RJEHdzrpWtoEPLoYx4CPQJ
	 YmCMJN6/Qp4hJXi3Xo6CZ+VBRJvtYKNrnwXIO9tIoJOucd85BI5WDpGFWjFKsP4a2M
	 vCXmwQlNn20/JhcuyDxN8Ui3MCKA55uj0rYqXstM=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 90F5F34E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:43:04 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092584; bh=D2TLDAdpm+fjK70CW/j088nStdidPvC5r6zWbPI0ZXQ=;
	h=From:Subject:To:Date;
	b=EtxS0LPRwDimetTFnD8CjwhNZerPRVIeciQa5OGGUo6RJEHdzrpWtoEPLoYx4CPQJ
	 YmCMJN6/Qp4hJXi3Xo6CZ+VBRJvtYKNrnwXIO9tIoJOucd85BI5WDpGFWjFKsP4a2M
	 vCXmwQlNn20/JhcuyDxN8Ui3MCKA55uj0rYqXstM=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F65E8.2010504@voidland.org>
Date: Wed, 2 Dec 2015 23:43:04 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="xCaUsAlGMRrFfPqD6bTaCOPJlxt2f8SoH"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--xCaUsAlGMRrFfPqD6bTaCOPJlxt2f8SoH
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body bgcolor=3D"#FFFFFF" text=3D"#000000">
    <b>Alabala</b> <i>=D0=90=D0=BB=D0=B0=D0=B1=D0=B0=D0=BB=D0=B0</i>
  </body>
</html>


--xCaUsAlGMRrFfPqD6bTaCOPJlxt2f8SoH
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX2XoAAoJEMl6bvU0WTOvAQsP+gJ7YAbR94fDEda1v88uFobA
r0MoUz+2KRhRekdB34hwcBsXOnmL5nTHtyttGZQrB2HC9vFVdz+SilW4Feqr5yB0
LgCRzgO3CSvlshiRYC1xs7Ei+p4FEw5KN+Nz2AcuK+WH2GQu8DeDHTYmtFKm1NLL
SsiwyGGpxE4gf7iFEhb/aT84QctgFjoyqdcG/Bs3Ex2aaRTW06Q2M17NLXWu/rrw
u0EvflIeM1FgoxOftOqsjVdd7tt55nNeydJ6B3Gd416vYDsqszJ3ctbX5uudcInm
EwtgjtVov21kCY8oeNuFwyFlo1xb5vjJrUf90F2NpRp3CTbgz4iXr7qiiNkfTLnC
R1AN9l8dLXkWhd3Y22P3r85uOc1mTkTc0hGmvdtIupHfoI9ZnPnd1W4jAN9IIhxV
YecazK/JhwzPY82Dvbqsdt9VqZ394ENcq57YgDSyoQmko2vcOCSd7RUCSjUzG9n1
yj3xSW+a+9bw1naXknqNuDu3L31fpb44pdsrOtUXbaj06+YSDYQInOd7gAdJmyAu
rQ+/SC188aYqTzxZprn8cVUdZ50LqmvY8dGNljOqralo8XzHpB2ywv1ydwooK1I/
JzyTfUII3zoSzk3mbM6Cb/R4vOpuFjCNg5LbUx+OETu3EGkPqafz9oHu3ZkQnT5/
fxaTSEaaTkTTP/ntryWL
=OXQo
-----END PGP SIGNATURE-----

--xCaUsAlGMRrFfPqD6bTaCOPJlxt2f8SoH--
