Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id A503614201E5
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:43:55 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 88FF440A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:43:55 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092635; bh=ObC3uxdqCkue+WKxhOeFnalwCH1BWT5dWJAKjM7zUag=;
	h=From:Subject:To:Date;
	b=Z7xBKCiA54ZGvfewvV3QrtvitM04oj0M+S1n1n2XhAaDMpcgg/DBEpuyyF6aeuuQc
	 uPvBclgUhSVvBYmqXbSy037PszLwcMeTYR/2YVbdIgDFgOy9zFgZcSGtk2GTpwG9BS
	 YnS7lHmYqqUuzDNmf87keTe4IvuWvl0px8wezsQM=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 7051F34E012C
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:43:55 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449092635; bh=ObC3uxdqCkue+WKxhOeFnalwCH1BWT5dWJAKjM7zUag=;
	h=From:Subject:To:Date;
	b=Z7xBKCiA54ZGvfewvV3QrtvitM04oj0M+S1n1n2XhAaDMpcgg/DBEpuyyF6aeuuQc
	 uPvBclgUhSVvBYmqXbSy037PszLwcMeTYR/2YVbdIgDFgOy9zFgZcSGtk2GTpwG9BS
	 YnS7lHmYqqUuzDNmf87keTe4IvuWvl0px8wezsQM=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F661B.1060405@voidland.org>
Date: Wed, 2 Dec 2015 23:43:55 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="sC7qScKv0uXjPBn7WOXMTRmkj9xk3hXxl"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--sC7qScKv0uXjPBn7WOXMTRmkj9xk3hXxl
Content-Type: multipart/mixed;
 boundary="------------080103020501090409030101"

This is a multi-part message in MIME format.
--------------080103020501090409030101
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Alabala



--------------080103020501090409030101
Content-Type: image/jpeg;
 name="BorPetVlad.jpg"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="BorPetVlad.jpg"

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAQCAwMDAgQDAwMEBAQEBQkGBQUFBQsICAYJDQsN
DQ0LDAwOEBQRDg8TDwwMEhgSExUWFxcXDhEZGxkWGhQWFxb/2wBDAQQEBAUFBQoGBgoWDwwP
FhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhb/wAAR
CAA6ADADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA
AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK
FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG
h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl
5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA
AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk
NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE
hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk
5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3J/GXhpbpmiBaOGKIgKcAhs54PORj6VxX
iHxPFda5O4hkktfLJgAMahhzuQkZG7GD39K8c0XUb3UPJQsAZmWMFjt3469e3J/Kpop9dttE
uUvbMpa20JSN0jxgjlGHvjI56/jXNHNqlSM+RfCcMcKtbvUwPFeoXn/CUSw21t9htbtvkRMM
iNzn9D+ntVW0F9batI9xtcrGr2/mFShbPOR/wHH410svh3SZ/DNnfvrMi6zIcvaG3MscKkkA
uV5B24boe1cf4gm1IXUaWcsgu7eQxxzLbkr8p58tiMORnOBnrXiPD1q01N7u3nrdfodEqMkt
iT+0QfEEr3uG3NhYkUFSvcemetdh8O7600VY5NTsIfKkO/yZ4EZdpzwMjI7HAIrlfES67BfW
c3iC5bUZJocwzyhPOU8H59oGRyMbhnqM1n6lcanEJIuWZwNoAG7I757dO1ceLlXwuJfsHquv
9fjfQyrUp7NanpNjZ+H5/EsqwXF1eLFbeZFuIx8wIJJGMbTntycVleJks9L0a5Nzr8llptnb
y3DROoZmlVflVT15YKAOlTR6Np5kDqJQQu3du6r2XjtXJ/HOwtbT4c3YtUH2iR0QbgW4Jy2M
9DxXbgsZQ5lRow0k/wAzvVNQV7GFr3j61t7vwnqWmaWbaKLTFN5bJMgN6GcB1LDJLblPzn5s
kjHFe5t4b1tPCuo/2rd+ZbaXozXUcVjJtnjuEi8xVUEH5VPHfeOuK+JbWG5REkMbAszENjAy
ew9Tn0r63+FPja2na+1SW41CGys9CgF1dPcxjZOdwk8wP2O37uMg/WvqcLQUJLljrf0t+Gv4
DrYypV5m3bS3qXPiP4e1u/8AA+keNNPuv7a0O8tYJJb1Y/mtJHRSVZAThGbOCOAeOOK82inm
lkubfT7Vg6KWaWVflUdMDp+Rr0+JW0fwLqHh+x1Flt9UnS7h0yWRVNhDgEgopO0O53BCARno
K5LVrS/Ofs6zKwGwGLDcfjwelfN53RVTFLlXu2Sdv61IlRqOzbu3v3RoXnjlLAyQwSebcYGX
ldWDbuhAGMemKg1bxLpuqN4f8PeIHhW0unbUdQuFjRmTYH2KVbKlcAEr3zzmua13VtOs7IWW
kWscFtHEHKpbrnkfeZsZJz+VcV4rn1jxDfSXekaXe7Li3MCK0eHjBwOn+76etfRYCvhYKc6k
l0SXrv8Ah+Zx4qVSTjGn6/dt+P5Fb4g+INGvvipqmseFdMENiwPlmYAnfgbnRQAqZAJAUAAk
4qvH4Yu7/R21ifVBDucFEXGzHBG4nqeeKdo3hPxFbeX9p0u4hjZl3yvBIAo7kgKT+ldP4f8A
CGv3cjJFp85ihbMccgCrgd2GTgc55PpWdbGc0HKCtrsjWEWkk3d+ZX0W9v7PSw0N3M00snzS
liNwUjOR3yR0Nei+DviU06rp15GtqdpPyw/K/GOefSudsPCGowXiyXD28SsQrf8AExTEY/3A
pJOfRqsw6XBcapJYosc2xCzuWwpHqSR7nj2ry8diqka0ZRhdNJefUte76mJb2F4jRtFcYmQ8
BCct75GMHBrT0S18QyzIGa5Zny0myUqoGOoz3yPwr0vwPa2ot2YW0IbPURjNaDEi6MQP7v5v
k7flXFhcC1Hm5yo04tpdTh4rDXoxGZXZ/LUhy4w2BycnHJ/Gqc2oXt2XCXCwtcbEaTkqAO+1
Tj/Irs/Ek0vm6tF5r+WtgCE3HAO48gV5hdO8d5IqOyhZBtCnGOe1Riq1Sg705P569vuNJU9d
zoNI0SCXUI7G0uP7VvJk+ZZQVjgGfvcHJxXe+HvB1to9sPOVr+RVLtIwCIp/ujJ6f4VwXg+R
01kujsrMoyQcE813EN1cvBHvuJW+YjlyeMV2ZfetD20nq/wsY3d7s//Z
--------------080103020501090409030101
Content-Type: text/plain;
 name="Text.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="Text.txt"

0JDQu9Cw0LHQsNC70LAK
--------------080103020501090409030101--

--sC7qScKv0uXjPBn7WOXMTRmkj9xk3hXxl
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX2YbAAoJEMl6bvU0WTOvp4sP/jvw62oPRkjbLe30OJUFxbxl
CJbkUG3kK9+Uk5QgyvTNkjyjNS4Yh5bOZI7LWtc3xDyRqtu1nXUFWyQnzAxJngiI
iUjnNszmFBlchZbHruzOqKG75/RBwuXx2UTRZU1O2PEJieBPCxsfkmWKewok1e+I
W2IeaQ8TSeWdBtOkXlxEqbxabceh/82Gq8RCISSzNx+JTCqCGHmfAMGt5Qi3QVt2
dQg32uEoIgnCjw5UgDJZoi0TaE6gLao2rRPZ2sHkb3rmCCn6YKFSE3YRJh4XHkPu
wqCa7Nw6+T3DjeRkWjbFuM4Wb2Y35f05ewMicFrSmX1+bG+8duuicvB2GkDO+yyH
bkSIyq7zDV00T6I+ChFb2m1nHxIdzj5oLZtnYEsPQla8hzR42bduOCAC0/oV8xT7
UHxzS+HeJCUIqbmLwjKw9hRe9o5OjJR3n35DtT37XPGhQWC/bHXtJ7iVSRaWutHa
YlP9w9ZoF2lp24JV/UDcGc7S/D0xhubrzx4o2uSejBd/F4GJmGu1VVTFxtvKrBM+
sGSQ6kTtSVCR7HX1pJTqaHbfb6kYSmRquqS9WG4CnimXcl1eLw6YcgpyU1BpwTwT
cYJJivfK8w5WvRGWhnb0yPrDBMCVeQC5fNTE76yRQNGd6ZQQZbll+Fw3iDyzBSc5
FJUlD5UqL9mdzdGMcW5f
=YDrp
-----END PGP SIGNATURE-----

--sC7qScKv0uXjPBn7WOXMTRmkj9xk3hXxl--
