Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 18E281420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:08:31 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id EE65440A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:08:30 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090511; bh=HvzGTTSz0w6h2guKXsSRhpHWzZdawbpRteMTn2XBuTM=;
	h=From:Subject:To:Date;
	b=tThFJO8VPo+QBG1mi5//zep52SjbUXenXU0i8a9TMNv7Q+Yu+0PiCcosZzV68Poom
	 eO8imyjDr6pCbmBi2kvaTPeQj+j+mA7um6JK4E7ZNSDkQNDvdy9vrvlb4EdOGVxI2I
	 IgK//W0W/P4HwCT3qjeYaPPLy/b/ALMDNjOOX8ZY=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id E406034E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:08:30 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090510; bh=HvzGTTSz0w6h2guKXsSRhpHWzZdawbpRteMTn2XBuTM=;
	h=From:Subject:To:Date;
	b=kHMfTu37RPOaVeBhJ5RLVoaHVnqzG04v/oyzdUeS7XVp8KHd23IAusSPVxjzm5y40
	 kWl+o4mG10PSZb5R4W8R5YdA3FCC1YT8eGkWfDf0l5XC/AKy5PWvezR/sNnU7jJiGD
	 BZwIcLcoEb4O9XzbWVoRiAstpCq9wK1EKTIOeHkA=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F5DCE.6070801@voidland.org>
Date: Wed, 2 Dec 2015 23:08:30 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="5qqmxavqw523reIfasPOqw26TWPjEu1rm"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--5qqmxavqw523reIfasPOqw26TWPjEu1rm
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Alabala =D0=90=D0=BB=D0=B0=D0=B1=D0=B0=D0=BB=D0=B0



--5qqmxavqw523reIfasPOqw26TWPjEu1rm
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX13OAAoJEH+wSfeQEeGpAy0QAJICvnP43rPEiqR8ptUgOqUS
4grPmQhbJHpTDgIczHTVxhCEIdJytOJsj6IgWnOySInWHBU8n0nz+WVq0tQ8c6zz
YppkpNdmHKUXWTdrT3uvPlvsRoGsJE4BwHNuwR693iWkjaHhWPJPL6//IL3T06PC
eXe4J+TsX7htKtvQ0OeBOq0p8peD6oF6Sa+VYEVmw8u+DaKJMXnIcRJ3wPSI2nUO
gdGbFWqhcaILs3rDgSt0R8L/JlbZVVA7LGav0XvuArd5IPhvIEgM/2FS+DPv/29c
Dy+XpeLPq1LeD3cE1RuEydAzR8cKnaVkeEdzhUAIGx93f5AWC8XAukJWAEGgPU5v
WmtUYAnig3hoPFD7zyAWIOWnZs4QMiLyaey1Vh6SlXbpJv/j6Sc/0OWvVZmORJqr
Zf1ibzWmhlVVbv2UOXW/MpmdLYeqvMbQrl9Spzc1glNSNni45mDMYOiUFn9Jvzyx
BZKdI1qArOdhzFMgEJFIW9cgCB3Zjcr4bvB7ikL/3rij9p7+38Ab65fGy0hNHukN
QX1oCWMgVPMBVbTKNhaVBZ9PBIIbhVp/w+e0Ll7/SAF2LeYU4Plh4u8qPD0hLCRc
VSUwrvc5zkyin6sgvebOMTTefKKNt5zHbuBq1s4rQ11eDlw1F3VWvvw/L2v6+v0a
VZNz+uqHDsCWWYXl1qLz
=3F+n
-----END PGP SIGNATURE-----

--5qqmxavqw523reIfasPOqw26TWPjEu1rm--
