Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id B40AE142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:11:27 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 9AFE5409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:11:27 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id CA72534E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:11:27 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C78F.6080502@voidland.org>
Date: Sun, 18 Oct 2015 01:11:27 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="0R3cveMG4fX2kfrbEFIMGvSNIJSfw7NWM"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--0R3cveMG4fX2kfrbEFIMGvSNIJSfw7NWM
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body text=3D"#000000" bgcolor=3D"#FFFFFF">
    <b>Alabala</b><br>
    From - Sat Oct 17 22:30:43 2015<br>
  </body>
</html>


--0R3cveMG4fX2kfrbEFIMGvSNIJSfw7NWM
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWIsePAAoJEMl6bvU0WTOvxvsP/R1NzNocMEPcKrYaNQeUIKo9
V3vDJ4oWLNQroLsrPU3b/+XdXgZZs9Cqu6hjwo6ebBNV9kCKVE02RIao/qWM/0hz
Ev+t13MeC2Y5UMjCHyTBHppXm+ek5tMAa2UXLZctCsXSACxgnSuT6t2I/7kawLe4
1m8+Q2tpm+wPkLYHzfkk1T4+4mBbH9TlPW41nTk4W/odTDYp8pno4HZmVJImmjBs
mt/M+RUyZqIkoRNyVlpj7KGB9zUJ0CLzrT4zoM3BRYec26RoaUzTAOTS9NvRXBVM
/4ESEJg9h45DhylnnvXAcQieAtNwb0kE/1jTRIa8BkQrGXUkmH5UKQFPoAMMDzpT
0uCM+H7owA1OfttGT5ERapWd6Hrrne2x81656mGQfuVr8YTdnWRU4+HyA0T62Xs8
ix3ZhdctCyuL49gXQ1sZr41ywW4LSLsf00Q2YwzgRgno+o0X/JKwTPaOje0qUEvl
v1wwVgSA09kKJeczRj7jS6czhszygn54Nz1jncSk5GoMyMo1aHaqoUnxbfXSQVmW
5i6khfxJ4Hv1TfHjKR3NCGWmzXivUyx43miACrNxsE3lrivwgGAnFznr3/P6G7ui
MRwTdlWLEMKgLcgv7B1BCu1N5fRskU8dTGYxjMWo3zOmmprdx2VJhpRSwAQdYQEw
24Hv6DkkQQobG4+XGuHH
=Vnf8
-----END PGP SIGNATURE-----

--0R3cveMG4fX2kfrbEFIMGvSNIJSfw7NWM--
