Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 0CC80142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:10:48 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id E04D3409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:10:47 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id E8F8734E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:10:47 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C767.3000404@voidland.org>
Date: Sun, 18 Oct 2015 01:10:47 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <b>Alabala</b><br>
    From - Sat Oct 17 22:30:43 2015<br>
  </body>
</html>
