Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id E26EA14204D3
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:39:52 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id BE138409F8
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:39:52 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 9EBF734E00CF
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:39:52 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622B217.4080904@voidland.org>
Date: Sat, 17 Oct 2015 23:39:51 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="kJuaM68ic5aREuXxVMTNbM4SbpAml3PRO"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--kJuaM68ic5aREuXxVMTNbM4SbpAml3PRO
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Alabala
=46rom - Sat Oct 17 22:30:43 2015


--kJuaM68ic5aREuXxVMTNbM4SbpAml3PRO
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWIrIYAAoJEMl6bvU0WTOvbFIQAI8Pko2zI1YaEsgcW6vKUd9w
dfyDFpNiAeGKkys/tXgu0Pb1+H4E8n+LE4SFJFNWIm7IMbEZqI9lwh++RsiHh3nk
i3ulBPaEeIChfdxJxoK/d5WnZCNBdplRidHJU1sR9OcToyGj6qEt3YbrZKwU9ymc
dJD+K78LxXRU1glplDPmIBRKkk9PhOwd8rQ/irZHIgbZY28ChETRr3Czt/L0JtVs
/qOzdM1lqmePZdyeMX89SAx6sW75ceQu4+FDvjrmzsxEZuTXBHI3kOXW3EEAEk4l
P0Etz3fK1RT3q6/cwUS3lh6M1whgHA2fol6cBi+ffQh+gfWt4+T3PjxKpJFB5DVG
WXVqA/23yXqpeYDdVey/l0vvEOsiD5LXh19bSYiLXIfydnjDLNgGUInHt8LF0Kjm
ax1Hvib/rYQdKpElBIeNehbqSremuUfIk2BFzjx3BRxsYwyVKVhGy6qgELGOQdpD
YzMvGMj/6q9CaFyMmhgCIoA/iS6tFyfMKV9BQXkpPqlbKSQ7DJcJKg+SxviGKkEy
4Fy5cBX3aSmdWuOVP63KgH5Pq+0aaH33Oxo6/PaE5J5I1pki0YGoWElOajyTRhkg
fMzCfXGYUXGTKyN6sdRh/N9nWkvFIPwihRkpszMyaAiSs3vqjbHWkp0gR0HyJhbP
vAthZ6AdUZnTtRnTpHYz
=EmqZ
-----END PGP SIGNATURE-----

--kJuaM68ic5aREuXxVMTNbM4SbpAml3PRO--
