Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 1A37114204D3
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:19:47 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id E7869409E2
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:19:46 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 1551B34E00A5
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:19:47 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C982.4010804@voidland.org>
Date: Sun, 18 Oct 2015 01:19:46 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------040806020401010105010607"

This is a multi-part message in MIME format.
--------------040806020401010105010607
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Alabala
From - Sat Oct 17 22:30:43 2015

--------------040806020401010105010607
Content-Type: image/jpeg;
 name="BorPetVlad.jpg"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="BorPetVlad.jpg"

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAQCAwMDAgQDAwMEBAQEBQkGBQUFBQsICAYJDQsN
DQ0LDAwOEBQRDg8TDwwMEhgSExUWFxcXDhEZGxkWGhQWFxb/2wBDAQQEBAUFBQoGBgoWDwwP
FhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhb/wAAR
CABEAEQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA
AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK
FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG
h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl
5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA
AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk
NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE
hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk
5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDatPHl691ps/mmU28DgFpDnGBg8+mMfjVS
PxXJeah9la3Ty/J3CeWdkcjdgqoHGcE8+nWvNdCec2W+cPHEvyKJTw474H/fI/CtW+0S6u7O
xu7C6VpI4w5KPtWIFjjcBkjjGPXNeTRzCvWrujfRL/I5aeHpRlex0esX9jZaD9jEStZSAvA+
dxVuQyk9AOcnA5wK8w8UW1tPdRzwwyLMxX5l5BHGBntxXU+JbLUtL0O3sJkUs9xviHmgquU6
AA5ByR165ropLnwenge30ZdGttS1OKDE90tyInM3qrYO4gkYBwOKxnTqTxXvSVl+Xb+v+CdE
KEneUE7dThry3tLjSbqO5ih8yJcLGWxkhuxHcAE1FpNzosyPBrOv6TojAFUa9LtvY88bFPHb
nFWdY0mWO+itdB0TWdUeeMbrZYhLLFI2Qd8kY287cjp+lYfhHwy+seIY5VtpWt52/wBYYyRA
MsCGX7xO5CMAc0sLl69pT53ok/zv+X5ClQneLtuJcWE1lq3lW93BdW74kWSzl8yF0J6ow5x1
+mO1bmmy2NlaxwQLJ5oJYzCbgspxg+3NZOtaXJ4e1yW1tpY5IrpBLII1IWFjwQQwHJwDx6mq
2p2e3bI0ke5eSqPyc55Kj/PSvGzGjJ15RhLRbP177GVWjUUnF7o09R8UyRXHlS6msTJxhI94
PJ5zkdaK5W+sdTluDIrbQ3YYH86K86OBhbV/19xz+yqHr2reGEGqWlg+tRu11EJU3jyxtx94
g/Q9M1PrmgWRvo7nTLqSL7NFH5BKhiSvTJPHJwcVy5TWW+wzlWY2bh2WWMMrkgZUAdBjA69K
2L3UNbupCyadaxpkELkhgB/n9K+ow0sHhpScHZM9KNHexi+Pl1a38G6l4q8R3ccdraSx2zLb
/IXWRwGCAcltu447AZ44rD+OHinSrHW9BuPB0ltA2nWruRBCvkvC4X5Xxjcx56jIz2rm/wBo
6/1GOxsdOvr4iF5XuDbrnaeAoLZ6nt09a851DxPqurLYz3csW+2hFtvjjCl1B+8+OrY4z7V6
lKnGvFVVszro4xUIOnb1PqLwjql7qfh+51/w1p93daW08UAzGjXFxMqfOwU/II1Y47nAz3OO
mk0nUrXxp4T/AOJ79lv/ABUssV/aXEYWG3CLuLwuo3BvlHXPfHXFcX8AvGU9j8CbNobRorfR
LqRLi7CBkVmk+XceoDb+3ORXbfHGO+1zQPDer6fa32neJPD84u7RJ7Z2jnyBuhLdAr4HPb86
9WhGnzThFNaK/Zp2vZnJPEVfZwu1ZO68mjh/ipBrmneJTpWu2rHUIxuWVn3Jcw5+V0boV64x
6Y4INczNcWVneL58qqxG0RldoZjno3avdPF3jfRvH37PttqEujJ5q3JW0kmBM1q4ba4XGMjg
gjofQYzXi99oenJ5d21vJIykMsZkwGGeoU/j+VfJcQxi8W/ZtKLtt6W7eRnKFaMVKfXXvuc7
rGoXUt5kWERVUUJ5jNkDGe3HeitjWNY0wX7q1zcRsvBVGcAUVwxy+NlZ/iJJfzHolvaX5UIY
WXKqSuR6d6sSWF6md1qd2eACB+J+tYI8RWumlYkWZpWUyJO0u5ZcZHB/Kjwr4kvNU8Wwm7mB
s4w8s6MgCFY0LkMe+TgfjXp08io1JqCbbfp/kbzqqEXOWyPNP2lNF1XVfF1lYrp0zXklsiwR
QxGSSbczEbVGSc+1eSNpUkHlQOf3m7i1iBMjseMN7+1fVHw/8WaXrvjDXfGfirUb+xlshHEk
1ncCISRKCfLOBuAJxwCM4A6V4T428S2eo/Fi81nwzpken2s0zsFVekjDG4k9yck+5NfWf2as
JTUE1yp2Xd99PU86niY1WrJ3au+y7K5d8M6pqWieCrrwrqNw1pa306TERciMhvmEmAc8HqOm
BXtsvxR0i91yx8OWHjNriyig3XWqTKGit41TiNFAXzJDjAzwO+a+fdH07UfFGpIpnMMZOJpP
4s85wPbBqzN4TXSb5biC9mEOQQzEE8jP4Z9cVLxEab5V1Opbq+qXQ+g9Q8SaBrth9i0uGaPT
9PUNGX8uFrpnJ3O0cZwMsTwPqaqReH7jUMmxikYBRycDGB/CT1/CvJ3eRNLtraBT525ZN+eY
xyc5/Gus8MfEq5sYUtLucpEihFby8uFHbIrxcZh4PEyhLayfmbrETk7vY1dY8M6paXKxTXRi
YpuCsFHGT7fWituTxEjpGYtTymzj5WUDk8DDdKK5/qNJaW/Irn8l9xyx0PT9I0+OTVZdQ1O+
aNWJku2jigGMYCpgfl+tZ/mW1poN9cWsLR5P2aMtKzdeXxk45+X361mXmpXF1bwK1zJ5McYV
zkDcB3Dcnv19aoT6F9qvhfHxEkcW0IIRFICR6vkYJx0Irry/OMNQrqq435V+P/APOxUHVpOC
drnH63qzReGWhi3br253SkN1VCwHPvmqGkeQFkclc4yQTz1r0ey8BeE5pN8useWGBVjDbMRn
sTk9a15Ph1oKKmNQuSZsOsjiEJkDrsPXPcdPatauOqV+WVrJea33bNadHkTt1OF0eefTbj7T
Z5JuXG0qMpv9Qen4etaaQSX07z6gW8+XG0PjZsz1OOAP8K7a58HacI4NR1e+kuF3CMEybUQf
whYkUD8h61qalp/g/S7ONjZSXcuBlpCY1VscADH86itKdSpzRtY0jHucHpdvezqtxcxWnkyH
EDm6QscHBG0YOevAyRWg+kQNDukihAGBsXjA4z/Suitrrw+dRF3pvhLT2u4Wys0UQZ1H+9jr
g1Dfi61vUFEexXi+V08vEgAOQMgdTk9c4Ary8zpyxFVThP3trBay5TCvtFneRSt/cRjbwsbD
A5PqvWiu9uNJvgsZstHiETJkmSEuzHJyc+9FKODxiWtUm1Q8z0W0hu2a1mBKLkjnn3/OoJFc
XEZM0jblwQWznEmM/XHFFFeLD+Kl0CCTizc02NJdQv7V1Xy45BGo2jhdufT179at3DeQkhhV
V8ho0Xvw27Oc/SiirrSleWv9WJpaxRo3EjxmNEZgrkbl3HHTt6dB0p/hvRLfxDdyXGpXFyzM
4TCyADAGfTOaKK78POb5I30No/GaXiy1g8NXxsNHT7PGwwzAks3GeT9a7bwf4Y0nTtBi1CKJ
pLiSJWkkkIO884zgDpmiit8Ol9cmuxldurqR6tfulyEWGHCrgcH1PvRRRXpXZ08q7H//2Q==
--------------040806020401010105010607--
