Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 883EB1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 22:52:42 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 6A60A40A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 22:52:42 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449089562; bh=pj2vaN57x4+2kHxyJce7shwviaf622SWNTd07+x1P7g=;
	h=To:From:Subject:Date;
	b=uJvBoKTs8jdi1AiQ6aYwGqyPku9w30j8O3L229gBDJM7x3acUNV7h8oCcheFjyNbp
	 ArZD1kdsqJfRHRcL8423ikmHS+e1OG0VW8yA6EhxgX9mHlrA5K8v/IwZA4HVjF/NIt
	 upRDzvQJ6MxhDf48/ULqxCUh2SbkFN2E/+7o0GuI=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 5916934E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 22:52:42 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449089562; bh=pj2vaN57x4+2kHxyJce7shwviaf622SWNTd07+x1P7g=;
	h=To:From:Subject:Date;
	b=uJvBoKTs8jdi1AiQ6aYwGqyPku9w30j8O3L229gBDJM7x3acUNV7h8oCcheFjyNbp
	 ArZD1kdsqJfRHRcL8423ikmHS+e1OG0VW8yA6EhxgX9mHlrA5K8v/IwZA4HVjF/NIt
	 upRDzvQJ6MxhDf48/ULqxCUh2SbkFN2E/+7o0GuI=
To: gbr@voidland.voidland.org
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
Message-ID: <565F5A1A.8030602@voidland.org>
Date: Wed, 2 Dec 2015 22:52:42 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------010403020801050201010602"

This is a multi-part message in MIME format.
--------------010403020801050201010602
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

*Alabala* /Алабала/

--------------010403020801050201010602
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    <b>Alabala</b> <i>Алабала</i>
  </body>
</html>

--------------010403020801050201010602--
