Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id CA36B1420210
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:08:49 +0200 (EET)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id ACC8240A2A
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:08:49 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090529; bh=sVZ985UFkOvIQJM9FrhxkzSBySch3hIZ48kx9k6AkeY=;
	h=From:Subject:To:Date;
	b=uOLgqtQQWJMrKPc7vVV83AY23AIVBBpa3VDI4GJIOwnQfPcs3Wd+hES66W5MOfsy8
	 zbfCP4d7OWG0LsBwga1urL5q5vgwziz4rEIxyUMT9mFTHs16a8E5dvFN3H/hWnC2k8
	 skXuaByCTXTX9SHLOj968luMLEMb7ns7/8IzC0L8=
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 9FE3634E0124
	for <gbr@voidland.voidland.org>; Wed,  2 Dec 2015 23:08:49 +0200 (EET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=voidland.org; s=mail;
	t=1449090529; bh=sVZ985UFkOvIQJM9FrhxkzSBySch3hIZ48kx9k6AkeY=;
	h=From:Subject:To:Date;
	b=uOLgqtQQWJMrKPc7vVV83AY23AIVBBpa3VDI4GJIOwnQfPcs3Wd+hES66W5MOfsy8
	 zbfCP4d7OWG0LsBwga1urL5q5vgwziz4rEIxyUMT9mFTHs16a8E5dvFN3H/hWnC2k8
	 skXuaByCTXTX9SHLOj968luMLEMb7ns7/8IzC0L8=
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <565F5DE1.3060309@voidland.org>
Date: Wed, 2 Dec 2015 23:08:49 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101
 Firefox/41.0 SeaMonkey/2.38
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="SaO2iS0EpbDKdCVOO8qofrLCNQe8hSjPH"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--SaO2iS0EpbDKdCVOO8qofrLCNQe8hSjPH
Content-Type: multipart/alternative;
 boundary="------------070008080601090507080101"

This is a multi-part message in MIME format.
--------------070008080601090507080101
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

KkFsYWJhbGEqIC/QkNC70LDQsdCw0LvQsC8K
--------------070008080601090507080101
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body bgcolor=3D"#FFFFFF" text=3D"#000000">
    <b>Alabala</b> <i>=D0=90=D0=BB=D0=B0=D0=B1=D0=B0=D0=BB=D0=B0</i>
  </body>
</html>

--------------070008080601090507080101--

--SaO2iS0EpbDKdCVOO8qofrLCNQe8hSjPH
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWX13hAAoJEH+wSfeQEeGpJ84P/1ntF3MK3RJPLF9zwHIEsrjr
Ztij/ZoX49/Ylgrs/1chJonI+FqQIw7sMQn3fcr38Vye5CpzX3koP+9QPknZERDO
18wYOhHqm3VgU3BQKtv5Fd1MDL9Tx5MsgywfSFyfee18y4CkVgIqMmlc703hjwn9
wcBa2T+Nqf4WFeH8XIuq4zF3SwIf/+pY2+NLTwutv5YHUrazs8Hpyd6VCGpaZX4j
d4pWjtKUYVbA3Zm5gnejxg4M629Rat11mlDyMMdP/L4s6TMiFjiLabSWfyVJCIIX
mwKAKenCno9DOAYPk2hdcQH+6o4KjtB1uAAO9ElNigWAchsq4hFnBrS6OCRP/3ur
k1MN02F+1ka0SIj2QCGD7lHydTiPMT57nsRbSoyYMfjHArSdGp61NG3LlMEU/iYC
ixGrS3hgCskRWCo6QA87NLhSv4Z4Ap2R3QrFH7NQzVP1GiTRvBslBE/aKxpxSCYy
JQgrW2sGiHzriCaCGVtyQziibpGuxsJKtcr3ThzKwyH527+17tyLLp29EaEOGVJC
BIuSLFulcU2Jg+qQaISqVd5ecJGUUD4149mwBVhh9iFJeGZmqg6LhouTdaGVmKYp
Cii8ma4h+1J00gtGfezdgNDg+vUFnbxmZFGMtLHnbiRfX/niqlAKLRLdB/Xkmef7
qC7oOp0xm42yc9s336bA
=xKPO
-----END PGP SIGNATURE-----

--SaO2iS0EpbDKdCVOO8qofrLCNQe8hSjPH--
