Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id BDECE142017E
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:21:28 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id A6BE6409F8
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:21:28 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id C208534E00A5
	for <gbr@voidland.voidland.org>; Sat, 17 Oct 2015 23:21:28 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622ADC8.5010508@voidland.org>
Date: Sat, 17 Oct 2015 23:21:28 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="psw8IQ5iVnmJBOQwwcbDvXvv8MjKAi0JB"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--psw8IQ5iVnmJBOQwwcbDvXvv8MjKAi0JB
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Alabala
=46rom - Sat Oct 17 22:30:43 2015


--psw8IQ5iVnmJBOQwwcbDvXvv8MjKAi0JB
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWIq3IAAoJEH+wSfeQEeGpOkIQALv1LeUen6I+BM9Ebl3aykNX
7Yjik60+ngl1OCmtFFv2IvFamanT/0UqHHi5dL9oNM3F2B7Uylg550LQusqdqcHP
TxFhDP6FRwZhefaaaKFYpPmD88+qN60MuY3mcw7uwPHUVpi/Ww6+tekjqww+2KA7
YmWY6w12aH7s2bPtJaFsUF9GFJ/lExzN1t02AE/VrfrKkK6cgNya5Y2j/MxRPrhR
4sm8l29NVeL9+YA4CjgnQ16EN1UkoiYJFSoyU8cS/Y8ecA+e3RiTrZLjKRGh4+Xg
QjsvPKaLmGQ52hVJKt3m5BNnqaHdr2f31P2S8zegTeg8y0N7qkXzIaBOB5fNo3xE
B342/9EI1Z6rYSAeXdfk42rWxOwEuszAvhl5ya58IXIGzjhdHZEzN2GYYiO2AZZ5
M7Rri3H+rir0ztyOslzum7KdPhPMgiCY76RHSmR0kFPrE/WVi2no4cYnmONb+pvp
NLT3T/Z9SCmn8YAOG42wB1H1GAIhUkG4aLz2FTEVJ4lvfymfbb8fcxRBT8T/VzDK
68HoOI9i96pbxFN9SAbg0fZA524qbiQSIOhPlMIxK2rveqCR2wCCmcxild/VE+Aw
5RtcNQC7Qii2a90RWlo5P/SZ0Toi0x3ETuz2s6wZM2CTmuSIbFeRVOLf2MVftjAO
sILEni/iSRMTF6Rly5Nn
=J0V5
-----END PGP SIGNATURE-----

--psw8IQ5iVnmJBOQwwcbDvXvv8MjKAi0JB--
