Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id 6991B1420017
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:28:15 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id 48416409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:28:15 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id 1773C34E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 00:28:15 +0300 (EEST)
To: gbr@voidland.voidland.org
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
Message-ID: <5622BD6E.7040000@voidland.org>
Date: Sun, 18 Oct 2015 00:28:14 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------040405030603040904050808"

This is a multi-part message in MIME format.
--------------040405030603040904050808
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

*Alabala*
From - Sat Oct 17 22:30:43 2015

--------------040405030603040904050808
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <b>Alabala</b><br>
    From - Sat Oct 17 22:30:43 2015<br>
  </body>
</html>

--------------040405030603040904050808--
