Return-Path: <gbr@voidland.org>
X-Original-To: gbr@voidland.voidland.org
Delivered-To: gbr@voidland.voidland.org
Received: from mail.voidland.org (router.voidland.org [192.168.255.16])
	by voidland.voidland.org (Postfix) with ESMTP id BCDD6142002F
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:13:10 +0300 (EEST)
Received: from es.voidland.org (es.voidland.org [192.168.255.1])
	by mail.voidland.org (Postfix) with ESMTP id A8601409F8
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:13:10 +0300 (EEST)
Received: from [192.168.255.2] (router.voidland.org [192.168.255.16])
	by es.voidland.org (Postfix) with ESMTPSA id D8BD234E00CF
	for <gbr@voidland.voidland.org>; Sun, 18 Oct 2015 01:13:10 +0300 (EEST)
From: Vladimir Panov <gbr@voidland.org>
Subject: Opa
To: gbr@voidland.voidland.org
Message-ID: <5622C7F6.1060403@voidland.org>
Date: Sun, 18 Oct 2015 01:13:10 +0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101
 Firefox/38.0 SeaMonkey/2.35
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha256;
 protocol="application/pgp-signature";
 boundary="iwGeeBNDsDmtoQGSLhOTolhx2TR2e5fba"

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--iwGeeBNDsDmtoQGSLhOTolhx2TR2e5fba
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3DUTF=
-8">
  </head>
  <body text=3D"#000000" bgcolor=3D"#FFFFFF">
    <b>Alabala</b><br>
    From - Sat Oct 17 22:30:43 2015<br>
  </body>
</html>


--iwGeeBNDsDmtoQGSLhOTolhx2TR2e5fba
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWIsf2AAoJEH+wSfeQEeGpMlEP/2LqkVkm1PqYM4xEkpe4WPIU
4oX412iuKPtveRCyNqU3oVrpXr/JDjj4RXc5Z/WMHjebV6gBcpbTgxrYK28jL1Vv
YVvTSWGhngX5b89NJpG8QEoHDBxXkkOG4TY/mH1/eFthtloSTmjdrv/kY7K3O6eh
sLeNQ1Jr3Gt7rit6mORoADqe+ZlQmBWXbRCUOS6pJM9XS6zUftQT0AeA3zeLGK7x
eWkaTgmfKlxuH+StVT8qdNRFtnFxKTRT68EakJrVkdTmtuUJEUUycmLMShf5RWip
KFVyVfBYhJUwfLYwp0beJIdHfb1BOgz+WZ6DW+sqFfB835bNLWtWUqn1vbjhqkUW
LHXTA7BC1qkur0XoHm1lh6AxBR+xv1mkpPI4/CEVF3/zxFyEaMypmn+6hqRnZAKn
PHGaZdHFRiLDjTdjoohD9Qks5d/JdK2LNEiHg+97F8RY0XzqOZY38n6L9gWC8zWT
QE8HYuNlq7PMOSlrkU1WAu7maGrlHM9TRykHsxiVsjTr8xK/1i8XC1TGG+H8YcYQ
dAbsmjbDnTd9IVWT7noS+8tv8adJU2lGrhh8Y+jK/bjxAMQbrXzPox8BN0JgEThU
iV0VxUEZsA/D370z02wIIddq6voWAxwqusJMt28zYrpuFhzViBJ2CupdLjLrysau
RdQZnP0H/FW3bOTVs52Q
=wkK/
-----END PGP SIGNATURE-----

--iwGeeBNDsDmtoQGSLhOTolhx2TR2e5fba--
